#Hotstring CO
#Hotstring EndChars `n `t
<^+0::Suspend -1

::a::အ
::qi::ဣ
::qii::ဤ
::qu::ဥ
::quu::ဦ
::qe::ဧ
::qaw::ဩ
::qaww::ဪ
::i::အိ
::ii::အီ
::u::အု
::uu::အူ
::e::အေ
::aw::အော
::aww::အော်
::ar::အာ
::ui::အို

::k::က်
::kh::ခ်
::g::ဂ်
::gh::ဃ်
::ng::င်
::c::စ်
::ch::ဆ်
::j::ဇ်
::jh::ဈ်
::ny::ဉ်
::Ny::ည်
::T::ဋ်
::Th::ဌ်
::D::ဍ်
::Dh::ဎ်
::N::ဏ်
::t::တ်
::th::ထ်
::d::ဒ်
::dh::ဓ်
::n::န်
::p::ပ်
::ph::ဖ်
::b::ဗ်
::bh::ဘ်
::m::မ်
::y::ယ်
::r::ရ်
::l::လ်
::L::ဠ်
::w::ဝ်
::h::ဟ်
::s::သ်
::S::ဿ်

::k'::က္
::kh'::ခ္
::g'::ဂ္
::gh'::ဃ္
::ng'::င္
::c'::စ္
::ch'::ဆ္
::j'::ဇ္
::jh'::ဈ္
::ny'::ဉ္
::Ny'::ည္
::T'::ဋ္
::Th'::ဌ္
::D'::ဍ္
::Dh'::ဎ္
::N'::ဏ္
::t'::တ္
::th'::ထ္
::d'::ဒ္
::dh'::ဓ္
::n'::န္
::p'::ပ္
::ph'::ဖ္
::b'::ဗ္
::bh'::ဘ္
::m'::မ္
::y'::ယ္
::r'::ရ္
::l'::လ္
::L'::ဠ္
::w'::ဝ္
::h'::ဟ္
::s'::သ္
::S'::ဿ္

::k-::က
::kh-::ခ
::g-::ဂ
::gh-::ဃ
::ng-::င
::c-::စ
::ch-::ဆ
::j-::ဇ
::jh-::ဈ
::ny-::ဉ
::Ny-::ည
::T-::ဋ
::Th-::ဌ
::D-::ဍ
::Dh-::ဎ
::N-::ဏ
::t-::တ
::th-::ထ
::d-::ဒ
::dh-::ဓ
::n-::န
::p-::ပ
::ph-::ဖ
::b-::ဗ
::bh-::ဘ
::m-::မ
::y-::ယ
::r-::ရ
::l-::လ
::L-::ဠ
::w-::ဝ
::h-::ဟ
::s-::သ
::S-::ဿ

::ka::က
::kha::ခ
::ga::ဂ
::gha::ဃ
::nga::င
::ca::စ
::cha::ဆ
::ja::ဇ
::jha::ဈ
::nya::ဉ
::Nya::ည
::Ta::ဋ
::Tha::ဌ
::Da::ဍ
::Dha::ဎ
::Na::ဏ
::ta::တ
::tha::ထ
::da::ဒ
::dha::ဓ
::na::န
::pa::ပ
::pha::ဖ
::ba::ဗ
::bha::ဘ
::ma::မ
::ya::ယ
::ra::ရ
::la::လ
::La::ဠ
::wa::ဝ
::ha::ဟ
::sa::သ
::Sa::ဿ

::kaa::ကါ
::khaa::ခါ
::gaa::ဂါ
::ghaa::ဃါ
::ngaa::ငါ
::caa::စါ
::chaa::ဆါ
::jaa::ဇါ
::jhaa::ဈါ
::nyaa::ဉါ
::Nyaa::ညါ
::Taa::ဋါ
::Thaa::ဌါ
::Daa::ဍါ
::Dhaa::ဎါ
::Naa::ဏါ
::taa::တါ
::thaa::ထါ
::daa::ဒါ
::dhaa::ဓါ
::naa::နါ
::paa::ပါ
::phaa::ဖါ
::baa::ဗါ
::bhaa::ဘါ
::maa::မါ
::yaa::ယါ
::raa::ရါ
::laa::လါ
::Laa::ဠါ
::waa::ဝါ
::haa::ဟါ
::saa::သါ
::Saa::ဿါ

::kar::ကာ
::khar::ခာ
::gar::ဂာ
::ghar::ဃာ
::ngar::ငာ
::car::စာ
::char::ဆာ
::jar::ဇာ
::jhar::ဈာ
::nyar::ဉာ
::Nyar::ညာ
::Tar::ဋာ
::Thar::ဌာ
::Dar::ဍာ
::Dhar::ဎာ
::Nar::ဏာ
::tar::တာ
::thar::ထာ
::dar::ဒာ
::dhar::ဓာ
::nar::နာ
::par::ပာ
::phar::ဖာ
::bar::ဗာ
::bhar::ဘာ
::mar::မာ
::yar::ယာ
::rar::ရာ
::lar::လာ
::Lar::ဠာ
::war::ဝာ
::har::ဟာ
::sar::သာ
::Sar::ဿာ

::ki::ကိ
::khi::ခိ
::gi::ဂိ
::ghi::ဃိ
::ngi::ငိ
::ci::စိ
::chi::ဆိ
::ji::ဇိ
::jhi::ဈိ
::nyi::ဉိ
::Nyi::ညိ
::Ti::ဋိ
::Thi::ဌိ
::Di::ဍိ
::Dhi::ဎိ
::Ni::ဏိ
::ti::တိ
::thi::ထိ
::di::ဒိ
::dhi::ဓိ
::ni::နိ
::pi::ပိ
::phi::ဖိ
::bi::ဗိ
::bhi::ဘိ
::mi::မိ
::yi::ယိ
::ri::ရိ
::li::လိ
::Li::ဠိ
::wi::ဝိ
::hi::ဟိ
::si::သိ
::Si::ဿိ

::kui::ကို
::khui::ခို
::gui::ဂို
::ghui::ဃို
::ngui::ငို
::cui::စို
::chui::ဆို
::jui::ဇို
::jhui::ဈို
::nyui::ဉို
::Nyui::ညို
::Tui::ဋို
::Thui::ဌို
::Dui::ဍို
::Dhui::ဎို
::Nui::ဏို
::tui::တို
::thui::ထို
::dui::ဒို
::dhui::ဓို
::nui::နို
::pui::ပို
::phui::ဖို
::bui::ဗို
::bhui::ဘို
::mui::မို
::yui::ယို
::rui::ရို
::lui::လို
::Lui::ဠို
::wui::ဝို
::hui::ဟို
::sui::သို
::Sui::ဿို

::kii::ကီ
::khii::ခီ
::gii::ဂီ
::ghii::ဃီ
::ngii::ငီ
::cii::စီ
::chii::ဆီ
::jii::ဇီ
::jhii::ဈီ
::nyii::ဉီ
::Nyii::ညီ
::Tii::ဋီ
::Thii::ဌီ
::Dii::ဍီ
::Dhii::ဎီ
::Nii::ဏီ
::tii::တီ
::thii::ထီ
::dii::ဒီ
::dhii::ဓီ
::nii::နီ
::pii::ပီ
::phii::ဖီ
::bii::ဗီ
::bhii::ဘီ
::mii::မီ
::yii::ယီ
::rii::ရီ
::lii::လီ
::Lii::ဠီ
::wii::ဝီ
::hii::ဟီ
::sii::သီ
::Sii::ဿီ

::ku::ကု
::khu::ခု
::gu::ဂု
::ghu::ဃု
::ngu::ငု
::cu::စု
::chu::ဆု
::ju::ဇု
::jhu::ဈု
::nyu::ဉု
::Nyu::ညု
::Tu::ဋု
::Thu::ဌု
::Du::ဍု
::Dhu::ဎု
::Nu::ဏု
::tu::တု
::thu::ထု
::du::ဒု
::dhu::ဓု
::nu::နု
::pu::ပု
::phu::ဖု
::bu::ဗု
::bhu::ဘု
::mu::မု
::yu::ယု
::ru::ရု
::lu::လု
::Lu::ဠု
::wu::ဝု
::hu::ဟု
::su::သု
::Su::ဿု

::kuu::ကူ
::khuu::ခူ
::guu::ဂူ
::ghuu::ဃူ
::nguu::ငူ
::cuu::စူ
::chuu::ဆူ
::juu::ဇူ
::jhuu::ဈူ
::nyuu::ဉူ
::Nyuu::ညူ
::Tuu::ဋူ
::Thuu::ဌူ
::Duu::ဍူ
::Dhuu::ဎူ
::Nuu::ဏူ
::tuu::တူ
::thuu::ထူ
::duu::ဒူ
::dhuu::ဓူ
::nuu::နူ
::puu::ပူ
::phuu::ဖူ
::buu::ဗူ
::bhuu::ဘူ
::muu::မူ
::yuu::ယူ
::ruu::ရူ
::luu::လူ
::Luu::ဠူ
::wuu::ဝူ
::huu::ဟူ
::suu::သူ
::Suu::ဿူ

::ke::ကေ
::khe::ခေ
::ge::ဂေ
::ghe::ဃေ
::nge::ငေ
::ce::စေ
::che::ဆေ
::je::ဇေ
::jhe::ဈေ
::nye::ဉေ
::Nye::ညေ
::Te::ဋေ
::The::ဌေ
::De::ဍေ
::Dhe::ဎေ
::Ne::ဏေ
::te::တေ
::the::ထေ
::de::ဒေ
::dhe::ဓေ
::ne::နေ
::pe::ပေ
::phe::ဖေ
::be::ဗေ
::bhe::ဘေ
::me::မေ
::ye::ယေ
::re::ရေ
::le::လေ
::Le::ဠေ
::we::ဝေ
::he::ဟေ
::se::သေ
::Se::ဿေ

::kau::ကေါ်
::khau::ခေါ်
::gau::ဂေါ်
::ghau::ဃေါ်
::ngau::ငေါ်
::cau::စေါ်
::chau::ဆေါ်
::jau::ဇေါ်
::jhau::ဈေါ်
::nyau::ဉေါ်
::Nyau::ညေါ်
::Tau::ဋေါ်
::Thau::ဌေါ်
::Dau::ဍေါ်
::Dhau::ဎေါ်
::Nau::ဏေါ်
::tau::တေါ်
::thau::ထေါ်
::dau::ဒေါ်
::dhau::ဓေါ်
::nau::နေါ်
::pau::ပေါ်
::phau::ဖေါ်
::bau::ဗေါ်
::bhau::ဘေါ်
::mau::မေါ်
::yau::ယေါ်
::rau::ရေါ်
::lau::လေါ်
::Lau::ဠေါ်
::wau::ဝေါ်
::hau::ဟေါ်
::sau::သေါ်
::Sau::ဿေါ်

::kaw::ကော
::khaw::ခော
::gaw::ဂော
::ghaw::ဃော
::ngaw::ငော
::caw::စော
::chaw::ဆော
::jaw::ဇော
::jhaw::ဈော
::nyaw::ဉော
::Nyaw::ညော
::Taw::ဋော
::Thaw::ဌော
::Daw::ဍော
::Dhaw::ဎော
::Naw::ဏော
::taw::တော
::thaw::ထော
::daw::ဒော
::dhaw::ဓော
::naw::နော
::paw::ပော
::phaw::ဖော
::baw::ဗော
::bhaw::ဘော
::maw::မော
::yaw::ယော
::raw::ရော
::law::လော
::Law::ဠော
::waw::ဝော
::haw::ဟော
::saw::သော
::Saw::ဿော

::kaww::ကော်
::khaww::ခော်
::gaww::ဂော်
::ghaww::ဃော်
::ngaww::ငော်
::caww::စော်
::chaww::ဆော်
::jaww::ဇော်
::jhaww::ဈော်
::nyaww::ဉော်
::Nyaww::ညော်
::Taww::ဋော်
::Thaww::ဌော်
::Daww::ဍော်
::Dhaww::ဎော်
::Naww::ဏော်
::taww::တော်
::thaww::ထော်
::daww::ဒော်
::dhaww::ဓော်
::naww::နော်
::paww::ပော်
::phaww::ဖော်
::baww::ဗော်
::bhaww::ဘော်
::maww::မော်
::yaww::ယော်
::raww::ရော်
::laww::လော်
::Laww::ဠော်
::waww::ဝော်
::haww::ဟော်
::saww::သော်
::Saww::ဿော်

::kai::ကဲ
::khai::ခဲ
::gai::ဂဲ
::ghai::ဃဲ
::ngai::ငဲ
::cai::စဲ
::chai::ဆဲ
::jai::ဇဲ
::jhai::ဈဲ
::nyai::ဉဲ
::Nyai::ညဲ
::Tai::ဋဲ
::Thai::ဌဲ
::Dai::ဍဲ
::Dhai::ဎဲ
::Nai::ဏဲ
::tai::တဲ
::thai::ထဲ
::dai::ဒဲ
::dhai::ဓဲ
::nai::နဲ
::pai::ပဲ
::phai::ဖဲ
::bai::ဗဲ
::bhai::ဘဲ
::mai::မဲ
::yai::ယဲ
::rai::ရဲ
::lai::လဲ
::Lai::ဠဲ
::wai::ဝဲ
::hai::ဟဲ
::sai::သဲ
::Sai::ဿဲ

::kya::ကျ
::khya::ချ
::gya::ဂျ
::ghya::ဃျ
::ngya::ငျ
::cya::စျ
::chya::ဆျ
::jya::ဇျ
::jhya::ဈျ
::nyya::ဉျ
::Nyya::ညျ
::Tya::ဋျ
::Thya::ဌျ
::Dya::ဍျ
::Dhya::ဎျ
::Nya::ဏျ
::tya::တျ
::thya::ထျ
::dya::ဒျ
::dhya::ဓျ
::nya::နျ
::pya::ပျ
::phya::ဖျ
::bya::ဗျ
::bhya::ဘျ
::mya::မျ
::yya::ယျ
::rya::ရျ
::lya::လျ
::Lya::ဠျ
::wya::ဝျ
::hya::ဟျ
::sya::သျ
::Sya::ဿျ

::kyaa::ကျါ
::khyaa::ချါ
::gyaa::ဂျါ
::ghyaa::ဃျါ
::ngyaa::ငျါ
::cyaa::စျါ
::chyaa::ဆျါ
::jyaa::ဇျါ
::jhyaa::ဈျါ
::nyyaa::ဉျါ
::Nyyaa::ညျါ
::Tyaa::ဋျါ
::Thyaa::ဌျါ
::Dyaa::ဍျါ
::Dhyaa::ဎျါ
::Nyaa::ဏျါ
::tyaa::တျါ
::thyaa::ထျါ
::dyaa::ဒျါ
::dhyaa::ဓျါ
::nyaa::နျါ
::pyaa::ပျါ
::phyaa::ဖျါ
::byaa::ဗျါ
::bhyaa::ဘျါ
::myaa::မျါ
::yyaa::ယျါ
::ryaa::ရျါ
::lyaa::လျါ
::Lyaa::ဠျါ
::wyaa::ဝျါ
::hyaa::ဟျါ
::syaa::သျါ
::Syaa::ဿျါ

::kyar::ကျာ
::khyar::ချာ
::gyar::ဂျာ
::ghyar::ဃျာ
::ngyar::ငျာ
::cyar::စျာ
::chyar::ဆျာ
::jyar::ဇျာ
::jhyar::ဈျာ
::nyyar::ဉျာ
::Nyyar::ညျာ
::Tyar::ဋျာ
::Thyar::ဌျာ
::Dyar::ဍျာ
::Dhyar::ဎျာ
::Nyar::ဏျာ
::tyar::တျာ
::thyar::ထျာ
::dyar::ဒျာ
::dhyar::ဓျာ
::nyar::နျာ
::pyar::ပျာ
::phyar::ဖျာ
::byar::ဗျာ
::bhyar::ဘျာ
::myar::မျာ
::yyar::ယျာ
::ryar::ရျာ
::lyar::လျာ
::Lyar::ဠျာ
::wyar::ဝျာ
::hyar::ဟျာ
::syar::သျာ
::Syar::ဿျာ

::kyi::ကျိ
::khyi::ချိ
::gyi::ဂျိ
::ghyi::ဃျိ
::ngyi::ငျိ
::cyi::စျိ
::chyi::ဆျိ
::jyi::ဇျိ
::jhyi::ဈျိ
::nyyi::ဉျိ
::Nyyi::ညျိ
::Tyi::ဋျိ
::Thyi::ဌျိ
::Dyi::ဍျိ
::Dhyi::ဎျိ
::Nyi::ဏျိ
::tyi::တျိ
::thyi::ထျိ
::dyi::ဒျိ
::dhyi::ဓျိ
::nyi::နျိ
::pyi::ပျိ
::phyi::ဖျိ
::byi::ဗျိ
::bhyi::ဘျိ
::myi::မျိ
::yyi::ယျိ
::ryi::ရျိ
::lyi::လျိ
::Lyi::ဠျိ
::wyi::ဝျိ
::hyi::ဟျိ
::syi::သျိ
::Syi::ဿျိ

::kyui::ကျို
::khyui::ချို
::gyui::ဂျို
::ghyui::ဃျို
::ngyui::ငျို
::cyui::စျို
::chyui::ဆျို
::jyui::ဇျို
::jhyui::ဈျို
::nyyui::ဉျို
::Nyyui::ညျို
::Tyui::ဋျို
::Thyui::ဌျို
::Dyui::ဍျို
::Dhyui::ဎျို
::Nyui::ဏျို
::tyui::တျို
::thyui::ထျို
::dyui::ဒျို
::dhyui::ဓျို
::nyui::နျို
::pyui::ပျို
::phyui::ဖျို
::byui::ဗျို
::bhyui::ဘျို
::myui::မျို
::yyui::ယျို
::ryui::ရျို
::lyui::လျို
::Lyui::ဠျို
::wyui::ဝျို
::hyui::ဟျို
::syui::သျို
::Syui::ဿျို

::kyii::ကျီ
::khyii::ချီ
::gyii::ဂျီ
::ghyii::ဃျီ
::ngyii::ငျီ
::cyii::စျီ
::chyii::ဆျီ
::jyii::ဇျီ
::jhyii::ဈျီ
::nyyii::ဉျီ
::Nyyii::ညျီ
::Tyii::ဋျီ
::Thyii::ဌျီ
::Dyii::ဍျီ
::Dhyii::ဎျီ
::Nyii::ဏျီ
::tyii::တျီ
::thyii::ထျီ
::dyii::ဒျီ
::dhyii::ဓျီ
::nyii::နျီ
::pyii::ပျီ
::phyii::ဖျီ
::byii::ဗျီ
::bhyii::ဘျီ
::myii::မျီ
::yyii::ယျီ
::ryii::ရျီ
::lyii::လျီ
::Lyii::ဠျီ
::wyii::ဝျီ
::hyii::ဟျီ
::syii::သျီ
::Syii::ဿျီ

::kyu::ကျု
::khyu::ချု
::gyu::ဂျု
::ghyu::ဃျု
::ngyu::ငျု
::cyu::စျု
::chyu::ဆျု
::jyu::ဇျု
::jhyu::ဈျု
::nyyu::ဉျု
::Nyyu::ညျု
::Tyu::ဋျု
::Thyu::ဌျု
::Dyu::ဍျု
::Dhyu::ဎျု
::Nyu::ဏျု
::tyu::တျု
::thyu::ထျု
::dyu::ဒျု
::dhyu::ဓျု
::nyu::နျု
::pyu::ပျု
::phyu::ဖျု
::byu::ဗျု
::bhyu::ဘျု
::myu::မျု
::yyu::ယျု
::ryu::ရျု
::lyu::လျု
::Lyu::ဠျု
::wyu::ဝျု
::hyu::ဟျု
::syu::သျု
::Syu::ဿျု

::kyuu::ကျူ
::khyuu::ချူ
::gyuu::ဂျူ
::ghyuu::ဃျူ
::ngyuu::ငျူ
::cyuu::စျူ
::chyuu::ဆျူ
::jyuu::ဇျူ
::jhyuu::ဈျူ
::nyyuu::ဉျူ
::Nyyuu::ညျူ
::Tyuu::ဋျူ
::Thyuu::ဌျူ
::Dyuu::ဍျူ
::Dhyuu::ဎျူ
::Nyuu::ဏျူ
::tyuu::တျူ
::thyuu::ထျူ
::dyuu::ဒျူ
::dhyuu::ဓျူ
::nyuu::နျူ
::pyuu::ပျူ
::phyuu::ဖျူ
::byuu::ဗျူ
::bhyuu::ဘျူ
::myuu::မျူ
::yyuu::ယျူ
::ryuu::ရျူ
::lyuu::လျူ
::Lyuu::ဠျူ
::wyuu::ဝျူ
::hyuu::ဟျူ
::syuu::သျူ
::Syuu::ဿျူ

::kye::ကျေ
::khye::ချေ
::gye::ဂျေ
::ghye::ဃျေ
::ngye::ငျေ
::cye::စျေ
::chye::ဆျေ
::jye::ဇျေ
::jhye::ဈျေ
::nyye::ဉျေ
::Nyye::ညျေ
::Tye::ဋျေ
::Thye::ဌျေ
::Dye::ဍျေ
::Dhye::ဎျေ
::Nye::ဏျေ
::tye::တျေ
::thye::ထျေ
::dye::ဒျေ
::dhye::ဓျေ
::nye::နျေ
::pye::ပျေ
::phye::ဖျေ
::bye::ဗျေ
::bhye::ဘျေ
::mye::မျေ
::yye::ယျေ
::rye::ရျေ
::lye::လျေ
::Lye::ဠျေ
::wye::ဝျေ
::hye::ဟျေ
::sye::သျေ
::Sye::ဿျေ

::kyau::ကျါ်
::khyau::ချါ်
::gyau::ဂျါ်
::ghyau::ဃျါ်
::ngyau::ငျါ်
::cyau::စျါ်
::chyau::ဆျါ်
::jyau::ဇျါ်
::jhyau::ဈျါ်
::nyyau::ဉျါ်
::Nyyau::ညျါ်
::Tyau::ဋျါ်
::Thyau::ဌျါ်
::Dyau::ဍျါ်
::Dhyau::ဎျါ်
::Nyau::ဏျါ်
::tyau::တျါ်
::thyau::ထျါ်
::dyau::ဒျါ်
::dhyau::ဓျါ်
::nyau::နျါ်
::pyau::ပျါ်
::phyau::ဖျါ်
::byau::ဗျါ်
::bhyau::ဘျါ်
::myau::မျါ်
::yyau::ယျါ်
::ryau::ရျါ်
::lyau::လျါ်
::Lyau::ဠျါ်
::wyau::ဝျါ်
::hyau::ဟျါ်
::syau::သျါ်
::Syau::ဿျါ်

::kyaw::ကျော
::khyaw::ချော
::gyaw::ဂျော
::ghyaw::ဃျော
::ngyaw::ငျော
::cyaw::စျော
::chyaw::ဆျော
::jyaw::ဇျော
::jhyaw::ဈျော
::nyyaw::ဉျော
::Nyyaw::ညျော
::Tyaw::ဋျော
::Thyaw::ဌျော
::Dyaw::ဍျော
::Dhyaw::ဎျော
::Nyaw::ဏျော
::tyaw::တျော
::thyaw::ထျော
::dyaw::ဒျော
::dhyaw::ဓျော
::nyaw::နျော
::pyaw::ပျော
::phyaw::ဖျော
::byaw::ဗျော
::bhyaw::ဘျော
::myaw::မျော
::yyaw::ယျော
::ryaw::ရျော
::lyaw::လျော
::Lyaw::ဠျော
::wyaw::ဝျော
::hyaw::ဟျော
::syaw::သျော
::Syaw::ဿျော

::kyaww::ကျော်
::khyaww::ချော်
::gyaww::ဂျော်
::ghyaww::ဃျော်
::ngyaww::ငျော်
::cyaww::စျော်
::chyaww::ဆျော်
::jyaww::ဇျော်
::jhyaww::ဈျော်
::nyyaww::ဉျော်
::Nyyaww::ညျော်
::Tyaww::ဋျော်
::Thyaww::ဌျော်
::Dyaww::ဍျော်
::Dhyaww::ဎျော်
::Nyaww::ဏျော်
::tyaww::တျော်
::thyaww::ထျော်
::dyaww::ဒျော်
::dhyaww::ဓျော်
::nyaww::နျော်
::pyaww::ပျော်
::phyaww::ဖျော်
::byaww::ဗျော်
::bhyaww::ဘျော်
::myaww::မျော်
::yyaww::ယျော်
::ryaww::ရျော်
::lyaww::လျော်
::Lyaww::ဠျော်
::wyaww::ဝျော်
::hyaww::ဟျော်
::syaww::သျော်
::Syaww::ဿျော်

::kyai::ကျဲ
::khyai::ချဲ
::gyai::ဂျဲ
::ghyai::ဃျဲ
::ngyai::ငျဲ
::cyai::စျဲ
::chyai::ဆျဲ
::jyai::ဇျဲ
::jhyai::ဈျဲ
::nyyai::ဉျဲ
::Nyyai::ညျဲ
::Tyai::ဋျဲ
::Thyai::ဌျဲ
::Dyai::ဍျဲ
::Dhyai::ဎျဲ
::Nyai::ဏျဲ
::tyai::တျဲ
::thyai::ထျဲ
::dyai::ဒျဲ
::dhyai::ဓျဲ
::nyai::နျဲ
::pyai::ပျဲ
::phyai::ဖျဲ
::byai::ဗျဲ
::bhyai::ဘျဲ
::myai::မျဲ
::yyai::ယျဲ
::ryai::ရျဲ
::lyai::လျဲ
::Lyai::ဠျဲ
::wyai::ဝျဲ
::hyai::ဟျဲ
::syai::သျဲ
::Syai::ဿျဲ

::kra::ကြ
::khra::ခြ
::gra::ဂြ
::ghra::ဃြ
::ngra::ငြ
::cra::စြ
::chra::ဆြ
::jra::ဇြ
::jhra::ဈြ
::nyra::ဉြ
::Nyra::ညြ
::Tra::ဋြ
::Thra::ဌြ
::Dra::ဍြ
::Dhra::ဎြ
::Nra::ဏြ
::tra::တြ
::thra::ထြ
::dra::ဒြ
::dhra::ဓြ
::nra::နြ
::pra::ပြ
::phra::ဖြ
::bra::ဗြ
::bhra::ဘြ
::mra::မြ
::yra::ယြ
::rra::ရြ
::lra::လြ
::Lra::ဠြ
::wra::ဝြ
::hra::ဟြ
::sra::သြ
::Sra::ဿြ

::kraa::ကြါ
::khraa::ခြါ
::graa::ဂြါ
::ghraa::ဃြါ
::ngraa::ငြါ
::craa::စြါ
::chraa::ဆြါ
::jraa::ဇြါ
::jhraa::ဈြါ
::nyraa::ဉြါ
::Nyraa::ညြါ
::Traa::ဋြါ
::Thraa::ဌြါ
::Draa::ဍြါ
::Dhraa::ဎြါ
::Nraa::ဏြါ
::traa::တြါ
::thraa::ထြါ
::draa::ဒြါ
::dhraa::ဓြါ
::nraa::နြါ
::praa::ပြါ
::phraa::ဖြါ
::braa::ဗြါ
::bhraa::ဘြါ
::mraa::မြါ
::yraa::ယြါ
::rraa::ရြါ
::lraa::လြါ
::Lraa::ဠြါ
::wraa::ဝြါ
::hraa::ဟြါ
::sraa::သြါ
::Sraa::ဿြါ

::krar::ကြော
::khrar::ခြော
::grar::ဂြော
::ghrar::ဃြော
::ngrar::ငြော
::crar::စြော
::chrar::ဆြော
::jrar::ဇြော
::jhrar::ဈြော
::nyrar::ဉြော
::Nyrar::ညြော
::Trar::ဋြော
::Thrar::ဌြော
::Drar::ဍြော
::Dhrar::ဎြော
::Nrar::ဏြော
::trar::တြော
::thrar::ထြော
::drar::ဒြော
::dhrar::ဓြော
::nrar::နြော
::prar::ပြော
::phrar::ဖြော
::brar::ဗြော
::bhrar::ဘြော
::mrar::မြော
::yrar::ယြော
::rrar::ရြော
::lrar::လြော
::Lrar::ဠြော
::wrar::ဝြော
::hrar::ဟြော
::srar::သြော
::Srar::ဿြော

::kri::ကြိ
::khri::ခြိ
::gri::ဂြိ
::ghri::ဃြိ
::ngri::ငြိ
::cri::စြိ
::chri::ဆြိ
::jri::ဇြိ
::jhri::ဈြိ
::nyri::ဉြိ
::Nyri::ညြိ
::Tri::ဋြိ
::Thri::ဌြိ
::Dri::ဍြိ
::Dhri::ဎြိ
::Nri::ဏြိ
::tri::တြိ
::thri::ထြိ
::dri::ဒြိ
::dhri::ဓြိ
::nri::နြိ
::pri::ပြိ
::phri::ဖြိ
::bri::ဗြိ
::bhri::ဘြိ
::mri::မြိ
::yri::ယြိ
::rri::ရြိ
::lri::လြိ
::Lri::ဠြိ
::wri::ဝြိ
::hri::ဟြိ
::sri::သြိ
::Sri::ဿြိ

::krui::ကြို
::khrui::ခြို
::grui::ဂြို
::ghrui::ဃြို
::ngrui::ငြို
::crui::စြို
::chrui::ဆြို
::jrui::ဇြို
::jhrui::ဈြို
::nyrui::ဉြို
::Nyrui::ညြို
::Trui::ဋြို
::Thrui::ဌြို
::Drui::ဍြို
::Dhrui::ဎြို
::Nrui::ဏြို
::trui::တြို
::thrui::ထြို
::drui::ဒြို
::dhrui::ဓြို
::nrui::နြို
::prui::ပြို
::phrui::ဖြို
::brui::ဗြို
::bhrui::ဘြို
::mrui::မြို
::yrui::ယြို
::rrui::ရြို
::lrui::လြို
::Lrui::ဠြို
::wrui::ဝြို
::hrui::ဟြို
::srui::သြို
::Srui::ဿြို

::krii::ကြီ
::khrii::ခြီ
::grii::ဂြီ
::ghrii::ဃြီ
::ngrii::ငြီ
::crii::စြီ
::chrii::ဆြီ
::jrii::ဇြီ
::jhrii::ဈြီ
::nyrii::ဉြီ
::Nyrii::ညြီ
::Trii::ဋြီ
::Thrii::ဌြီ
::Drii::ဍြီ
::Dhrii::ဎြီ
::Nrii::ဏြီ
::trii::တြီ
::thrii::ထြီ
::drii::ဒြီ
::dhrii::ဓြီ
::nrii::နြီ
::prii::ပြီ
::phrii::ဖြီ
::brii::ဗြီ
::bhrii::ဘြီ
::mrii::မြီ
::yrii::ယြီ
::rrii::ရြီ
::lrii::လြီ
::Lrii::ဠြီ
::wrii::ဝြီ
::hrii::ဟြီ
::srii::သြီ
::Srii::ဿြီ

::kru::ကြု
::khru::ခြု
::gru::ဂြု
::ghru::ဃြု
::ngru::ငြု
::cru::စြု
::chru::ဆြု
::jru::ဇြု
::jhru::ဈြု
::nyru::ဉြု
::Nyru::ညြု
::Tru::ဋြု
::Thru::ဌြု
::Dru::ဍြု
::Dhru::ဎြု
::Nru::ဏြု
::tru::တြု
::thru::ထြု
::dru::ဒြု
::dhru::ဓြု
::nru::နြု
::pru::ပြု
::phru::ဖြု
::bru::ဗြု
::bhru::ဘြု
::mru::မြု
::yru::ယြု
::rru::ရြု
::lru::လြု
::Lru::ဠြု
::wru::ဝြု
::hru::ဟြု
::sru::သြု
::Sru::ဿြု

::kruu::ကြူ
::khruu::ခြူ
::gruu::ဂြူ
::ghruu::ဃြူ
::ngruu::ငြူ
::cruu::စြူ
::chruu::ဆြူ
::jruu::ဇြူ
::jhruu::ဈြူ
::nyruu::ဉြူ
::Nyruu::ညြူ
::Truu::ဋြူ
::Thruu::ဌြူ
::Druu::ဍြူ
::Dhruu::ဎြူ
::Nruu::ဏြူ
::truu::တြူ
::thruu::ထြူ
::druu::ဒြူ
::dhruu::ဓြူ
::nruu::နြူ
::pruu::ပြူ
::phruu::ဖြူ
::bruu::ဗြူ
::bhruu::ဘြူ
::mruu::မြူ
::yruu::ယြူ
::rruu::ရြူ
::lruu::လြူ
::Lruu::ဠြူ
::wruu::ဝြူ
::hruu::ဟြူ
::sruu::သြူ
::Sruu::ဿြူ

::kre::ကြေ
::khre::ခြေ
::gre::ဂြေ
::ghre::ဃြေ
::ngre::ငြေ
::cre::စြေ
::chre::ဆြေ
::jre::ဇြေ
::jhre::ဈြေ
::nyre::ဉြေ
::Nyre::ညြေ
::Tre::ဋြေ
::Thre::ဌြေ
::Dre::ဍြေ
::Dhre::ဎြေ
::Nre::ဏြေ
::tre::တြေ
::thre::ထြေ
::dre::ဒြေ
::dhre::ဓြေ
::nre::နြေ
::pre::ပြေ
::phre::ဖြေ
::bre::ဗြေ
::bhre::ဘြေ
::mre::မြေ
::yre::ယြေ
::rre::ရြေ
::lre::လြေ
::Lre::ဠြေ
::wre::ဝြေ
::hre::ဟြေ
::sre::သြေ
::Sre::ဿြေ

::krau::ကြေါ်
::khrau::ခြေါ်
::grau::ဂြေါ်
::ghrau::ဃြေါ်
::ngrau::ငြေါ်
::crau::စြေါ်
::chrau::ဆြေါ်
::jrau::ဇြေါ်
::jhrau::ဈြေါ်
::nyrau::ဉြေါ်
::Nyrau::ညြေါ်
::Trau::ဋြေါ်
::Thrau::ဌြေါ်
::Drau::ဍြေါ်
::Dhrau::ဎြေါ်
::Nrau::ဏြေါ်
::trau::တြေါ်
::thrau::ထြေါ်
::drau::ဒြေါ်
::dhrau::ဓြေါ်
::nrau::နြေါ်
::prau::ပြေါ်
::phrau::ဖြေါ်
::brau::ဗြေါ်
::bhrau::ဘြေါ်
::mrau::မြေါ်
::yrau::ယြေါ်
::rrau::ရြေါ်
::lrau::လြေါ်
::Lrau::ဠြေါ်
::wrau::ဝြေါ်
::hrau::ဟြေါ်
::srau::သြေါ်
::Srau::ဿြေါ်

::kraw::ကြော
::khraw::ခြော
::graw::ဂြော
::ghraw::ဃြော
::ngraw::ငြော
::craw::စြော
::chraw::ဆြော
::jraw::ဇြော
::jhraw::ဈြော
::nyraw::ဉြော
::Nyraw::ညြော
::Traw::ဋြော
::Thraw::ဌြော
::Draw::ဍြော
::Dhraw::ဎြော
::Nraw::ဏြော
::traw::တြော
::thraw::ထြော
::draw::ဒြော
::dhraw::ဓြော
::nraw::နြော
::praw::ပြော
::phraw::ဖြော
::braw::ဗြော
::bhraw::ဘြော
::mraw::မြော
::yraw::ယြော
::rraw::ရြော
::lraw::လြော
::Lraw::ဠြော
::wraw::ဝြော
::hraw::ဟြော
::sraw::သြော
::Sraw::ဿြော

::kraww::ကြော်
::khraww::ခြော်
::graww::ဂြော်
::ghraww::ဃြော်
::ngraww::ငြော်
::craww::စြော်
::chraww::ဆြော်
::jraww::ဇြော်
::jhraww::ဈြော်
::nyraww::ဉြော်
::Nyraww::ညြော်
::Traww::ဋြော်
::Thraww::ဌြော်
::Draww::ဍြော်
::Dhraww::ဎြော်
::Nraww::ဏြော်
::traww::တြော်
::thraww::ထြော်
::draww::ဒြော်
::dhraww::ဓြော်
::nraww::နြော်
::praww::ပြော်
::phraww::ဖြော်
::braww::ဗြော်
::bhraww::ဘြော်
::mraww::မြော်
::yraww::ယြော်
::rraww::ရြော်
::lraww::လြော်
::Lraww::ဠြော်
::wraww::ဝြော်
::hraww::ဟြော်
::sraww::သြော်
::Sraww::ဿြော်

::krai::ကြဲ
::khrai::ခြဲ
::grai::ဂြဲ
::ghrai::ဃြဲ
::ngrai::ငြဲ
::crai::စြဲ
::chrai::ဆြဲ
::jrai::ဇြဲ
::jhrai::ဈြဲ
::nyrai::ဉြဲ
::Nyrai::ညြဲ
::Trai::ဋြဲ
::Thrai::ဌြဲ
::Drai::ဍြဲ
::Dhrai::ဎြဲ
::Nrai::ဏြဲ
::trai::တြဲ
::thrai::ထြဲ
::drai::ဒြဲ
::dhrai::ဓြဲ
::nrai::နြဲ
::prai::ပြဲ
::phrai::ဖြဲ
::brai::ဗြဲ
::bhrai::ဘြဲ
::mrai::မြဲ
::yrai::ယြဲ
::rrai::ရြဲ
::lrai::လြဲ
::Lrai::ဠြဲ
::wrai::ဝြဲ
::hrai::ဟြဲ
::srai::သြဲ
::Srai::ဿြဲ

::kwa::ကွ
::khwa::ခွ
::gwa::ဂွ
::ghwa::ဃွ
::ngwa::ငွ
::cwa::စွ
::chwa::ဆွ
::jwa::ဇွ
::jhwa::ဈွ
::nywa::ဉွ
::Nywa::ညွ
::Twa::ဋွ
::Thwa::ဌွ
::Dwa::ဍွ
::Dhwa::ဎွ
::Nwa::ဏွ
::twa::တွ
::thwa::ထွ
::dwa::ဒွ
::dhwa::ဓွ
::nwa::နွ
::pwa::ပွ
::phwa::ဖွ
::bwa::ဗွ
::bhwa::ဘွ
::mwa::မွ
::ywa::ယွ
::rwa::ရွ
::lwa::လွ
::Lwa::ဠွ
::wwa::ဝွ
::hwa::ဟွ
::swa::သွ
::Swa::ဿွ

::kwaa::ကွါ
::khwaa::ခွါ
::gwaa::ဂွါ
::ghwaa::ဃွါ
::ngwaa::ငွါ
::cwaa::စွါ
::chwaa::ဆွါ
::jwaa::ဇွါ
::jhwaa::ဈွါ
::nywaa::ဉွါ
::Nywaa::ညွါ
::Twaa::ဋွါ
::Thwaa::ဌွါ
::Dwaa::ဍွါ
::Dhwaa::ဎွါ
::Nwaa::ဏွါ
::twaa::တွါ
::thwaa::ထွါ
::dwaa::ဒွါ
::dhwaa::ဓွါ
::nwaa::နွါ
::pwaa::ပွါ
::phwaa::ဖွါ
::bwaa::ဗွါ
::bhwaa::ဘွါ
::mwaa::မွါ
::ywaa::ယွါ
::rwaa::ရွါ
::lwaa::လွါ
::Lwaa::ဠွါ
::wwaa::ဝွါ
::hwaa::ဟွါ
::swaa::သွါ
::Swaa::ဿွါ

::kwar::ကွော
::khwar::ခွော
::gwar::ဂွော
::ghwar::ဃွော
::ngwar::ငွော
::cwar::စွော
::chwar::ဆွော
::jwar::ဇွော
::jhwar::ဈွော
::nywar::ဉွော
::Nywar::ညွော
::Twar::ဋွော
::Thwar::ဌွော
::Dwar::ဍွော
::Dhwar::ဎွော
::Nwar::ဏွော
::twar::တွော
::thwar::ထွော
::dwar::ဒွော
::dhwar::ဓွော
::nwar::နွော
::pwar::ပွော
::phwar::ဖွော
::bwar::ဗွော
::bhwar::ဘွော
::mwar::မွော
::ywar::ယွော
::rwar::ရွော
::lwar::လွော
::Lwar::ဠွော
::wwar::ဝွော
::hwar::ဟွော
::swar::သွော
::Swar::ဿွော

::kwi::ကွိ
::khwi::ခွိ
::gwi::ဂွိ
::ghwi::ဃွိ
::ngwi::ငွိ
::cwi::စွိ
::chwi::ဆွိ
::jwi::ဇွိ
::jhwi::ဈွိ
::nywi::ဉွိ
::Nywi::ညွိ
::Twi::ဋွိ
::Thwi::ဌွိ
::Dwi::ဍွိ
::Dhwi::ဎွိ
::Nwi::ဏွိ
::twi::တွိ
::thwi::ထွိ
::dwi::ဒွိ
::dhwi::ဓွိ
::nwi::နွိ
::pwi::ပွိ
::phwi::ဖွိ
::bwi::ဗွိ
::bhwi::ဘွိ
::mwi::မွိ
::ywi::ယွိ
::rwi::ရွိ
::lwi::လွိ
::Lwi::ဠွိ
::wwi::ဝွိ
::hwi::ဟွိ
::swi::သွိ
::Swi::ဿွိ

::kwui::ကွို
::khwui::ခွို
::gwui::ဂွို
::ghwui::ဃွို
::ngwui::ငွို
::cwui::စွို
::chwui::ဆွို
::jwui::ဇွို
::jhwui::ဈွို
::nywui::ဉွို
::Nywui::ညွို
::Twui::ဋွို
::Thwui::ဌွို
::Dwui::ဍွို
::Dhwui::ဎွို
::Nwui::ဏွို
::twui::တွို
::thwui::ထွို
::dwui::ဒွို
::dhwui::ဓွို
::nwui::နွို
::pwui::ပွို
::phwui::ဖွို
::bwui::ဗွို
::bhwui::ဘွို
::mwui::မွို
::ywui::ယွို
::rwui::ရွို
::lwui::လွို
::Lwui::ဠွို
::wwui::ဝွို
::hwui::ဟွို
::swui::သွို
::Swui::ဿွို

::kwii::ကွီ
::khwii::ခွီ
::gwii::ဂွီ
::ghwii::ဃွီ
::ngwii::ငွီ
::cwii::စွီ
::chwii::ဆွီ
::jwii::ဇွီ
::jhwii::ဈွီ
::nywii::ဉွီ
::Nywii::ညွီ
::Twii::ဋွီ
::Thwii::ဌွီ
::Dwii::ဍွီ
::Dhwii::ဎွီ
::Nwii::ဏွီ
::twii::တွီ
::thwii::ထွီ
::dwii::ဒွီ
::dhwii::ဓွီ
::nwii::နွီ
::pwii::ပွီ
::phwii::ဖွီ
::bwii::ဗွီ
::bhwii::ဘွီ
::mwii::မွီ
::ywii::ယွီ
::rwii::ရွီ
::lwii::လွီ
::Lwii::ဠွီ
::wwii::ဝွီ
::hwii::ဟွီ
::swii::သွီ
::Swii::ဿွီ

::kwu::ကွု
::khwu::ခွု
::gwu::ဂွု
::ghwu::ဃွု
::ngwu::ငွု
::cwu::စွု
::chwu::ဆွု
::jwu::ဇွု
::jhwu::ဈွု
::nywu::ဉွု
::Nywu::ညွု
::Twu::ဋွု
::Thwu::ဌွု
::Dwu::ဍွု
::Dhwu::ဎွု
::Nwu::ဏွု
::twu::တွု
::thwu::ထွု
::dwu::ဒွု
::dhwu::ဓွု
::nwu::နွု
::pwu::ပွု
::phwu::ဖွု
::bwu::ဗွု
::bhwu::ဘွု
::mwu::မွု
::ywu::ယွု
::rwu::ရွု
::lwu::လွု
::Lwu::ဠွု
::wwu::ဝွု
::hwu::ဟွု
::swu::သွု
::Swu::ဿွု

::kwuu::ကွူ
::khwuu::ခွူ
::gwuu::ဂွူ
::ghwuu::ဃွူ
::ngwuu::ငွူ
::cwuu::စွူ
::chwuu::ဆွူ
::jwuu::ဇွူ
::jhwuu::ဈွူ
::nywuu::ဉွူ
::Nywuu::ညွူ
::Twuu::ဋွူ
::Thwuu::ဌွူ
::Dwuu::ဍွူ
::Dhwuu::ဎွူ
::Nwuu::ဏွူ
::twuu::တွူ
::thwuu::ထွူ
::dwuu::ဒွူ
::dhwuu::ဓွူ
::nwuu::နွူ
::pwuu::ပွူ
::phwuu::ဖွူ
::bwuu::ဗွူ
::bhwuu::ဘွူ
::mwuu::မွူ
::ywuu::ယွူ
::rwuu::ရွူ
::lwuu::လွူ
::Lwuu::ဠွူ
::wwuu::ဝွူ
::hwuu::ဟွူ
::swuu::သွူ
::Swuu::ဿွူ

::kwe::ကွေ
::khwe::ခွေ
::gwe::ဂွေ
::ghwe::ဃွေ
::ngwe::ငွေ
::cwe::စွေ
::chwe::ဆွေ
::jwe::ဇွေ
::jhwe::ဈွေ
::nywe::ဉွေ
::Nywe::ညွေ
::Twe::ဋွေ
::Thwe::ဌွေ
::Dwe::ဍွေ
::Dhwe::ဎွေ
::Nwe::ဏွေ
::twe::တွေ
::thwe::ထွေ
::dwe::ဒွေ
::dhwe::ဓွေ
::nwe::နွေ
::pwe::ပွေ
::phwe::ဖွေ
::bwe::ဗွေ
::bhwe::ဘွေ
::mwe::မွေ
::ywe::ယွေ
::rwe::ရွေ
::lwe::လွေ
::Lwe::ဠွေ
::wwe::ဝွေ
::hwe::ဟွေ
::swe::သွေ
::Swe::ဿွေ

::kwau::ကွါ်
::khwau::ခွါ်
::gwau::ဂွါ်
::ghwau::ဃွါ်
::ngwau::ငွါ်
::cwau::စွါ်
::chwau::ဆွါ်
::jwau::ဇွါ်
::jhwau::ဈွါ်
::nywau::ဉွါ်
::Nywau::ညွါ်
::Twau::ဋွါ်
::Thwau::ဌွါ်
::Dwau::ဍွါ်
::Dhwau::ဎွါ်
::Nwau::ဏွါ်
::twau::တွါ်
::thwau::ထွါ်
::dwau::ဒွါ်
::dhwau::ဓွါ်
::nwau::နွါ်
::pwau::ပွါ်
::phwau::ဖွါ်
::bwau::ဗွါ်
::bhwau::ဘွါ်
::mwau::မွါ်
::ywau::ယွါ်
::rwau::ရွါ်
::lwau::လွါ်
::Lwau::ဠွါ်
::wwau::ဝွါ်
::hwau::ဟွါ်
::swau::သွါ်
::Swau::ဿွါ်

::kwaw::ကွော
::khwaw::ခွော
::gwaw::ဂွော
::ghwaw::ဃွော
::ngwaw::ငွော
::cwaw::စွော
::chwaw::ဆွော
::jwaw::ဇွော
::jhwaw::ဈွော
::nywaw::ဉွော
::Nywaw::ညွော
::Twaw::ဋွော
::Thwaw::ဌွော
::Dwaw::ဍွော
::Dhwaw::ဎွော
::Nwaw::ဏွော
::twaw::တွော
::thwaw::ထွော
::dwaw::ဒွော
::dhwaw::ဓွော
::nwaw::နွော
::pwaw::ပွော
::phwaw::ဖွော
::bwaw::ဗွော
::bhwaw::ဘွော
::mwaw::မွော
::ywaw::ယွော
::rwaw::ရွော
::lwaw::လွော
::Lwaw::ဠွော
::wwaw::ဝွော
::hwaw::ဟွော
::swaw::သွော
::Swaw::ဿွော

::kwaww::ကွော်
::khwaww::ခွော်
::gwaww::ဂွော်
::ghwaww::ဃွော်
::ngwaww::ငွော်
::cwaww::စွော်
::chwaww::ဆွော်
::jwaww::ဇွော်
::jhwaww::ဈွော်
::nywaww::ဉွော်
::Nywaww::ညွော်
::Twaww::ဋွော်
::Thwaww::ဌွော်
::Dwaww::ဍွော်
::Dhwaww::ဎွော်
::Nwaww::ဏွော်
::twaww::တွော်
::thwaww::ထွော်
::dwaww::ဒွော်
::dhwaww::ဓွော်
::nwaww::နွော်
::pwaww::ပွော်
::phwaww::ဖွော်
::bwaww::ဗွော်
::bhwaww::ဘွော်
::mwaww::မွော်
::ywaww::ယွော်
::rwaww::ရွော်
::lwaww::လွော်
::Lwaww::ဠွော်
::wwaww::ဝွော်
::hwaww::ဟွော်
::swaww::သွော်
::Swaww::ဿွော်

::kwai::ကွဲ
::khwai::ခွဲ
::gwai::ဂွဲ
::ghwai::ဃွဲ
::ngwai::ငွဲ
::cwai::စွဲ
::chwai::ဆွဲ
::jwai::ဇွဲ
::jhwai::ဈွဲ
::nywai::ဉွဲ
::Nywai::ညွဲ
::Twai::ဋွဲ
::Thwai::ဌွဲ
::Dwai::ဍွဲ
::Dhwai::ဎွဲ
::Nwai::ဏွဲ
::twai::တွဲ
::thwai::ထွဲ
::dwai::ဒွဲ
::dhwai::ဓွဲ
::nwai::နွဲ
::pwai::ပွဲ
::phwai::ဖွဲ
::bwai::ဗွဲ
::bhwai::ဘွဲ
::mwai::မွဲ
::ywai::ယွဲ
::rwai::ရွဲ
::lwai::လွဲ
::Lwai::ဠွဲ
::wwai::ဝွဲ
::hwai::ဟွဲ
::swai::သွဲ
::Swai::ဿွဲ

::hkwa::ကွှ
::hkhwa::ခွှ
::hgwa::ဂွှ
::hghwa::ဃွှ
::hngwa::ငွှ
::hcwa::စွှ
::hchwa::ဆွှ
::hjwa::ဇွှ
::hjhwa::ဈွှ
::hnywa::ဉွှ
::hNywa::ညွှ
::hTwa::ဋွှ
::hThwa::ဌွှ
::hDwa::ဍွှ
::hDhwa::ဎွှ
::hNwa::ဏွှ
::htwa::တွှ
::hthwa::ထွှ
::hdwa::ဒွှ
::hdhwa::ဓွှ
::hnwa::နွှ
::hpwa::ပွှ
::hphwa::ဖွှ
::hbwa::ဗွှ
::hbhwa::ဘွှ
::hmwa::မွှ
::hywa::ယွှ
::hrwa::ရွှ
::hlwa::လွှ
::hLwa::ဠွှ
::hwwa::ဝွှ
::hhwa::ဟွှ
::hswa::သွှ
::hSwa::ဿွှ

::hkwaa::ကွှါ
::hkhwaa::ခွှါ
::hgwaa::ဂွှါ
::hghwaa::ဃွှါ
::hngwaa::ငွှါ
::hcwaa::စွှါ
::hchwaa::ဆွှါ
::hjwaa::ဇွှါ
::hjhwaa::ဈွှါ
::hnywaa::ဉွှါ
::hNywaa::ညွှါ
::hTwaa::ဋွှါ
::hThwaa::ဌွှါ
::hDwaa::ဍွှါ
::hDhwaa::ဎွှါ
::hNwaa::ဏွှါ
::htwaa::တွှါ
::hthwaa::ထွှါ
::hdwaa::ဒွှါ
::hdhwaa::ဓွှါ
::hnwaa::နွှါ
::hpwaa::ပွှါ
::hphwaa::ဖွှါ
::hbwaa::ဗွှါ
::hbhwaa::ဘွှါ
::hmwaa::မွှါ
::hywaa::ယွှါ
::hrwaa::ရွှါ
::hlwaa::လွှါ
::hLwaa::ဠွှါ
::hwwaa::ဝွှါ
::hhwaa::ဟွှါ
::hswaa::သွှါ
::hSwaa::ဿွှါ

::hkwar::ကွှော
::hkhwar::ခွှော
::hgwar::ဂွှော
::hghwar::ဃွှော
::hngwar::ငွှော
::hcwar::စွှော
::hchwar::ဆွှော
::hjwar::ဇွှော
::hjhwar::ဈွှော
::hnywar::ဉွှော
::hNywar::ညွှော
::hTwar::ဋွှော
::hThwar::ဌွှော
::hDwar::ဍွှော
::hDhwar::ဎွှော
::hNwar::ဏွှော
::htwar::တွှော
::hthwar::ထွှော
::hdwar::ဒွှော
::hdhwar::ဓွှော
::hnwar::နွှော
::hpwar::ပွှော
::hphwar::ဖွှော
::hbwar::ဗွှော
::hbhwar::ဘွှော
::hmwar::မွှော
::hywar::ယွှော
::hrwar::ရွှော
::hlwar::လွှော
::hLwar::ဠွှော
::hwwar::ဝွှော
::hhwar::ဟွှော
::hswar::သွှော
::hSwar::ဿွှော

::hkwi::ကွှိ
::hkhwi::ခွှိ
::hgwi::ဂွှိ
::hghwi::ဃွှိ
::hngwi::ငွှိ
::hcwi::စွှိ
::hchwi::ဆွှိ
::hjwi::ဇွှိ
::hjhwi::ဈွှိ
::hnywi::ဉွှိ
::hNywi::ညွှိ
::hTwi::ဋွှိ
::hThwi::ဌွှိ
::hDwi::ဍွှိ
::hDhwi::ဎွှိ
::hNwi::ဏွှိ
::htwi::တွှိ
::hthwi::ထွှိ
::hdwi::ဒွှိ
::hdhwi::ဓွှိ
::hnwi::နွှိ
::hpwi::ပွှိ
::hphwi::ဖွှိ
::hbwi::ဗွှိ
::hbhwi::ဘွှိ
::hmwi::မွှိ
::hywi::ယွှိ
::hrwi::ရွှိ
::hlwi::လွှိ
::hLwi::ဠွှိ
::hwwi::ဝွှိ
::hhwi::ဟွှိ
::hswi::သွှိ
::hSwi::ဿွှိ

::hkwui::ကွှို
::hkhwui::ခွှို
::hgwui::ဂွှို
::hghwui::ဃွှို
::hngwui::ငွှို
::hcwui::စွှို
::hchwui::ဆွှို
::hjwui::ဇွှို
::hjhwui::ဈွှို
::hnywui::ဉွှို
::hNywui::ညွှို
::hTwui::ဋွှို
::hThwui::ဌွှို
::hDwui::ဍွှို
::hDhwui::ဎွှို
::hNwui::ဏွှို
::htwui::တွှို
::hthwui::ထွှို
::hdwui::ဒွှို
::hdhwui::ဓွှို
::hnwui::နွှို
::hpwui::ပွှို
::hphwui::ဖွှို
::hbwui::ဗွှို
::hbhwui::ဘွှို
::hmwui::မွှို
::hywui::ယွှို
::hrwui::ရွှို
::hlwui::လွှို
::hLwui::ဠွှို
::hwwui::ဝွှို
::hhwui::ဟွှို
::hswui::သွှို
::hSwui::ဿွှို

::hkwii::ကွှီ
::hkhwii::ခွှီ
::hgwii::ဂွှီ
::hghwii::ဃွှီ
::hngwii::ငွှီ
::hcwii::စွှီ
::hchwii::ဆွှီ
::hjwii::ဇွှီ
::hjhwii::ဈွှီ
::hnywii::ဉွှီ
::hNywii::ညွှီ
::hTwii::ဋွှီ
::hThwii::ဌွှီ
::hDwii::ဍွှီ
::hDhwii::ဎွှီ
::hNwii::ဏွှီ
::htwii::တွှီ
::hthwii::ထွှီ
::hdwii::ဒွှီ
::hdhwii::ဓွှီ
::hnwii::နွှီ
::hpwii::ပွှီ
::hphwii::ဖွှီ
::hbwii::ဗွှီ
::hbhwii::ဘွှီ
::hmwii::မွှီ
::hywii::ယွှီ
::hrwii::ရွှီ
::hlwii::လွှီ
::hLwii::ဠွှီ
::hwwii::ဝွှီ
::hhwii::ဟွှီ
::hswii::သွှီ
::hSwii::ဿွှီ

::hkwu::ကွှု
::hkhwu::ခွှု
::hgwu::ဂွှု
::hghwu::ဃွှု
::hngwu::ငွှု
::hcwu::စွှု
::hchwu::ဆွှု
::hjwu::ဇွှု
::hjhwu::ဈွှု
::hnywu::ဉွှု
::hNywu::ညွှု
::hTwu::ဋွှု
::hThwu::ဌွှု
::hDwu::ဍွှု
::hDhwu::ဎွှု
::hNwu::ဏွှု
::htwu::တွှု
::hthwu::ထွှု
::hdwu::ဒွှု
::hdhwu::ဓွှု
::hnwu::နွှု
::hpwu::ပွှု
::hphwu::ဖွှု
::hbwu::ဗွှု
::hbhwu::ဘွှု
::hmwu::မွှု
::hywu::ယွှု
::hrwu::ရွှု
::hlwu::လွှု
::hLwu::ဠွှု
::hwwu::ဝွှု
::hhwu::ဟွှု
::hswu::သွှု
::hSwu::ဿွှု

::hkwuu::ကွှူ
::hkhwuu::ခွှူ
::hgwuu::ဂွှူ
::hghwuu::ဃွှူ
::hngwuu::ငွှူ
::hcwuu::စွှူ
::hchwuu::ဆွှူ
::hjwuu::ဇွှူ
::hjhwuu::ဈွှူ
::hnywuu::ဉွှူ
::hNywuu::ညွှူ
::hTwuu::ဋွှူ
::hThwuu::ဌွှူ
::hDwuu::ဍွှူ
::hDhwuu::ဎွှူ
::hNwuu::ဏွှူ
::htwuu::တွှူ
::hthwuu::ထွှူ
::hdwuu::ဒွှူ
::hdhwuu::ဓွှူ
::hnwuu::နွှူ
::hpwuu::ပွှူ
::hphwuu::ဖွှူ
::hbwuu::ဗွှူ
::hbhwuu::ဘွှူ
::hmwuu::မွှူ
::hywuu::ယွှူ
::hrwuu::ရွှူ
::hlwuu::လွှူ
::hLwuu::ဠွှူ
::hwwuu::ဝွှူ
::hhwuu::ဟွှူ
::hswuu::သွှူ
::hSwuu::ဿွှူ

::hkwe::ကွှေ
::hkhwe::ခွှေ
::hgwe::ဂွှေ
::hghwe::ဃွှေ
::hngwe::ငွှေ
::hcwe::စွှေ
::hchwe::ဆွှေ
::hjwe::ဇွှေ
::hjhwe::ဈွှေ
::hnywe::ဉွှေ
::hNywe::ညွှေ
::hTwe::ဋွှေ
::hThwe::ဌွှေ
::hDwe::ဍွှေ
::hDhwe::ဎွှေ
::hNwe::ဏွှေ
::htwe::တွှေ
::hthwe::ထွှေ
::hdwe::ဒွှေ
::hdhwe::ဓွှေ
::hnwe::နွှေ
::hpwe::ပွှေ
::hphwe::ဖွှေ
::hbwe::ဗွှေ
::hbhwe::ဘွှေ
::hmwe::မွှေ
::hywe::ယွှေ
::hrwe::ရွှေ
::hlwe::လွှေ
::hLwe::ဠွှေ
::hwwe::ဝွှေ
::hhwe::ဟွှေ
::hswe::သွှေ
::hSwe::ဿွှေ

::hkwau::ကွှါ်
::hkhwau::ခွှါ်
::hgwau::ဂွှါ်
::hghwau::ဃွှါ်
::hngwau::ငွှါ်
::hcwau::စွှါ်
::hchwau::ဆွှါ်
::hjwau::ဇွှါ်
::hjhwau::ဈွှါ်
::hnywau::ဉွှါ်
::hNywau::ညွှါ်
::hTwau::ဋွှါ်
::hThwau::ဌွှါ်
::hDwau::ဍွှါ်
::hDhwau::ဎွှါ်
::hNwau::ဏွှါ်
::htwau::တွှါ်
::hthwau::ထွှါ်
::hdwau::ဒွှါ်
::hdhwau::ဓွှါ်
::hnwau::နွှါ်
::hpwau::ပွှါ်
::hphwau::ဖွှါ်
::hbwau::ဗွှါ်
::hbhwau::ဘွှါ်
::hmwau::မွှါ်
::hywau::ယွှါ်
::hrwau::ရွှါ်
::hlwau::လွှါ်
::hLwau::ဠွှါ်
::hwwau::ဝွှါ်
::hhwau::ဟွှါ်
::hswau::သွှါ်
::hSwau::ဿွှါ်

::hkwaw::ကွှော
::hkhwaw::ခွှော
::hgwaw::ဂွှော
::hghwaw::ဃွှော
::hngwaw::ငွှော
::hcwaw::စွှော
::hchwaw::ဆွှော
::hjwaw::ဇွှော
::hjhwaw::ဈွှော
::hnywaw::ဉွှော
::hNywaw::ညွှော
::hTwaw::ဋွှော
::hThwaw::ဌွှော
::hDwaw::ဍွှော
::hDhwaw::ဎွှော
::hNwaw::ဏွှော
::htwaw::တွှော
::hthwaw::ထွှော
::hdwaw::ဒွှော
::hdhwaw::ဓွှော
::hnwaw::နွှော
::hpwaw::ပွှော
::hphwaw::ဖွှော
::hbwaw::ဗွှော
::hbhwaw::ဘွှော
::hmwaw::မွှော
::hywaw::ယွှော
::hrwaw::ရွှော
::hlwaw::လွှော
::hLwaw::ဠွှော
::hwwaw::ဝွှော
::hhwaw::ဟွှော
::hswaw::သွှော
::hSwaw::ဿွှော

::hkwaww::ကွှော်
::hkhwaww::ခွှော်
::hgwaww::ဂွှော်
::hghwaww::ဃွှော်
::hngwaww::ငွှော်
::hcwaww::စွှော်
::hchwaww::ဆွှော်
::hjwaww::ဇွှော်
::hjhwaww::ဈွှော်
::hnywaww::ဉွှော်
::hNywaww::ညွှော်
::hTwaww::ဋွှော်
::hThwaww::ဌွှော်
::hDwaww::ဍွှော်
::hDhwaww::ဎွှော်
::hNwaww::ဏွှော်
::htwaww::တွှော်
::hthwaww::ထွှော်
::hdwaww::ဒွှော်
::hdhwaww::ဓွှော်
::hnwaww::နွှော်
::hpwaww::ပွှော်
::hphwaww::ဖွှော်
::hbwaww::ဗွှော်
::hbhwaww::ဘွှော်
::hmwaww::မွှော်
::hywaww::ယွှော်
::hrwaww::ရွှော်
::hlwaww::လွှော်
::hLwaww::ဠွှော်
::hwwaww::ဝွှော်
::hhwaww::ဟွှော်
::hswaww::သွှော်
::hSwaww::ဿွှော်

::hkwai::ကွှဲ
::hkhwai::ခွှဲ
::hgwai::ဂွှဲ
::hghwai::ဃွှဲ
::hngwai::ငွှဲ
::hcwai::စွှဲ
::hchwai::ဆွှဲ
::hjwai::ဇွှဲ
::hjhwai::ဈွှဲ
::hnywai::ဉွှဲ
::hNywai::ညွှဲ
::hTwai::ဋွှဲ
::hThwai::ဌွှဲ
::hDwai::ဍွှဲ
::hDhwai::ဎွှဲ
::hNwai::ဏွှဲ
::htwai::တွှဲ
::hthwai::ထွှဲ
::hdwai::ဒွှဲ
::hdhwai::ဓွှဲ
::hnwai::နွှဲ
::hpwai::ပွှဲ
::hphwai::ဖွှဲ
::hbwai::ဗွှဲ
::hbhwai::ဘွှဲ
::hmwai::မွှဲ
::hywai::ယွှဲ
::hrwai::ရွှဲ
::hlwai::လွှဲ
::hLwai::ဠွှဲ
::hwwai::ဝွှဲ
::hhwai::ဟွှဲ
::hswai::သွှဲ
::hSwai::ဿွှဲ

::hka::ကှ
::hkha::ခှ
::hga::ဂှ
::hgha::ဃှ
::hnga::ငှ
::hca::စှ
::hcha::ဆှ
::hja::ဇှ
::hjha::ဈှ
::hnya::ဉှ
::hNya::ညှ
::hTa::ဋှ
::hTha::ဌှ
::hDa::ဍှ
::hDha::ဎှ
::hNa::ဏှ
::hta::တှ
::htha::ထှ
::hda::ဒှ
::hdha::ဓှ
::hna::နှ
::hpa::ပှ
::hpha::ဖှ
::hba::ဗှ
::hbha::ဘှ
::hma::မှ
::hya::ယှ
::hra::ရှ
::hla::လှ
::hLa::ဠှ
::hwa::ဝှ
::hha::ဟှ
::hsa::သှ
::hSa::ဿှ

::hkaa::ကှါ
::hkhaa::ခှါ
::hgaa::ဂှါ
::hghaa::ဃှါ
::hngaa::ငှါ
::hcaa::စှါ
::hchaa::ဆှါ
::hjaa::ဇှါ
::hjhaa::ဈှါ
::hnyaa::ဉှါ
::hNyaa::ညှါ
::hTaa::ဋှါ
::hThaa::ဌှါ
::hDaa::ဍှါ
::hDhaa::ဎှါ
::hNaa::ဏှါ
::htaa::တှါ
::hthaa::ထှါ
::hdaa::ဒှါ
::hdhaa::ဓှါ
::hnaa::နှါ
::hpaa::ပှါ
::hphaa::ဖှါ
::hbaa::ဗှါ
::hbhaa::ဘှါ
::hmaa::မှါ
::hyaa::ယှါ
::hraa::ရှါ
::hlaa::လှါ
::hLaa::ဠှါ
::hwaa::ဝှါ
::hhaa::ဟှါ
::hsaa::သှါ
::hSaa::ဿှါ

::hkar::ကှော
::hkhar::ခှော
::hgar::ဂှော
::hghar::ဃှော
::hngar::ငှော
::hcar::စှော
::hchar::ဆှော
::hjar::ဇှော
::hjhar::ဈှော
::hnyar::ဉှော
::hNyar::ညှော
::hTar::ဋှော
::hThar::ဌှော
::hDar::ဍှော
::hDhar::ဎှော
::hNar::ဏှော
::htar::တှော
::hthar::ထှော
::hdar::ဒှော
::hdhar::ဓှော
::hnar::နှော
::hpar::ပှော
::hphar::ဖှော
::hbar::ဗှော
::hbhar::ဘှော
::hmar::မှော
::hyar::ယှော
::hrar::ရှော
::hlar::လှော
::hLar::ဠှော
::hwar::ဝှော
::hhar::ဟှော
::hsar::သှော
::hSar::ဿှော

::hki::ကှိ
::hkhi::ခှိ
::hgi::ဂှိ
::hghi::ဃှိ
::hngi::ငှိ
::hci::စှိ
::hchi::ဆှိ
::hji::ဇှိ
::hjhi::ဈှိ
::hnyi::ဉှိ
::hNyi::ညှိ
::hTi::ဋှိ
::hThi::ဌှိ
::hDi::ဍှိ
::hDhi::ဎှိ
::hNi::ဏှိ
::hti::တှိ
::hthi::ထှိ
::hdi::ဒှိ
::hdhi::ဓှိ
::hni::နှိ
::hpi::ပှိ
::hphi::ဖှိ
::hbi::ဗှိ
::hbhi::ဘှိ
::hmi::မှိ
::hyi::ယှိ
::hri::ရှိ
::hli::လှိ
::hLi::ဠှိ
::hwi::ဝှိ
::hhi::ဟှိ
::hsi::သှိ
::hSi::ဿှိ

::hkui::ကှို
::hkhui::ခှို
::hgui::ဂှို
::hghui::ဃှို
::hngui::ငှို
::hcui::စှို
::hchui::ဆှို
::hjui::ဇှို
::hjhui::ဈှို
::hnyui::ဉှို
::hNyui::ညှို
::hTui::ဋှို
::hThui::ဌှို
::hDui::ဍှို
::hDhui::ဎှို
::hNui::ဏှို
::htui::တှို
::hthui::ထှို
::hdui::ဒှို
::hdhui::ဓှို
::hnui::နှို
::hpui::ပှို
::hphui::ဖှို
::hbui::ဗှို
::hbhui::ဘှို
::hmui::မှို
::hyui::ယှို
::hrui::ရှို
::hlui::လှို
::hLui::ဠှို
::hwui::ဝှို
::hhui::ဟှို
::hsui::သှို
::hSui::ဿှို

::hkii::ကှီ
::hkhii::ခှီ
::hgii::ဂှီ
::hghii::ဃှီ
::hngii::ငှီ
::hcii::စှီ
::hchii::ဆှီ
::hjii::ဇှီ
::hjhii::ဈှီ
::hnyii::ဉှီ
::hNyii::ညှီ
::hTii::ဋှီ
::hThii::ဌှီ
::hDii::ဍှီ
::hDhii::ဎှီ
::hNii::ဏှီ
::htii::တှီ
::hthii::ထှီ
::hdii::ဒှီ
::hdhii::ဓှီ
::hnii::နှီ
::hpii::ပှီ
::hphii::ဖှီ
::hbii::ဗှီ
::hbhii::ဘှီ
::hmii::မှီ
::hyii::ယှီ
::hrii::ရှီ
::hlii::လှီ
::hLii::ဠှီ
::hwii::ဝှီ
::hhii::ဟှီ
::hsii::သှီ
::hSii::ဿှီ

::hku::ကှု
::hkhu::ခှု
::hgu::ဂှု
::hghu::ဃှု
::hngu::ငှု
::hcu::စှု
::hchu::ဆှု
::hju::ဇှု
::hjhu::ဈှု
::hnyu::ဉှု
::hNyu::ညှု
::hTu::ဋှု
::hThu::ဌှု
::hDu::ဍှု
::hDhu::ဎှု
::hNu::ဏှု
::htu::တှု
::hthu::ထှု
::hdu::ဒှု
::hdhu::ဓှု
::hnu::နှု
::hpu::ပှု
::hphu::ဖှု
::hbu::ဗှု
::hbhu::ဘှု
::hmu::မှု
::hyu::ယှု
::hru::ရှု
::hlu::လှု
::hLu::ဠှု
::hwu::ဝှု
::hhu::ဟှု
::hsu::သှု
::hSu::ဿှု

::hkuu::ကှူ
::hkhuu::ခှူ
::hguu::ဂှူ
::hghuu::ဃှူ
::hnguu::ငှူ
::hcuu::စှူ
::hchuu::ဆှူ
::hjuu::ဇှူ
::hjhuu::ဈှူ
::hnyuu::ဉှူ
::hNyuu::ညှူ
::hTuu::ဋှူ
::hThuu::ဌှူ
::hDuu::ဍှူ
::hDhuu::ဎှူ
::hNuu::ဏှူ
::htuu::တှူ
::hthuu::ထှူ
::hduu::ဒှူ
::hdhuu::ဓှူ
::hnuu::နှူ
::hpuu::ပှူ
::hphuu::ဖှူ
::hbuu::ဗှူ
::hbhuu::ဘှူ
::hmuu::မှူ
::hyuu::ယှူ
::hruu::ရှူ
::hluu::လှူ
::hLuu::ဠှူ
::hwuu::ဝှူ
::hhuu::ဟှူ
::hsuu::သှူ
::hSuu::ဿှူ

::hke::ကှေ
::hkhe::ခှေ
::hge::ဂှေ
::hghe::ဃှေ
::hnge::ငှေ
::hce::စှေ
::hche::ဆှေ
::hje::ဇှေ
::hjhe::ဈှေ
::hnye::ဉှေ
::hNye::ညှေ
::hTe::ဋှေ
::hThe::ဌှေ
::hDe::ဍှေ
::hDhe::ဎှေ
::hNe::ဏှေ
::hte::တှေ
::hthe::ထှေ
::hde::ဒှေ
::hdhe::ဓှေ
::hne::နှေ
::hpe::ပှေ
::hphe::ဖှေ
::hbe::ဗှေ
::hbhe::ဘှေ
::hme::မှေ
::hye::ယှေ
::hre::ရှေ
::hle::လှေ
::hLe::ဠှေ
::hwe::ဝှေ
::hhe::ဟှေ
::hse::သှေ
::hSe::ဿှေ

::hkau::ကှါ်
::hkhau::ခှါ်
::hgau::ဂှါ်
::hghau::ဃှါ်
::hngau::ငှါ်
::hcau::စှါ်
::hchau::ဆှါ်
::hjau::ဇှါ်
::hjhau::ဈှါ်
::hnyau::ဉှါ်
::hNyau::ညှါ်
::hTau::ဋှါ်
::hThau::ဌှါ်
::hDau::ဍှါ်
::hDhau::ဎှါ်
::hNau::ဏှါ်
::htau::တှါ်
::hthau::ထှါ်
::hdau::ဒှါ်
::hdhau::ဓှါ်
::hnau::နှါ်
::hpau::ပှါ်
::hphau::ဖှါ်
::hbau::ဗှါ်
::hbhau::ဘှါ်
::hmau::မှါ်
::hyau::ယှါ်
::hrau::ရှါ်
::hlau::လှါ်
::hLau::ဠှါ်
::hwau::ဝှါ်
::hhau::ဟှါ်
::hsau::သှါ်
::hSau::ဿှါ်

::hkaw::ကှော
::hkhaw::ခှော
::hgaw::ဂှော
::hghaw::ဃှော
::hngaw::ငှော
::hcaw::စှော
::hchaw::ဆှော
::hjaw::ဇှော
::hjhaw::ဈှော
::hnyaw::ဉှော
::hNyaw::ညှော
::hTaw::ဋှော
::hThaw::ဌှော
::hDaw::ဍှော
::hDhaw::ဎှော
::hNaw::ဏှော
::htaw::တှော
::hthaw::ထှော
::hdaw::ဒှော
::hdhaw::ဓှော
::hnaw::နှော
::hpaw::ပှော
::hphaw::ဖှော
::hbaw::ဗှော
::hbhaw::ဘှော
::hmaw::မှော
::hyaw::ယှော
::hraw::ရှော
::hlaw::လှော
::hLaw::ဠှော
::hwaw::ဝှော
::hhaw::ဟှော
::hsaw::သှော
::hSaw::ဿှော

::hkaww::ကှော်
::hkhaww::ခှော်
::hgaww::ဂှော်
::hghaww::ဃှော်
::hngaww::ငှော်
::hcaww::စှော်
::hchaww::ဆှော်
::hjaww::ဇှော်
::hjhaww::ဈှော်
::hnyaww::ဉှော်
::hNyaww::ညှော်
::hTaww::ဋှော်
::hThaww::ဌှော်
::hDaww::ဍှော်
::hDhaww::ဎှော်
::hNaww::ဏှော်
::htaww::တှော်
::hthaww::ထှော်
::hdaww::ဒှော်
::hdhaww::ဓှော်
::hnaww::နှော်
::hpaww::ပှော်
::hphaww::ဖှော်
::hbaww::ဗှော်
::hbhaww::ဘှော်
::hmaww::မှော်
::hyaww::ယှော်
::hraww::ရှော်
::hlaww::လှော်
::hLaww::ဠှော်
::hwaww::ဝှော်
::hhaww::ဟှော်
::hsaww::သှော်
::hSaww::ဿှော်

::hkai::ကှဲ
::hkhai::ခှဲ
::hgai::ဂှဲ
::hghai::ဃှဲ
::hngai::ငှဲ
::hcai::စှဲ
::hchai::ဆှဲ
::hjai::ဇှဲ
::hjhai::ဈှဲ
::hnyai::ဉှဲ
::hNyai::ညှဲ
::hTai::ဋှဲ
::hThai::ဌှဲ
::hDai::ဍှဲ
::hDhai::ဎှဲ
::hNai::ဏှဲ
::htai::တှဲ
::hthai::ထှဲ
::hdai::ဒှဲ
::hdhai::ဓှဲ
::hnai::နှဲ
::hpai::ပှဲ
::hphai::ဖှဲ
::hbai::ဗှဲ
::hbhai::ဘှဲ
::hmai::မှဲ
::hyai::ယှဲ
::hrai::ရှဲ
::hlai::လှဲ
::hLai::ဠှဲ
::hwai::ဝှဲ
::hhai::ဟှဲ
::hsai::သှဲ
::hSai::ဿှဲ

::hkya::ကျှ
::hkhya::ချှ
::hgya::ဂျှ
::hghya::ဃျှ
::hngya::ငျှ
::hcya::စျှ
::hchya::ဆျှ
::hjya::ဇျှ
::hjhya::ဈျှ
::hnyya::ဉျှ
::hNyya::ညျှ
::hTya::ဋျှ
::hThya::ဌျှ
::hDya::ဍျှ
::hDhya::ဎျှ
::hNya::ဏျှ
::htya::တျှ
::hthya::ထျှ
::hdya::ဒျှ
::hdhya::ဓျှ
::hnya::နျှ
::hpya::ပျှ
::hphya::ဖျှ
::hbya::ဗျှ
::hbhya::ဘျှ
::hmya::မျှ
::hyya::ယျှ
::hrya::ရျှ
::hlya::လျှ
::hLya::ဠျှ
::hwya::ဝျှ
::hhya::ဟျှ
::hsya::သျှ
::hSya::ဿျှ

::hkyaa::ကျှါ
::hkhyaa::ချှါ
::hgyaa::ဂျှါ
::hghyaa::ဃျှါ
::hngyaa::ငျှါ
::hcyaa::စျှါ
::hchyaa::ဆျှါ
::hjyaa::ဇျှါ
::hjhyaa::ဈျှါ
::hnyyaa::ဉျှါ
::hNyyaa::ညျှါ
::hTyaa::ဋျှါ
::hThyaa::ဌျှါ
::hDyaa::ဍျှါ
::hDhyaa::ဎျှါ
::hNyaa::ဏျှါ
::htyaa::တျှါ
::hthyaa::ထျှါ
::hdyaa::ဒျှါ
::hdhyaa::ဓျှါ
::hnyaa::နျှါ
::hpyaa::ပျှါ
::hphyaa::ဖျှါ
::hbyaa::ဗျှါ
::hbhyaa::ဘျှါ
::hmyaa::မျှါ
::hyyaa::ယျှါ
::hryaa::ရျှါ
::hlyaa::လျှါ
::hLyaa::ဠျှါ
::hwyaa::ဝျှါ
::hhyaa::ဟျှါ
::hsyaa::သျှါ
::hSyaa::ဿျှါ

::hkyar::ကျှော
::hkhyar::ချှော
::hgyar::ဂျှော
::hghyar::ဃျှော
::hngyar::ငျှော
::hcyar::စျှော
::hchyar::ဆျှော
::hjyar::ဇျှော
::hjhyar::ဈျှော
::hnyyar::ဉျှော
::hNyyar::ညျှော
::hTyar::ဋျှော
::hThyar::ဌျှော
::hDyar::ဍျှော
::hDhyar::ဎျှော
::hNyar::ဏျှော
::htyar::တျှော
::hthyar::ထျှော
::hdyar::ဒျှော
::hdhyar::ဓျှော
::hnyar::နျှော
::hpyar::ပျှော
::hphyar::ဖျှော
::hbyar::ဗျှော
::hbhyar::ဘျှော
::hmyar::မျှော
::hyyar::ယျှော
::hryar::ရျှော
::hlyar::လျှော
::hLyar::ဠျှော
::hwyar::ဝျှော
::hhyar::ဟျှော
::hsyar::သျှော
::hSyar::ဿျှော

::hkyi::ကျှိ
::hkhyi::ချှိ
::hgyi::ဂျှိ
::hghyi::ဃျှိ
::hngyi::ငျှိ
::hcyi::စျှိ
::hchyi::ဆျှိ
::hjyi::ဇျှိ
::hjhyi::ဈျှိ
::hnyyi::ဉျှိ
::hNyyi::ညျှိ
::hTyi::ဋျှိ
::hThyi::ဌျှိ
::hDyi::ဍျှိ
::hDhyi::ဎျှိ
::hNyi::ဏျှိ
::htyi::တျှိ
::hthyi::ထျှိ
::hdyi::ဒျှိ
::hdhyi::ဓျှိ
::hnyi::နျှိ
::hpyi::ပျှိ
::hphyi::ဖျှိ
::hbyi::ဗျှိ
::hbhyi::ဘျှိ
::hmyi::မျှိ
::hyyi::ယျှိ
::hryi::ရျှိ
::hlyi::လျှိ
::hLyi::ဠျှိ
::hwyi::ဝျှိ
::hhyi::ဟျှိ
::hsyi::သျှိ
::hSyi::ဿျှိ

::hkyui::ကျှို
::hkhyui::ချှို
::hgyui::ဂျှို
::hghyui::ဃျှို
::hngyui::ငျှို
::hcyui::စျှို
::hchyui::ဆျှို
::hjyui::ဇျှို
::hjhyui::ဈျှို
::hnyyui::ဉျှို
::hNyyui::ညျှို
::hTyui::ဋျှို
::hThyui::ဌျှို
::hDyui::ဍျှို
::hDhyui::ဎျှို
::hNyui::ဏျှို
::htyui::တျှို
::hthyui::ထျှို
::hdyui::ဒျှို
::hdhyui::ဓျှို
::hnyui::နျှို
::hpyui::ပျှို
::hphyui::ဖျှို
::hbyui::ဗျှို
::hbhyui::ဘျှို
::hmyui::မျှို
::hyyui::ယျှို
::hryui::ရျှို
::hlyui::လျှို
::hLyui::ဠျှို
::hwyui::ဝျှို
::hhyui::ဟျှို
::hsyui::သျှို
::hSyui::ဿျှို

::hkyii::ကျှီ
::hkhyii::ချှီ
::hgyii::ဂျှီ
::hghyii::ဃျှီ
::hngyii::ငျှီ
::hcyii::စျှီ
::hchyii::ဆျှီ
::hjyii::ဇျှီ
::hjhyii::ဈျှီ
::hnyyii::ဉျှီ
::hNyyii::ညျှီ
::hTyii::ဋျှီ
::hThyii::ဌျှီ
::hDyii::ဍျှီ
::hDhyii::ဎျှီ
::hNyii::ဏျှီ
::htyii::တျှီ
::hthyii::ထျှီ
::hdyii::ဒျှီ
::hdhyii::ဓျှီ
::hnyii::နျှီ
::hpyii::ပျှီ
::hphyii::ဖျှီ
::hbyii::ဗျှီ
::hbhyii::ဘျှီ
::hmyii::မျှီ
::hyyii::ယျှီ
::hryii::ရျှီ
::hlyii::လျှီ
::hLyii::ဠျှီ
::hwyii::ဝျှီ
::hhyii::ဟျှီ
::hsyii::သျှီ
::hSyii::ဿျှီ

::hkyu::ကျှု
::hkhyu::ချှု
::hgyu::ဂျှု
::hghyu::ဃျှု
::hngyu::ငျှု
::hcyu::စျှု
::hchyu::ဆျှု
::hjyu::ဇျှု
::hjhyu::ဈျှု
::hnyyu::ဉျှု
::hNyyu::ညျှု
::hTyu::ဋျှု
::hThyu::ဌျှု
::hDyu::ဍျှု
::hDhyu::ဎျှု
::hNyu::ဏျှု
::htyu::တျှု
::hthyu::ထျှု
::hdyu::ဒျှု
::hdhyu::ဓျှု
::hnyu::နျှု
::hpyu::ပျှု
::hphyu::ဖျှု
::hbyu::ဗျှု
::hbhyu::ဘျှု
::hmyu::မျှု
::hyyu::ယျှု
::hryu::ရျှု
::hlyu::လျှု
::hLyu::ဠျှု
::hwyu::ဝျှု
::hhyu::ဟျှု
::hsyu::သျှု
::hSyu::ဿျှု

::hkyuu::ကျှူ
::hkhyuu::ချှူ
::hgyuu::ဂျှူ
::hghyuu::ဃျှူ
::hngyuu::ငျှူ
::hcyuu::စျှူ
::hchyuu::ဆျှူ
::hjyuu::ဇျှူ
::hjhyuu::ဈျှူ
::hnyyuu::ဉျှူ
::hNyyuu::ညျှူ
::hTyuu::ဋျှူ
::hThyuu::ဌျှူ
::hDyuu::ဍျှူ
::hDhyuu::ဎျှူ
::hNyuu::ဏျှူ
::htyuu::တျှူ
::hthyuu::ထျှူ
::hdyuu::ဒျှူ
::hdhyuu::ဓျှူ
::hnyuu::နျှူ
::hpyuu::ပျှူ
::hphyuu::ဖျှူ
::hbyuu::ဗျှူ
::hbhyuu::ဘျှူ
::hmyuu::မျှူ
::hyyuu::ယျှူ
::hryuu::ရျှူ
::hlyuu::လျှူ
::hLyuu::ဠျှူ
::hwyuu::ဝျှူ
::hhyuu::ဟျှူ
::hsyuu::သျှူ
::hSyuu::ဿျှူ

::hkye::ကျှေ
::hkhye::ချှေ
::hgye::ဂျှေ
::hghye::ဃျှေ
::hngye::ငျှေ
::hcye::စျှေ
::hchye::ဆျှေ
::hjye::ဇျှေ
::hjhye::ဈျှေ
::hnyye::ဉျှေ
::hNyye::ညျှေ
::hTye::ဋျှေ
::hThye::ဌျှေ
::hDye::ဍျှေ
::hDhye::ဎျှေ
::hNye::ဏျှေ
::htye::တျှေ
::hthye::ထျှေ
::hdye::ဒျှေ
::hdhye::ဓျှေ
::hnye::နျှေ
::hpye::ပျှေ
::hphye::ဖျှေ
::hbye::ဗျှေ
::hbhye::ဘျှေ
::hmye::မျှေ
::hyye::ယျှေ
::hrye::ရျှေ
::hlye::လျှေ
::hLye::ဠျှေ
::hwye::ဝျှေ
::hhye::ဟျှေ
::hsye::သျှေ
::hSye::ဿျှေ

::hkyau::ကျှါ်
::hkhyau::ချှါ်
::hgyau::ဂျှါ်
::hghyau::ဃျှါ်
::hngyau::ငျှါ်
::hcyau::စျှါ်
::hchyau::ဆျှါ်
::hjyau::ဇျှါ်
::hjhyau::ဈျှါ်
::hnyyau::ဉျှါ်
::hNyyau::ညျှါ်
::hTyau::ဋျှါ်
::hThyau::ဌျှါ်
::hDyau::ဍျှါ်
::hDhyau::ဎျှါ်
::hNyau::ဏျှါ်
::htyau::တျှါ်
::hthyau::ထျှါ်
::hdyau::ဒျှါ်
::hdhyau::ဓျှါ်
::hnyau::နျှါ်
::hpyau::ပျှါ်
::hphyau::ဖျှါ်
::hbyau::ဗျှါ်
::hbhyau::ဘျှါ်
::hmyau::မျှါ်
::hyyau::ယျှါ်
::hryau::ရျှါ်
::hlyau::လျှါ်
::hLyau::ဠျှါ်
::hwyau::ဝျှါ်
::hhyau::ဟျှါ်
::hsyau::သျှါ်
::hSyau::ဿျှါ်

::hkyaw::ကျှော
::hkhyaw::ချှော
::hgyaw::ဂျှော
::hghyaw::ဃျှော
::hngyaw::ငျှော
::hcyaw::စျှော
::hchyaw::ဆျှော
::hjyaw::ဇျှော
::hjhyaw::ဈျှော
::hnyyaw::ဉျှော
::hNyyaw::ညျှော
::hTyaw::ဋျှော
::hThyaw::ဌျှော
::hDyaw::ဍျှော
::hDhyaw::ဎျှော
::hNyaw::ဏျှော
::htyaw::တျှော
::hthyaw::ထျှော
::hdyaw::ဒျှော
::hdhyaw::ဓျှော
::hnyaw::နျှော
::hpyaw::ပျှော
::hphyaw::ဖျှော
::hbyaw::ဗျှော
::hbhyaw::ဘျှော
::hmyaw::မျှော
::hyyaw::ယျှော
::hryaw::ရျှော
::hlyaw::လျှော
::hLyaw::ဠျှော
::hwyaw::ဝျှော
::hhyaw::ဟျှော
::hsyaw::သျှော
::hSyaw::ဿျှော

::hkyaww::ကျှော်
::hkhyaww::ချှော်
::hgyaww::ဂျှော်
::hghyaww::ဃျှော်
::hngyaww::ငျှော်
::hcyaww::စျှော်
::hchyaww::ဆျှော်
::hjyaww::ဇျှော်
::hjhyaww::ဈျှော်
::hnyyaww::ဉျှော်
::hNyyaww::ညျှော်
::hTyaww::ဋျှော်
::hThyaww::ဌျှော်
::hDyaww::ဍျှော်
::hDhyaww::ဎျှော်
::hNyaww::ဏျှော်
::htyaww::တျှော်
::hthyaww::ထျှော်
::hdyaww::ဒျှော်
::hdhyaww::ဓျှော်
::hnyaww::နျှော်
::hpyaww::ပျှော်
::hphyaww::ဖျှော်
::hbyaww::ဗျှော်
::hbhyaww::ဘျှော်
::hmyaww::မျှော်
::hyyaww::ယျှော်
::hryaww::ရျှော်
::hlyaww::လျှော်
::hLyaww::ဠျှော်
::hwyaww::ဝျှော်
::hhyaww::ဟျှော်
::hsyaww::သျှော်
::hSyaww::ဿျှော်

::hkyai::ကျှဲ
::hkhyai::ချှဲ
::hgyai::ဂျှဲ
::hghyai::ဃျှဲ
::hngyai::ငျှဲ
::hcyai::စျှဲ
::hchyai::ဆျှဲ
::hjyai::ဇျှဲ
::hjhyai::ဈျှဲ
::hnyyai::ဉျှဲ
::hNyyai::ညျှဲ
::hTyai::ဋျှဲ
::hThyai::ဌျှဲ
::hDyai::ဍျှဲ
::hDhyai::ဎျှဲ
::hNyai::ဏျှဲ
::htyai::တျှဲ
::hthyai::ထျှဲ
::hdyai::ဒျှဲ
::hdhyai::ဓျှဲ
::hnyai::နျှဲ
::hpyai::ပျှဲ
::hphyai::ဖျှဲ
::hbyai::ဗျှဲ
::hbhyai::ဘျှဲ
::hmyai::မျှဲ
::hyyai::ယျှဲ
::hryai::ရျှဲ
::hlyai::လျှဲ
::hLyai::ဠျှဲ
::hwyai::ဝျှဲ
::hhyai::ဟျှဲ
::hsyai::သျှဲ
::hSyai::ဿျှဲ

::kywa::ကျွ
::khywa::ချွ
::gywa::ဂျွ
::ghywa::ဃျွ
::ngywa::ငျွ
::cywa::စျွ
::chywa::ဆျွ
::jywa::ဇျွ
::jhywa::ဈျွ
::nyywa::ဉျွ
::Nyywa::ညျွ
::Tywa::ဋျွ
::Thywa::ဌျွ
::Dywa::ဍျွ
::Dhywa::ဎျွ
::Nywa::ဏျွ
::tywa::တျွ
::thywa::ထျွ
::dywa::ဒျွ
::dhywa::ဓျွ
::nywa::နျွ
::pywa::ပျွ
::phywa::ဖျွ
::bywa::ဗျွ
::bhywa::ဘျွ
::mywa::မျွ
::yywa::ယျွ
::rywa::ရျွ
::lywa::လျွ
::Lywa::ဠျွ
::wywa::ဝျွ
::hywa::ဟျွ
::sywa::သျွ
::Sywa::ဿျွ

::kywaa::ကျွါ
::khywaa::ချွါ
::gywaa::ဂျွါ
::ghywaa::ဃျွါ
::ngywaa::ငျွါ
::cywaa::စျွါ
::chywaa::ဆျွါ
::jywaa::ဇျွါ
::jhywaa::ဈျွါ
::nyywaa::ဉျွါ
::Nyywaa::ညျွါ
::Tywaa::ဋျွါ
::Thywaa::ဌျွါ
::Dywaa::ဍျွါ
::Dhywaa::ဎျွါ
::Nywaa::ဏျွါ
::tywaa::တျွါ
::thywaa::ထျွါ
::dywaa::ဒျွါ
::dhywaa::ဓျွါ
::nywaa::နျွါ
::pywaa::ပျွါ
::phywaa::ဖျွါ
::bywaa::ဗျွါ
::bhywaa::ဘျွါ
::mywaa::မျွါ
::yywaa::ယျွါ
::rywaa::ရျွါ
::lywaa::လျွါ
::Lywaa::ဠျွါ
::wywaa::ဝျွါ
::hywaa::ဟျွါ
::sywaa::သျွါ
::Sywaa::ဿျွါ

::kywar::ကျွော
::khywar::ချွော
::gywar::ဂျွော
::ghywar::ဃျွော
::ngywar::ငျွော
::cywar::စျွော
::chywar::ဆျွော
::jywar::ဇျွော
::jhywar::ဈျွော
::nyywar::ဉျွော
::Nyywar::ညျွော
::Tywar::ဋျွော
::Thywar::ဌျွော
::Dywar::ဍျွော
::Dhywar::ဎျွော
::Nywar::ဏျွော
::tywar::တျွော
::thywar::ထျွော
::dywar::ဒျွော
::dhywar::ဓျွော
::nywar::နျွော
::pywar::ပျွော
::phywar::ဖျွော
::bywar::ဗျွော
::bhywar::ဘျွော
::mywar::မျွော
::yywar::ယျွော
::rywar::ရျွော
::lywar::လျွော
::Lywar::ဠျွော
::wywar::ဝျွော
::hywar::ဟျွော
::sywar::သျွော
::Sywar::ဿျွော

::kywi::ကျွိ
::khywi::ချွိ
::gywi::ဂျွိ
::ghywi::ဃျွိ
::ngywi::ငျွိ
::cywi::စျွိ
::chywi::ဆျွိ
::jywi::ဇျွိ
::jhywi::ဈျွိ
::nyywi::ဉျွိ
::Nyywi::ညျွိ
::Tywi::ဋျွိ
::Thywi::ဌျွိ
::Dywi::ဍျွိ
::Dhywi::ဎျွိ
::Nywi::ဏျွိ
::tywi::တျွိ
::thywi::ထျွိ
::dywi::ဒျွိ
::dhywi::ဓျွိ
::nywi::နျွိ
::pywi::ပျွိ
::phywi::ဖျွိ
::bywi::ဗျွိ
::bhywi::ဘျွိ
::mywi::မျွိ
::yywi::ယျွိ
::rywi::ရျွိ
::lywi::လျွိ
::Lywi::ဠျွိ
::wywi::ဝျွိ
::hywi::ဟျွိ
::sywi::သျွိ
::Sywi::ဿျွိ

::kywui::ကျွို
::khywui::ချွို
::gywui::ဂျွို
::ghywui::ဃျွို
::ngywui::ငျွို
::cywui::စျွို
::chywui::ဆျွို
::jywui::ဇျွို
::jhywui::ဈျွို
::nyywui::ဉျွို
::Nyywui::ညျွို
::Tywui::ဋျွို
::Thywui::ဌျွို
::Dywui::ဍျွို
::Dhywui::ဎျွို
::Nywui::ဏျွို
::tywui::တျွို
::thywui::ထျွို
::dywui::ဒျွို
::dhywui::ဓျွို
::nywui::နျွို
::pywui::ပျွို
::phywui::ဖျွို
::bywui::ဗျွို
::bhywui::ဘျွို
::mywui::မျွို
::yywui::ယျွို
::rywui::ရျွို
::lywui::လျွို
::Lywui::ဠျွို
::wywui::ဝျွို
::hywui::ဟျွို
::sywui::သျွို
::Sywui::ဿျွို

::kywii::ကျွီ
::khywii::ချွီ
::gywii::ဂျွီ
::ghywii::ဃျွီ
::ngywii::ငျွီ
::cywii::စျွီ
::chywii::ဆျွီ
::jywii::ဇျွီ
::jhywii::ဈျွီ
::nyywii::ဉျွီ
::Nyywii::ညျွီ
::Tywii::ဋျွီ
::Thywii::ဌျွီ
::Dywii::ဍျွီ
::Dhywii::ဎျွီ
::Nywii::ဏျွီ
::tywii::တျွီ
::thywii::ထျွီ
::dywii::ဒျွီ
::dhywii::ဓျွီ
::nywii::နျွီ
::pywii::ပျွီ
::phywii::ဖျွီ
::bywii::ဗျွီ
::bhywii::ဘျွီ
::mywii::မျွီ
::yywii::ယျွီ
::rywii::ရျွီ
::lywii::လျွီ
::Lywii::ဠျွီ
::wywii::ဝျွီ
::hywii::ဟျွီ
::sywii::သျွီ
::Sywii::ဿျွီ

::kywu::ကျွု
::khywu::ချွု
::gywu::ဂျွု
::ghywu::ဃျွု
::ngywu::ငျွု
::cywu::စျွု
::chywu::ဆျွု
::jywu::ဇျွု
::jhywu::ဈျွု
::nyywu::ဉျွု
::Nyywu::ညျွု
::Tywu::ဋျွု
::Thywu::ဌျွု
::Dywu::ဍျွု
::Dhywu::ဎျွု
::Nywu::ဏျွု
::tywu::တျွု
::thywu::ထျွု
::dywu::ဒျွု
::dhywu::ဓျွု
::nywu::နျွု
::pywu::ပျွု
::phywu::ဖျွု
::bywu::ဗျွု
::bhywu::ဘျွု
::mywu::မျွု
::yywu::ယျွု
::rywu::ရျွု
::lywu::လျွု
::Lywu::ဠျွု
::wywu::ဝျွု
::hywu::ဟျွု
::sywu::သျွု
::Sywu::ဿျွု

::kywuu::ကျွူ
::khywuu::ချွူ
::gywuu::ဂျွူ
::ghywuu::ဃျွူ
::ngywuu::ငျွူ
::cywuu::စျွူ
::chywuu::ဆျွူ
::jywuu::ဇျွူ
::jhywuu::ဈျွူ
::nyywuu::ဉျွူ
::Nyywuu::ညျွူ
::Tywuu::ဋျွူ
::Thywuu::ဌျွူ
::Dywuu::ဍျွူ
::Dhywuu::ဎျွူ
::Nywuu::ဏျွူ
::tywuu::တျွူ
::thywuu::ထျွူ
::dywuu::ဒျွူ
::dhywuu::ဓျွူ
::nywuu::နျွူ
::pywuu::ပျွူ
::phywuu::ဖျွူ
::bywuu::ဗျွူ
::bhywuu::ဘျွူ
::mywuu::မျွူ
::yywuu::ယျွူ
::rywuu::ရျွူ
::lywuu::လျွူ
::Lywuu::ဠျွူ
::wywuu::ဝျွူ
::hywuu::ဟျွူ
::sywuu::သျွူ
::Sywuu::ဿျွူ

::kywe::ကျွေ
::khywe::ချွေ
::gywe::ဂျွေ
::ghywe::ဃျွေ
::ngywe::ငျွေ
::cywe::စျွေ
::chywe::ဆျွေ
::jywe::ဇျွေ
::jhywe::ဈျွေ
::nyywe::ဉျွေ
::Nyywe::ညျွေ
::Tywe::ဋျွေ
::Thywe::ဌျွေ
::Dywe::ဍျွေ
::Dhywe::ဎျွေ
::Nywe::ဏျွေ
::tywe::တျွေ
::thywe::ထျွေ
::dywe::ဒျွေ
::dhywe::ဓျွေ
::nywe::နျွေ
::pywe::ပျွေ
::phywe::ဖျွေ
::bywe::ဗျွေ
::bhywe::ဘျွေ
::mywe::မျွေ
::yywe::ယျွေ
::rywe::ရျွေ
::lywe::လျွေ
::Lywe::ဠျွေ
::wywe::ဝျွေ
::hywe::ဟျွေ
::sywe::သျွေ
::Sywe::ဿျွေ

::kywau::ကျွါ်
::khywau::ချွါ်
::gywau::ဂျွါ်
::ghywau::ဃျွါ်
::ngywau::ငျွါ်
::cywau::စျွါ်
::chywau::ဆျွါ်
::jywau::ဇျွါ်
::jhywau::ဈျွါ်
::nyywau::ဉျွါ်
::Nyywau::ညျွါ်
::Tywau::ဋျွါ်
::Thywau::ဌျွါ်
::Dywau::ဍျွါ်
::Dhywau::ဎျွါ်
::Nywau::ဏျွါ်
::tywau::တျွါ်
::thywau::ထျွါ်
::dywau::ဒျွါ်
::dhywau::ဓျွါ်
::nywau::နျွါ်
::pywau::ပျွါ်
::phywau::ဖျွါ်
::bywau::ဗျွါ်
::bhywau::ဘျွါ်
::mywau::မျွါ်
::yywau::ယျွါ်
::rywau::ရျွါ်
::lywau::လျွါ်
::Lywau::ဠျွါ်
::wywau::ဝျွါ်
::hywau::ဟျွါ်
::sywau::သျွါ်
::Sywau::ဿျွါ်

::kywaw::ကျွော
::khywaw::ချွော
::gywaw::ဂျွော
::ghywaw::ဃျွော
::ngywaw::ငျွော
::cywaw::စျွော
::chywaw::ဆျွော
::jywaw::ဇျွော
::jhywaw::ဈျွော
::nyywaw::ဉျွော
::Nyywaw::ညျွော
::Tywaw::ဋျွော
::Thywaw::ဌျွော
::Dywaw::ဍျွော
::Dhywaw::ဎျွော
::Nywaw::ဏျွော
::tywaw::တျွော
::thywaw::ထျွော
::dywaw::ဒျွော
::dhywaw::ဓျွော
::nywaw::နျွော
::pywaw::ပျွော
::phywaw::ဖျွော
::bywaw::ဗျွော
::bhywaw::ဘျွော
::mywaw::မျွော
::yywaw::ယျွော
::rywaw::ရျွော
::lywaw::လျွော
::Lywaw::ဠျွော
::wywaw::ဝျွော
::hywaw::ဟျွော
::sywaw::သျွော
::Sywaw::ဿျွော

::kywaww::ကျွော်
::khywaww::ချွော်
::gywaww::ဂျွော်
::ghywaww::ဃျွော်
::ngywaww::ငျွော်
::cywaww::စျွော်
::chywaww::ဆျွော်
::jywaww::ဇျွော်
::jhywaww::ဈျွော်
::nyywaww::ဉျွော်
::Nyywaww::ညျွော်
::Tywaww::ဋျွော်
::Thywaww::ဌျွော်
::Dywaww::ဍျွော်
::Dhywaww::ဎျွော်
::Nywaww::ဏျွော်
::tywaww::တျွော်
::thywaww::ထျွော်
::dywaww::ဒျွော်
::dhywaww::ဓျွော်
::nywaww::နျွော်
::pywaww::ပျွော်
::phywaww::ဖျွော်
::bywaww::ဗျွော်
::bhywaww::ဘျွော်
::mywaww::မျွော်
::yywaww::ယျွော်
::rywaww::ရျွော်
::lywaww::လျွော်
::Lywaww::ဠျွော်
::wywaww::ဝျွော်
::hywaww::ဟျွော်
::sywaww::သျွော်
::Sywaww::ဿျွော်

::kywai::ကျွဲ
::khywai::ချွဲ
::gywai::ဂျွဲ
::ghywai::ဃျွဲ
::ngywai::ငျွဲ
::cywai::စျွဲ
::chywai::ဆျွဲ
::jywai::ဇျွဲ
::jhywai::ဈျွဲ
::nyywai::ဉျွဲ
::Nyywai::ညျွဲ
::Tywai::ဋျွဲ
::Thywai::ဌျွဲ
::Dywai::ဍျွဲ
::Dhywai::ဎျွဲ
::Nywai::ဏျွဲ
::tywai::တျွဲ
::thywai::ထျွဲ
::dywai::ဒျွဲ
::dhywai::ဓျွဲ
::nywai::နျွဲ
::pywai::ပျွဲ
::phywai::ဖျွဲ
::bywai::ဗျွဲ
::bhywai::ဘျွဲ
::mywai::မျွဲ
::yywai::ယျွဲ
::rywai::ရျွဲ
::lywai::လျွဲ
::Lywai::ဠျွဲ
::wywai::ဝျွဲ
::hywai::ဟျွဲ
::sywai::သျွဲ
::Sywai::ဿျွဲ

::hkywa::ကျွှ
::hkhywa::ချွှ
::hgywa::ဂျွှ
::hghywa::ဃျွှ
::hngywa::ငျွှ
::hcywa::စျွှ
::hchywa::ဆျွှ
::hjywa::ဇျွှ
::hjhywa::ဈျွှ
::hnyywa::ဉျွှ
::hNyywa::ညျွှ
::hTywa::ဋျွှ
::hThywa::ဌျွှ
::hDywa::ဍျွှ
::hDhywa::ဎျွှ
::hNywa::ဏျွှ
::htywa::တျွှ
::hthywa::ထျွှ
::hdywa::ဒျွှ
::hdhywa::ဓျွှ
::hnywa::နျွှ
::hpywa::ပျွှ
::hphywa::ဖျွှ
::hbywa::ဗျွှ
::hbhywa::ဘျွှ
::hmywa::မျွှ
::hyywa::ယျွှ
::hrywa::ရျွှ
::hlywa::လျွှ
::hLywa::ဠျွှ
::hwywa::ဝျွှ
::hhywa::ဟျွှ
::hsywa::သျွှ
::hSywa::ဿျွှ

::hkywaa::ကျွှါ
::hkhywaa::ချွှါ
::hgywaa::ဂျွှါ
::hghywaa::ဃျွှါ
::hngywaa::ငျွှါ
::hcywaa::စျွှါ
::hchywaa::ဆျွှါ
::hjywaa::ဇျွှါ
::hjhywaa::ဈျွှါ
::hnyywaa::ဉျွှါ
::hNyywaa::ညျွှါ
::hTywaa::ဋျွှါ
::hThywaa::ဌျွှါ
::hDywaa::ဍျွှါ
::hDhywaa::ဎျွှါ
::hNywaa::ဏျွှါ
::htywaa::တျွှါ
::hthywaa::ထျွှါ
::hdywaa::ဒျွှါ
::hdhywaa::ဓျွှါ
::hnywaa::နျွှါ
::hpywaa::ပျွှါ
::hphywaa::ဖျွှါ
::hbywaa::ဗျွှါ
::hbhywaa::ဘျွှါ
::hmywaa::မျွှါ
::hyywaa::ယျွှါ
::hrywaa::ရျွှါ
::hlywaa::လျွှါ
::hLywaa::ဠျွှါ
::hwywaa::ဝျွှါ
::hhywaa::ဟျွှါ
::hsywaa::သျွှါ
::hSywaa::ဿျွှါ

::hkywar::ကျွှော
::hkhywar::ချွှော
::hgywar::ဂျွှော
::hghywar::ဃျွှော
::hngywar::ငျွှော
::hcywar::စျွှော
::hchywar::ဆျွှော
::hjywar::ဇျွှော
::hjhywar::ဈျွှော
::hnyywar::ဉျွှော
::hNyywar::ညျွှော
::hTywar::ဋျွှော
::hThywar::ဌျွှော
::hDywar::ဍျွှော
::hDhywar::ဎျွှော
::hNywar::ဏျွှော
::htywar::တျွှော
::hthywar::ထျွှော
::hdywar::ဒျွှော
::hdhywar::ဓျွှော
::hnywar::နျွှော
::hpywar::ပျွှော
::hphywar::ဖျွှော
::hbywar::ဗျွှော
::hbhywar::ဘျွှော
::hmywar::မျွှော
::hyywar::ယျွှော
::hrywar::ရျွှော
::hlywar::လျွှော
::hLywar::ဠျွှော
::hwywar::ဝျွှော
::hhywar::ဟျွှော
::hsywar::သျွှော
::hSywar::ဿျွှော

::hkywi::ကျွှိ
::hkhywi::ချွှိ
::hgywi::ဂျွှိ
::hghywi::ဃျွှိ
::hngywi::ငျွှိ
::hcywi::စျွှိ
::hchywi::ဆျွှိ
::hjywi::ဇျွှိ
::hjhywi::ဈျွှိ
::hnyywi::ဉျွှိ
::hNyywi::ညျွှိ
::hTywi::ဋျွှိ
::hThywi::ဌျွှိ
::hDywi::ဍျွှိ
::hDhywi::ဎျွှိ
::hNywi::ဏျွှိ
::htywi::တျွှိ
::hthywi::ထျွှိ
::hdywi::ဒျွှိ
::hdhywi::ဓျွှိ
::hnywi::နျွှိ
::hpywi::ပျွှိ
::hphywi::ဖျွှိ
::hbywi::ဗျွှိ
::hbhywi::ဘျွှိ
::hmywi::မျွှိ
::hyywi::ယျွှိ
::hrywi::ရျွှိ
::hlywi::လျွှိ
::hLywi::ဠျွှိ
::hwywi::ဝျွှိ
::hhywi::ဟျွှိ
::hsywi::သျွှိ
::hSywi::ဿျွှိ

::hkywui::ကျွှို
::hkhywui::ချွှို
::hgywui::ဂျွှို
::hghywui::ဃျွှို
::hngywui::ငျွှို
::hcywui::စျွှို
::hchywui::ဆျွှို
::hjywui::ဇျွှို
::hjhywui::ဈျွှို
::hnyywui::ဉျွှို
::hNyywui::ညျွှို
::hTywui::ဋျွှို
::hThywui::ဌျွှို
::hDywui::ဍျွှို
::hDhywui::ဎျွှို
::hNywui::ဏျွှို
::htywui::တျွှို
::hthywui::ထျွှို
::hdywui::ဒျွှို
::hdhywui::ဓျွှို
::hnywui::နျွှို
::hpywui::ပျွှို
::hphywui::ဖျွှို
::hbywui::ဗျွှို
::hbhywui::ဘျွှို
::hmywui::မျွှို
::hyywui::ယျွှို
::hrywui::ရျွှို
::hlywui::လျွှို
::hLywui::ဠျွှို
::hwywui::ဝျွှို
::hhywui::ဟျွှို
::hsywui::သျွှို
::hSywui::ဿျွှို

::hkywii::ကျွှီ
::hkhywii::ချွှီ
::hgywii::ဂျွှီ
::hghywii::ဃျွှီ
::hngywii::ငျွှီ
::hcywii::စျွှီ
::hchywii::ဆျွှီ
::hjywii::ဇျွှီ
::hjhywii::ဈျွှီ
::hnyywii::ဉျွှီ
::hNyywii::ညျွှီ
::hTywii::ဋျွှီ
::hThywii::ဌျွှီ
::hDywii::ဍျွှီ
::hDhywii::ဎျွှီ
::hNywii::ဏျွှီ
::htywii::တျွှီ
::hthywii::ထျွှီ
::hdywii::ဒျွှီ
::hdhywii::ဓျွှီ
::hnywii::နျွှီ
::hpywii::ပျွှီ
::hphywii::ဖျွှီ
::hbywii::ဗျွှီ
::hbhywii::ဘျွှီ
::hmywii::မျွှီ
::hyywii::ယျွှီ
::hrywii::ရျွှီ
::hlywii::လျွှီ
::hLywii::ဠျွှီ
::hwywii::ဝျွှီ
::hhywii::ဟျွှီ
::hsywii::သျွှီ
::hSywii::ဿျွှီ

::hkywu::ကျွှု
::hkhywu::ချွှု
::hgywu::ဂျွှု
::hghywu::ဃျွှု
::hngywu::ငျွှု
::hcywu::စျွှု
::hchywu::ဆျွှု
::hjywu::ဇျွှု
::hjhywu::ဈျွှု
::hnyywu::ဉျွှု
::hNyywu::ညျွှု
::hTywu::ဋျွှု
::hThywu::ဌျွှု
::hDywu::ဍျွှု
::hDhywu::ဎျွှု
::hNywu::ဏျွှု
::htywu::တျွှု
::hthywu::ထျွှု
::hdywu::ဒျွှု
::hdhywu::ဓျွှု
::hnywu::နျွှု
::hpywu::ပျွှု
::hphywu::ဖျွှု
::hbywu::ဗျွှု
::hbhywu::ဘျွှု
::hmywu::မျွှု
::hyywu::ယျွှု
::hrywu::ရျွှု
::hlywu::လျွှု
::hLywu::ဠျွှု
::hwywu::ဝျွှု
::hhywu::ဟျွှု
::hsywu::သျွှု
::hSywu::ဿျွှု

::hkywuu::ကျွှူ
::hkhywuu::ချွှူ
::hgywuu::ဂျွှူ
::hghywuu::ဃျွှူ
::hngywuu::ငျွှူ
::hcywuu::စျွှူ
::hchywuu::ဆျွှူ
::hjywuu::ဇျွှူ
::hjhywuu::ဈျွှူ
::hnyywuu::ဉျွှူ
::hNyywuu::ညျွှူ
::hTywuu::ဋျွှူ
::hThywuu::ဌျွှူ
::hDywuu::ဍျွှူ
::hDhywuu::ဎျွှူ
::hNywuu::ဏျွှူ
::htywuu::တျွှူ
::hthywuu::ထျွှူ
::hdywuu::ဒျွှူ
::hdhywuu::ဓျွှူ
::hnywuu::နျွှူ
::hpywuu::ပျွှူ
::hphywuu::ဖျွှူ
::hbywuu::ဗျွှူ
::hbhywuu::ဘျွှူ
::hmywuu::မျွှူ
::hyywuu::ယျွှူ
::hrywuu::ရျွှူ
::hlywuu::လျွှူ
::hLywuu::ဠျွှူ
::hwywuu::ဝျွှူ
::hhywuu::ဟျွှူ
::hsywuu::သျွှူ
::hSywuu::ဿျွှူ

::hkywe::ကျွှေ
::hkhywe::ချွှေ
::hgywe::ဂျွှေ
::hghywe::ဃျွှေ
::hngywe::ငျွှေ
::hcywe::စျွှေ
::hchywe::ဆျွှေ
::hjywe::ဇျွှေ
::hjhywe::ဈျွှေ
::hnyywe::ဉျွှေ
::hNyywe::ညျွှေ
::hTywe::ဋျွှေ
::hThywe::ဌျွှေ
::hDywe::ဍျွှေ
::hDhywe::ဎျွှေ
::hNywe::ဏျွှေ
::htywe::တျွှေ
::hthywe::ထျွှေ
::hdywe::ဒျွှေ
::hdhywe::ဓျွှေ
::hnywe::နျွှေ
::hpywe::ပျွှေ
::hphywe::ဖျွှေ
::hbywe::ဗျွှေ
::hbhywe::ဘျွှေ
::hmywe::မျွှေ
::hyywe::ယျွှေ
::hrywe::ရျွှေ
::hlywe::လျွှေ
::hLywe::ဠျွှေ
::hwywe::ဝျွှေ
::hhywe::ဟျွှေ
::hsywe::သျွှေ
::hSywe::ဿျွှေ

::hkywau::ကျွှါ်
::hkhywau::ချွှါ်
::hgywau::ဂျွှါ်
::hghywau::ဃျွှါ်
::hngywau::ငျွှါ်
::hcywau::စျွှါ်
::hchywau::ဆျွှါ်
::hjywau::ဇျွှါ်
::hjhywau::ဈျွှါ်
::hnyywau::ဉျွှါ်
::hNyywau::ညျွှါ်
::hTywau::ဋျွှါ်
::hThywau::ဌျွှါ်
::hDywau::ဍျွှါ်
::hDhywau::ဎျွှါ်
::hNywau::ဏျွှါ်
::htywau::တျွှါ်
::hthywau::ထျွှါ်
::hdywau::ဒျွှါ်
::hdhywau::ဓျွှါ်
::hnywau::နျွှါ်
::hpywau::ပျွှါ်
::hphywau::ဖျွှါ်
::hbywau::ဗျွှါ်
::hbhywau::ဘျွှါ်
::hmywau::မျွှါ်
::hyywau::ယျွှါ်
::hrywau::ရျွှါ်
::hlywau::လျွှါ်
::hLywau::ဠျွှါ်
::hwywau::ဝျွှါ်
::hhywau::ဟျွှါ်
::hsywau::သျွှါ်
::hSywau::ဿျွှါ်

::hkywaw::ကျွှော
::hkhywaw::ချွှော
::hgywaw::ဂျွှော
::hghywaw::ဃျွှော
::hngywaw::ငျွှော
::hcywaw::စျွှော
::hchywaw::ဆျွှော
::hjywaw::ဇျွှော
::hjhywaw::ဈျွှော
::hnyywaw::ဉျွှော
::hNyywaw::ညျွှော
::hTywaw::ဋျွှော
::hThywaw::ဌျွှော
::hDywaw::ဍျွှော
::hDhywaw::ဎျွှော
::hNywaw::ဏျွှော
::htywaw::တျွှော
::hthywaw::ထျွှော
::hdywaw::ဒျွှော
::hdhywaw::ဓျွှော
::hnywaw::နျွှော
::hpywaw::ပျွှော
::hphywaw::ဖျွှော
::hbywaw::ဗျွှော
::hbhywaw::ဘျွှော
::hmywaw::မျွှော
::hyywaw::ယျွှော
::hrywaw::ရျွှော
::hlywaw::လျွှော
::hLywaw::ဠျွှော
::hwywaw::ဝျွှော
::hhywaw::ဟျွှော
::hsywaw::သျွှော
::hSywaw::ဿျွှော

::hkywaww::ကျွှော်
::hkhywaww::ချွှော်
::hgywaww::ဂျွှော်
::hghywaww::ဃျွှော်
::hngywaww::ငျွှော်
::hcywaww::စျွှော်
::hchywaww::ဆျွှော်
::hjywaww::ဇျွှော်
::hjhywaww::ဈျွှော်
::hnyywaww::ဉျွှော်
::hNyywaww::ညျွှော်
::hTywaww::ဋျွှော်
::hThywaww::ဌျွှော်
::hDywaww::ဍျွှော်
::hDhywaww::ဎျွှော်
::hNywaww::ဏျွှော်
::htywaww::တျွှော်
::hthywaww::ထျွှော်
::hdywaww::ဒျွှော်
::hdhywaww::ဓျွှော်
::hnywaww::နျွှော်
::hpywaww::ပျွှော်
::hphywaww::ဖျွှော်
::hbywaww::ဗျွှော်
::hbhywaww::ဘျွှော်
::hmywaww::မျွှော်
::hyywaww::ယျွှော်
::hrywaww::ရျွှော်
::hlywaww::လျွှော်
::hLywaww::ဠျွှော်
::hwywaww::ဝျွှော်
::hhywaww::ဟျွှော်
::hsywaww::သျွှော်
::hSywaww::ဿျွှော်

::hkywai::ကျွှဲ
::hkhywai::ချွှဲ
::hgywai::ဂျွှဲ
::hghywai::ဃျွှဲ
::hngywai::ငျွှဲ
::hcywai::စျွှဲ
::hchywai::ဆျွှဲ
::hjywai::ဇျွှဲ
::hjhywai::ဈျွှဲ
::hnyywai::ဉျွှဲ
::hNyywai::ညျွှဲ
::hTywai::ဋျွှဲ
::hThywai::ဌျွှဲ
::hDywai::ဍျွှဲ
::hDhywai::ဎျွှဲ
::hNywai::ဏျွှဲ
::htywai::တျွှဲ
::hthywai::ထျွှဲ
::hdywai::ဒျွှဲ
::hdhywai::ဓျွှဲ
::hnywai::နျွှဲ
::hpywai::ပျွှဲ
::hphywai::ဖျွှဲ
::hbywai::ဗျွှဲ
::hbhywai::ဘျွှဲ
::hmywai::မျွှဲ
::hyywai::ယျွှဲ
::hrywai::ရျွှဲ
::hlywai::လျွှဲ
::hLywai::ဠျွှဲ
::hwywai::ဝျွှဲ
::hhywai::ဟျွှဲ
::hsywai::သျွှဲ
::hSywai::ဿျွှဲ

::hkra::ကြှ
::hkhra::ခြှ
::hgra::ဂြှ
::hghra::ဃြှ
::hngra::ငြှ
::hcra::စြှ
::hchra::ဆြှ
::hjra::ဇြှ
::hjhra::ဈြှ
::hnyra::ဉြှ
::hNyra::ညြှ
::hTra::ဋြှ
::hThra::ဌြှ
::hDra::ဍြှ
::hDhra::ဎြှ
::hNra::ဏြှ
::htra::တြှ
::hthra::ထြှ
::hdra::ဒြှ
::hdhra::ဓြှ
::hnra::နြှ
::hpra::ပြှ
::hphra::ဖြှ
::hbra::ဗြှ
::hbhra::ဘြှ
::hmra::မြှ
::hyra::ယြှ
::hrra::ရြှ
::hlra::လြှ
::hLra::ဠြှ
::hwra::ဝြှ
::hhra::ဟြှ
::hsra::သြှ
::hSra::ဿြှ

::hkraa::ကြှါ
::hkhraa::ခြှါ
::hgraa::ဂြှါ
::hghraa::ဃြှါ
::hngraa::ငြှါ
::hcraa::စြှါ
::hchraa::ဆြှါ
::hjraa::ဇြှါ
::hjhraa::ဈြှါ
::hnyraa::ဉြှါ
::hNyraa::ညြှါ
::hTraa::ဋြှါ
::hThraa::ဌြှါ
::hDraa::ဍြှါ
::hDhraa::ဎြှါ
::hNraa::ဏြှါ
::htraa::တြှါ
::hthraa::ထြှါ
::hdraa::ဒြှါ
::hdhraa::ဓြှါ
::hnraa::နြှါ
::hpraa::ပြှါ
::hphraa::ဖြှါ
::hbraa::ဗြှါ
::hbhraa::ဘြှါ
::hmraa::မြှါ
::hyraa::ယြှါ
::hrraa::ရြှါ
::hlraa::လြှါ
::hLraa::ဠြှါ
::hwraa::ဝြှါ
::hhraa::ဟြှါ
::hsraa::သြှါ
::hSraa::ဿြှါ

::hkrar::ကြှော
::hkhrar::ခြှော
::hgrar::ဂြှော
::hghrar::ဃြှော
::hngrar::ငြှော
::hcrar::စြှော
::hchrar::ဆြှော
::hjrar::ဇြှော
::hjhrar::ဈြှော
::hnyrar::ဉြှော
::hNyrar::ညြှော
::hTrar::ဋြှော
::hThrar::ဌြှော
::hDrar::ဍြှော
::hDhrar::ဎြှော
::hNrar::ဏြှော
::htrar::တြှော
::hthrar::ထြှော
::hdrar::ဒြှော
::hdhrar::ဓြှော
::hnrar::နြှော
::hprar::ပြှော
::hphrar::ဖြှော
::hbrar::ဗြှော
::hbhrar::ဘြှော
::hmrar::မြှော
::hyrar::ယြှော
::hrrar::ရြှော
::hlrar::လြှော
::hLrar::ဠြှော
::hwrar::ဝြှော
::hhrar::ဟြှော
::hsrar::သြှော
::hSrar::ဿြှော

::hkri::ကြှိ
::hkhri::ခြှိ
::hgri::ဂြှိ
::hghri::ဃြှိ
::hngri::ငြှိ
::hcri::စြှိ
::hchri::ဆြှိ
::hjri::ဇြှိ
::hjhri::ဈြှိ
::hnyri::ဉြှိ
::hNyri::ညြှိ
::hTri::ဋြှိ
::hThri::ဌြှိ
::hDri::ဍြှိ
::hDhri::ဎြှိ
::hNri::ဏြှိ
::htri::တြှိ
::hthri::ထြှိ
::hdri::ဒြှိ
::hdhri::ဓြှိ
::hnri::နြှိ
::hpri::ပြှိ
::hphri::ဖြှိ
::hbri::ဗြှိ
::hbhri::ဘြှိ
::hmri::မြှိ
::hyri::ယြှိ
::hrri::ရြှိ
::hlri::လြှိ
::hLri::ဠြှိ
::hwri::ဝြှိ
::hhri::ဟြှိ
::hsri::သြှိ
::hSri::ဿြှိ

::hkrui::ကြှို
::hkhrui::ခြှို
::hgrui::ဂြှို
::hghrui::ဃြှို
::hngrui::ငြှို
::hcrui::စြှို
::hchrui::ဆြှို
::hjrui::ဇြှို
::hjhrui::ဈြှို
::hnyrui::ဉြှို
::hNyrui::ညြှို
::hTrui::ဋြှို
::hThrui::ဌြှို
::hDrui::ဍြှို
::hDhrui::ဎြှို
::hNrui::ဏြှို
::htrui::တြှို
::hthrui::ထြှို
::hdrui::ဒြှို
::hdhrui::ဓြှို
::hnrui::နြှို
::hprui::ပြှို
::hphrui::ဖြှို
::hbrui::ဗြှို
::hbhrui::ဘြှို
::hmrui::မြှို
::hyrui::ယြှို
::hrrui::ရြှို
::hlrui::လြှို
::hLrui::ဠြှို
::hwrui::ဝြှို
::hhrui::ဟြှို
::hsrui::သြှို
::hSrui::ဿြှို

::hkrii::ကြှီ
::hkhrii::ခြှီ
::hgrii::ဂြှီ
::hghrii::ဃြှီ
::hngrii::ငြှီ
::hcrii::စြှီ
::hchrii::ဆြှီ
::hjrii::ဇြှီ
::hjhrii::ဈြှီ
::hnyrii::ဉြှီ
::hNyrii::ညြှီ
::hTrii::ဋြှီ
::hThrii::ဌြှီ
::hDrii::ဍြှီ
::hDhrii::ဎြှီ
::hNrii::ဏြှီ
::htrii::တြှီ
::hthrii::ထြှီ
::hdrii::ဒြှီ
::hdhrii::ဓြှီ
::hnrii::နြှီ
::hprii::ပြှီ
::hphrii::ဖြှီ
::hbrii::ဗြှီ
::hbhrii::ဘြှီ
::hmrii::မြှီ
::hyrii::ယြှီ
::hrrii::ရြှီ
::hlrii::လြှီ
::hLrii::ဠြှီ
::hwrii::ဝြှီ
::hhrii::ဟြှီ
::hsrii::သြှီ
::hSrii::ဿြှီ

::hkru::ကြှု
::hkhru::ခြှု
::hgru::ဂြှု
::hghru::ဃြှု
::hngru::ငြှု
::hcru::စြှု
::hchru::ဆြှု
::hjru::ဇြှု
::hjhru::ဈြှု
::hnyru::ဉြှု
::hNyru::ညြှု
::hTru::ဋြှု
::hThru::ဌြှု
::hDru::ဍြှု
::hDhru::ဎြှု
::hNru::ဏြှု
::htru::တြှု
::hthru::ထြှု
::hdru::ဒြှု
::hdhru::ဓြှု
::hnru::နြှု
::hpru::ပြှု
::hphru::ဖြှု
::hbru::ဗြှု
::hbhru::ဘြှု
::hmru::မြှု
::hyru::ယြှု
::hrru::ရြှု
::hlru::လြှု
::hLru::ဠြှု
::hwru::ဝြှု
::hhru::ဟြှု
::hsru::သြှု
::hSru::ဿြှု

::hkruu::ကြှူ
::hkhruu::ခြှူ
::hgruu::ဂြှူ
::hghruu::ဃြှူ
::hngruu::ငြှူ
::hcruu::စြှူ
::hchruu::ဆြှူ
::hjruu::ဇြှူ
::hjhruu::ဈြှူ
::hnyruu::ဉြှူ
::hNyruu::ညြှူ
::hTruu::ဋြှူ
::hThruu::ဌြှူ
::hDruu::ဍြှူ
::hDhruu::ဎြှူ
::hNruu::ဏြှူ
::htruu::တြှူ
::hthruu::ထြှူ
::hdruu::ဒြှူ
::hdhruu::ဓြှူ
::hnruu::နြှူ
::hpruu::ပြှူ
::hphruu::ဖြှူ
::hbruu::ဗြှူ
::hbhruu::ဘြှူ
::hmruu::မြှူ
::hyruu::ယြှူ
::hrruu::ရြှူ
::hlruu::လြှူ
::hLruu::ဠြှူ
::hwruu::ဝြှူ
::hhruu::ဟြှူ
::hsruu::သြှူ
::hSruu::ဿြှူ

::hkre::ကြှေ
::hkhre::ခြှေ
::hgre::ဂြှေ
::hghre::ဃြှေ
::hngre::ငြှေ
::hcre::စြှေ
::hchre::ဆြှေ
::hjre::ဇြှေ
::hjhre::ဈြှေ
::hnyre::ဉြှေ
::hNyre::ညြှေ
::hTre::ဋြှေ
::hThre::ဌြှေ
::hDre::ဍြှေ
::hDhre::ဎြှေ
::hNre::ဏြှေ
::htre::တြှေ
::hthre::ထြှေ
::hdre::ဒြှေ
::hdhre::ဓြှေ
::hnre::နြှေ
::hpre::ပြှေ
::hphre::ဖြှေ
::hbre::ဗြှေ
::hbhre::ဘြှေ
::hmre::မြှေ
::hyre::ယြှေ
::hrre::ရြှေ
::hlre::လြှေ
::hLre::ဠြှေ
::hwre::ဝြှေ
::hhre::ဟြှေ
::hsre::သြှေ
::hSre::ဿြှေ

::hkrau::ကြှါ်
::hkhrau::ခြှါ်
::hgrau::ဂြှါ်
::hghrau::ဃြှါ်
::hngrau::ငြှါ်
::hcrau::စြှါ်
::hchrau::ဆြှါ်
::hjrau::ဇြှါ်
::hjhrau::ဈြှါ်
::hnyrau::ဉြှါ်
::hNyrau::ညြှါ်
::hTrau::ဋြှါ်
::hThrau::ဌြှါ်
::hDrau::ဍြှါ်
::hDhrau::ဎြှါ်
::hNrau::ဏြှါ်
::htrau::တြှါ်
::hthrau::ထြှါ်
::hdrau::ဒြှါ်
::hdhrau::ဓြှါ်
::hnrau::နြှါ်
::hprau::ပြှါ်
::hphrau::ဖြှါ်
::hbrau::ဗြှါ်
::hbhrau::ဘြှါ်
::hmrau::မြှါ်
::hyrau::ယြှါ်
::hrrau::ရြှါ်
::hlrau::လြှါ်
::hLrau::ဠြှါ်
::hwrau::ဝြှါ်
::hhrau::ဟြှါ်
::hsrau::သြှါ်
::hSrau::ဿြှါ်

::hkraw::ကြှော
::hkhraw::ခြှော
::hgraw::ဂြှော
::hghraw::ဃြှော
::hngraw::ငြှော
::hcraw::စြှော
::hchraw::ဆြှော
::hjraw::ဇြှော
::hjhraw::ဈြှော
::hnyraw::ဉြှော
::hNyraw::ညြှော
::hTraw::ဋြှော
::hThraw::ဌြှော
::hDraw::ဍြှော
::hDhraw::ဎြှော
::hNraw::ဏြှော
::htraw::တြှော
::hthraw::ထြှော
::hdraw::ဒြှော
::hdhraw::ဓြှော
::hnraw::နြှော
::hpraw::ပြှော
::hphraw::ဖြှော
::hbraw::ဗြှော
::hbhraw::ဘြှော
::hmraw::မြှော
::hyraw::ယြှော
::hrraw::ရြှော
::hlraw::လြှော
::hLraw::ဠြှော
::hwraw::ဝြှော
::hhraw::ဟြှော
::hsraw::သြှော
::hSraw::ဿြှော

::hkraww::ကြှော်
::hkhraww::ခြှော်
::hgraww::ဂြှော်
::hghraww::ဃြှော်
::hngraww::ငြှော်
::hcraww::စြှော်
::hchraww::ဆြှော်
::hjraww::ဇြှော်
::hjhraww::ဈြှော်
::hnyraww::ဉြှော်
::hNyraww::ညြှော်
::hTraww::ဋြှော်
::hThraww::ဌြှော်
::hDraww::ဍြှော်
::hDhraww::ဎြှော်
::hNraww::ဏြှော်
::htraww::တြှော်
::hthraww::ထြှော်
::hdraww::ဒြှော်
::hdhraww::ဓြှော်
::hnraww::နြှော်
::hpraww::ပြှော်
::hphraww::ဖြှော်
::hbraww::ဗြှော်
::hbhraww::ဘြှော်
::hmraww::မြှော်
::hyraww::ယြှော်
::hrraww::ရြှော်
::hlraww::လြှော်
::hLraww::ဠြှော်
::hwraww::ဝြှော်
::hhraww::ဟြှော်
::hsraww::သြှော်
::hSraww::ဿြှော်

::hkrai::ကြှဲ
::hkhrai::ခြှဲ
::hgrai::ဂြှဲ
::hghrai::ဃြှဲ
::hngrai::ငြှဲ
::hcrai::စြှဲ
::hchrai::ဆြှဲ
::hjrai::ဇြှဲ
::hjhrai::ဈြှဲ
::hnyrai::ဉြှဲ
::hNyrai::ညြှဲ
::hTrai::ဋြှဲ
::hThrai::ဌြှဲ
::hDrai::ဍြှဲ
::hDhrai::ဎြှဲ
::hNrai::ဏြှဲ
::htrai::တြှဲ
::hthrai::ထြှဲ
::hdrai::ဒြှဲ
::hdhrai::ဓြှဲ
::hnrai::နြှဲ
::hprai::ပြှဲ
::hphrai::ဖြှဲ
::hbrai::ဗြှဲ
::hbhrai::ဘြှဲ
::hmrai::မြှဲ
::hyrai::ယြှဲ
::hrrai::ရြှဲ
::hlrai::လြှဲ
::hLrai::ဠြှဲ
::hwrai::ဝြှဲ
::hhrai::ဟြှဲ
::hsrai::သြှဲ
::hSrai::ဿြှဲ

::krwa::ကြွ
::khrwa::ခြွ
::grwa::ဂြွ
::ghrwa::ဃြွ
::ngrwa::ငြွ
::crwa::စြွ
::chrwa::ဆြွ
::jrwa::ဇြွ
::jhrwa::ဈြွ
::nyrwa::ဉြွ
::Nyrwa::ညြွ
::Trwa::ဋြွ
::Thrwa::ဌြွ
::Drwa::ဍြွ
::Dhrwa::ဎြွ
::Nrwa::ဏြွ
::trwa::တြွ
::thrwa::ထြွ
::drwa::ဒြွ
::dhrwa::ဓြွ
::nrwa::နြွ
::prwa::ပြွ
::phrwa::ဖြွ
::brwa::ဗြွ
::bhrwa::ဘြွ
::mrwa::မြွ
::yrwa::ယြွ
::rrwa::ရြွ
::lrwa::လြွ
::Lrwa::ဠြွ
::wrwa::ဝြွ
::hrwa::ဟြွ
::srwa::သြွ
::Srwa::ဿြွ

::krwaa::ကြွါ
::khrwaa::ခြွါ
::grwaa::ဂြွါ
::ghrwaa::ဃြွါ
::ngrwaa::ငြွါ
::crwaa::စြွါ
::chrwaa::ဆြွါ
::jrwaa::ဇြွါ
::jhrwaa::ဈြွါ
::nyrwaa::ဉြွါ
::Nyrwaa::ညြွါ
::Trwaa::ဋြွါ
::Thrwaa::ဌြွါ
::Drwaa::ဍြွါ
::Dhrwaa::ဎြွါ
::Nrwaa::ဏြွါ
::trwaa::တြွါ
::thrwaa::ထြွါ
::drwaa::ဒြွါ
::dhrwaa::ဓြွါ
::nrwaa::နြွါ
::prwaa::ပြွါ
::phrwaa::ဖြွါ
::brwaa::ဗြွါ
::bhrwaa::ဘြွါ
::mrwaa::မြွါ
::yrwaa::ယြွါ
::rrwaa::ရြွါ
::lrwaa::လြွါ
::Lrwaa::ဠြွါ
::wrwaa::ဝြွါ
::hrwaa::ဟြွါ
::srwaa::သြွါ
::Srwaa::ဿြွါ

::krwar::ကြွော
::khrwar::ခြွော
::grwar::ဂြွော
::ghrwar::ဃြွော
::ngrwar::ငြွော
::crwar::စြွော
::chrwar::ဆြွော
::jrwar::ဇြွော
::jhrwar::ဈြွော
::nyrwar::ဉြွော
::Nyrwar::ညြွော
::Trwar::ဋြွော
::Thrwar::ဌြွော
::Drwar::ဍြွော
::Dhrwar::ဎြွော
::Nrwar::ဏြွော
::trwar::တြွော
::thrwar::ထြွော
::drwar::ဒြွော
::dhrwar::ဓြွော
::nrwar::နြွော
::prwar::ပြွော
::phrwar::ဖြွော
::brwar::ဗြွော
::bhrwar::ဘြွော
::mrwar::မြွော
::yrwar::ယြွော
::rrwar::ရြွော
::lrwar::လြွော
::Lrwar::ဠြွော
::wrwar::ဝြွော
::hrwar::ဟြွော
::srwar::သြွော
::Srwar::ဿြွော

::krwi::ကြွိ
::khrwi::ခြွိ
::grwi::ဂြွိ
::ghrwi::ဃြွိ
::ngrwi::ငြွိ
::crwi::စြွိ
::chrwi::ဆြွိ
::jrwi::ဇြွိ
::jhrwi::ဈြွိ
::nyrwi::ဉြွိ
::Nyrwi::ညြွိ
::Trwi::ဋြွိ
::Thrwi::ဌြွိ
::Drwi::ဍြွိ
::Dhrwi::ဎြွိ
::Nrwi::ဏြွိ
::trwi::တြွိ
::thrwi::ထြွိ
::drwi::ဒြွိ
::dhrwi::ဓြွိ
::nrwi::နြွိ
::prwi::ပြွိ
::phrwi::ဖြွိ
::brwi::ဗြွိ
::bhrwi::ဘြွိ
::mrwi::မြွိ
::yrwi::ယြွိ
::rrwi::ရြွိ
::lrwi::လြွိ
::Lrwi::ဠြွိ
::wrwi::ဝြွိ
::hrwi::ဟြွိ
::srwi::သြွိ
::Srwi::ဿြွိ

::krwui::ကြွို
::khrwui::ခြွို
::grwui::ဂြွို
::ghrwui::ဃြွို
::ngrwui::ငြွို
::crwui::စြွို
::chrwui::ဆြွို
::jrwui::ဇြွို
::jhrwui::ဈြွို
::nyrwui::ဉြွို
::Nyrwui::ညြွို
::Trwui::ဋြွို
::Thrwui::ဌြွို
::Drwui::ဍြွို
::Dhrwui::ဎြွို
::Nrwui::ဏြွို
::trwui::တြွို
::thrwui::ထြွို
::drwui::ဒြွို
::dhrwui::ဓြွို
::nrwui::နြွို
::prwui::ပြွို
::phrwui::ဖြွို
::brwui::ဗြွို
::bhrwui::ဘြွို
::mrwui::မြွို
::yrwui::ယြွို
::rrwui::ရြွို
::lrwui::လြွို
::Lrwui::ဠြွို
::wrwui::ဝြွို
::hrwui::ဟြွို
::srwui::သြွို
::Srwui::ဿြွို

::krwii::ကြွီ
::khrwii::ခြွီ
::grwii::ဂြွီ
::ghrwii::ဃြွီ
::ngrwii::ငြွီ
::crwii::စြွီ
::chrwii::ဆြွီ
::jrwii::ဇြွီ
::jhrwii::ဈြွီ
::nyrwii::ဉြွီ
::Nyrwii::ညြွီ
::Trwii::ဋြွီ
::Thrwii::ဌြွီ
::Drwii::ဍြွီ
::Dhrwii::ဎြွီ
::Nrwii::ဏြွီ
::trwii::တြွီ
::thrwii::ထြွီ
::drwii::ဒြွီ
::dhrwii::ဓြွီ
::nrwii::နြွီ
::prwii::ပြွီ
::phrwii::ဖြွီ
::brwii::ဗြွီ
::bhrwii::ဘြွီ
::mrwii::မြွီ
::yrwii::ယြွီ
::rrwii::ရြွီ
::lrwii::လြွီ
::Lrwii::ဠြွီ
::wrwii::ဝြွီ
::hrwii::ဟြွီ
::srwii::သြွီ
::Srwii::ဿြွီ

::krwu::ကြွု
::khrwu::ခြွု
::grwu::ဂြွု
::ghrwu::ဃြွု
::ngrwu::ငြွု
::crwu::စြွု
::chrwu::ဆြွု
::jrwu::ဇြွု
::jhrwu::ဈြွု
::nyrwu::ဉြွု
::Nyrwu::ညြွု
::Trwu::ဋြွု
::Thrwu::ဌြွု
::Drwu::ဍြွု
::Dhrwu::ဎြွု
::Nrwu::ဏြွု
::trwu::တြွု
::thrwu::ထြွု
::drwu::ဒြွု
::dhrwu::ဓြွု
::nrwu::နြွု
::prwu::ပြွု
::phrwu::ဖြွု
::brwu::ဗြွု
::bhrwu::ဘြွု
::mrwu::မြွု
::yrwu::ယြွု
::rrwu::ရြွု
::lrwu::လြွု
::Lrwu::ဠြွု
::wrwu::ဝြွု
::hrwu::ဟြွု
::srwu::သြွု
::Srwu::ဿြွု

::krwuu::ကြွူ
::khrwuu::ခြွူ
::grwuu::ဂြွူ
::ghrwuu::ဃြွူ
::ngrwuu::ငြွူ
::crwuu::စြွူ
::chrwuu::ဆြွူ
::jrwuu::ဇြွူ
::jhrwuu::ဈြွူ
::nyrwuu::ဉြွူ
::Nyrwuu::ညြွူ
::Trwuu::ဋြွူ
::Thrwuu::ဌြွူ
::Drwuu::ဍြွူ
::Dhrwuu::ဎြွူ
::Nrwuu::ဏြွူ
::trwuu::တြွူ
::thrwuu::ထြွူ
::drwuu::ဒြွူ
::dhrwuu::ဓြွူ
::nrwuu::နြွူ
::prwuu::ပြွူ
::phrwuu::ဖြွူ
::brwuu::ဗြွူ
::bhrwuu::ဘြွူ
::mrwuu::မြွူ
::yrwuu::ယြွူ
::rrwuu::ရြွူ
::lrwuu::လြွူ
::Lrwuu::ဠြွူ
::wrwuu::ဝြွူ
::hrwuu::ဟြွူ
::srwuu::သြွူ
::Srwuu::ဿြွူ

::krwe::ကြွေ
::khrwe::ခြွေ
::grwe::ဂြွေ
::ghrwe::ဃြွေ
::ngrwe::ငြွေ
::crwe::စြွေ
::chrwe::ဆြွေ
::jrwe::ဇြွေ
::jhrwe::ဈြွေ
::nyrwe::ဉြွေ
::Nyrwe::ညြွေ
::Trwe::ဋြွေ
::Thrwe::ဌြွေ
::Drwe::ဍြွေ
::Dhrwe::ဎြွေ
::Nrwe::ဏြွေ
::trwe::တြွေ
::thrwe::ထြွေ
::drwe::ဒြွေ
::dhrwe::ဓြွေ
::nrwe::နြွေ
::prwe::ပြွေ
::phrwe::ဖြွေ
::brwe::ဗြွေ
::bhrwe::ဘြွေ
::mrwe::မြွေ
::yrwe::ယြွေ
::rrwe::ရြွေ
::lrwe::လြွေ
::Lrwe::ဠြွေ
::wrwe::ဝြွေ
::hrwe::ဟြွေ
::srwe::သြွေ
::Srwe::ဿြွေ

::krwau::ကြွါ်
::khrwau::ခြွါ်
::grwau::ဂြွါ်
::ghrwau::ဃြွါ်
::ngrwau::ငြွါ်
::crwau::စြွါ်
::chrwau::ဆြွါ်
::jrwau::ဇြွါ်
::jhrwau::ဈြွါ်
::nyrwau::ဉြွါ်
::Nyrwau::ညြွါ်
::Trwau::ဋြွါ်
::Thrwau::ဌြွါ်
::Drwau::ဍြွါ်
::Dhrwau::ဎြွါ်
::Nrwau::ဏြွါ်
::trwau::တြွါ်
::thrwau::ထြွါ်
::drwau::ဒြွါ်
::dhrwau::ဓြွါ်
::nrwau::နြွါ်
::prwau::ပြွါ်
::phrwau::ဖြွါ်
::brwau::ဗြွါ်
::bhrwau::ဘြွါ်
::mrwau::မြွါ်
::yrwau::ယြွါ်
::rrwau::ရြွါ်
::lrwau::လြွါ်
::Lrwau::ဠြွါ်
::wrwau::ဝြွါ်
::hrwau::ဟြွါ်
::srwau::သြွါ်
::Srwau::ဿြွါ်

::krwaw::ကြွော
::khrwaw::ခြွော
::grwaw::ဂြွော
::ghrwaw::ဃြွော
::ngrwaw::ငြွော
::crwaw::စြွော
::chrwaw::ဆြွော
::jrwaw::ဇြွော
::jhrwaw::ဈြွော
::nyrwaw::ဉြွော
::Nyrwaw::ညြွော
::Trwaw::ဋြွော
::Thrwaw::ဌြွော
::Drwaw::ဍြွော
::Dhrwaw::ဎြွော
::Nrwaw::ဏြွော
::trwaw::တြွော
::thrwaw::ထြွော
::drwaw::ဒြွော
::dhrwaw::ဓြွော
::nrwaw::နြွော
::prwaw::ပြွော
::phrwaw::ဖြွော
::brwaw::ဗြွော
::bhrwaw::ဘြွော
::mrwaw::မြွော
::yrwaw::ယြွော
::rrwaw::ရြွော
::lrwaw::လြွော
::Lrwaw::ဠြွော
::wrwaw::ဝြွော
::hrwaw::ဟြွော
::srwaw::သြွော
::Srwaw::ဿြွော

::krwaww::ကြွော်
::khrwaww::ခြွော်
::grwaww::ဂြွော်
::ghrwaww::ဃြွော်
::ngrwaww::ငြွော်
::crwaww::စြွော်
::chrwaww::ဆြွော်
::jrwaww::ဇြွော်
::jhrwaww::ဈြွော်
::nyrwaww::ဉြွော်
::Nyrwaww::ညြွော်
::Trwaww::ဋြွော်
::Thrwaww::ဌြွော်
::Drwaww::ဍြွော်
::Dhrwaww::ဎြွော်
::Nrwaww::ဏြွော်
::trwaww::တြွော်
::thrwaww::ထြွော်
::drwaww::ဒြွော်
::dhrwaww::ဓြွော်
::nrwaww::နြွော်
::prwaww::ပြွော်
::phrwaww::ဖြွော်
::brwaww::ဗြွော်
::bhrwaww::ဘြွော်
::mrwaww::မြွော်
::yrwaww::ယြွော်
::rrwaww::ရြွော်
::lrwaww::လြွော်
::Lrwaww::ဠြွော်
::wrwaww::ဝြွော်
::hrwaww::ဟြွော်
::srwaww::သြွော်
::Srwaww::ဿြွော်

::krwai::ကြွဲ
::khrwai::ခြွဲ
::grwai::ဂြွဲ
::ghrwai::ဃြွဲ
::ngrwai::ငြွဲ
::crwai::စြွဲ
::chrwai::ဆြွဲ
::jrwai::ဇြွဲ
::jhrwai::ဈြွဲ
::nyrwai::ဉြွဲ
::Nyrwai::ညြွဲ
::Trwai::ဋြွဲ
::Thrwai::ဌြွဲ
::Drwai::ဍြွဲ
::Dhrwai::ဎြွဲ
::Nrwai::ဏြွဲ
::trwai::တြွဲ
::thrwai::ထြွဲ
::drwai::ဒြွဲ
::dhrwai::ဓြွဲ
::nrwai::နြွဲ
::prwai::ပြွဲ
::phrwai::ဖြွဲ
::brwai::ဗြွဲ
::bhrwai::ဘြွဲ
::mrwai::မြွဲ
::yrwai::ယြွဲ
::rrwai::ရြွဲ
::lrwai::လြွဲ
::Lrwai::ဠြွဲ
::wrwai::ဝြွဲ
::hrwai::ဟြွဲ
::srwai::သြွဲ
::Srwai::ဿြွဲ

::hkrwa::ကြွှ
::hkhrwa::ခြွှ
::hgrwa::ဂြွှ
::hghrwa::ဃြွှ
::hngrwa::ငြွှ
::hcrwa::စြွှ
::hchrwa::ဆြွှ
::hjrwa::ဇြွှ
::hjhrwa::ဈြွှ
::hnyrwa::ဉြွှ
::hNyrwa::ညြွှ
::hTrwa::ဋြွှ
::hThrwa::ဌြွှ
::hDrwa::ဍြွှ
::hDhrwa::ဎြွှ
::hNrwa::ဏြွှ
::htrwa::တြွှ
::hthrwa::ထြွှ
::hdrwa::ဒြွှ
::hdhrwa::ဓြွှ
::hnrwa::နြွှ
::hprwa::ပြွှ
::hphrwa::ဖြွှ
::hbrwa::ဗြွှ
::hbhrwa::ဘြွှ
::hmrwa::မြွှ
::hyrwa::ယြွှ
::hrrwa::ရြွှ
::hlrwa::လြွှ
::hLrwa::ဠြွှ
::hwrwa::ဝြွှ
::hhrwa::ဟြွှ
::hsrwa::သြွှ
::hSrwa::ဿြွှ

::hkrwaa::ကြွှါ
::hkhrwaa::ခြွှါ
::hgrwaa::ဂြွှါ
::hghrwaa::ဃြွှါ
::hngrwaa::ငြွှါ
::hcrwaa::စြွှါ
::hchrwaa::ဆြွှါ
::hjrwaa::ဇြွှါ
::hjhrwaa::ဈြွှါ
::hnyrwaa::ဉြွှါ
::hNyrwaa::ညြွှါ
::hTrwaa::ဋြွှါ
::hThrwaa::ဌြွှါ
::hDrwaa::ဍြွှါ
::hDhrwaa::ဎြွှါ
::hNrwaa::ဏြွှါ
::htrwaa::တြွှါ
::hthrwaa::ထြွှါ
::hdrwaa::ဒြွှါ
::hdhrwaa::ဓြွှါ
::hnrwaa::နြွှါ
::hprwaa::ပြွှါ
::hphrwaa::ဖြွှါ
::hbrwaa::ဗြွှါ
::hbhrwaa::ဘြွှါ
::hmrwaa::မြွှါ
::hyrwaa::ယြွှါ
::hrrwaa::ရြွှါ
::hlrwaa::လြွှါ
::hLrwaa::ဠြွှါ
::hwrwaa::ဝြွှါ
::hhrwaa::ဟြွှါ
::hsrwaa::သြွှါ
::hSrwaa::ဿြွှါ

::hkrwar::ကြွှော
::hkhrwar::ခြွှော
::hgrwar::ဂြွှော
::hghrwar::ဃြွှော
::hngrwar::ငြွှော
::hcrwar::စြွှော
::hchrwar::ဆြွှော
::hjrwar::ဇြွှော
::hjhrwar::ဈြွှော
::hnyrwar::ဉြွှော
::hNyrwar::ညြွှော
::hTrwar::ဋြွှော
::hThrwar::ဌြွှော
::hDrwar::ဍြွှော
::hDhrwar::ဎြွှော
::hNrwar::ဏြွှော
::htrwar::တြွှော
::hthrwar::ထြွှော
::hdrwar::ဒြွှော
::hdhrwar::ဓြွှော
::hnrwar::နြွှော
::hprwar::ပြွှော
::hphrwar::ဖြွှော
::hbrwar::ဗြွှော
::hbhrwar::ဘြွှော
::hmrwar::မြွှော
::hyrwar::ယြွှော
::hrrwar::ရြွှော
::hlrwar::လြွှော
::hLrwar::ဠြွှော
::hwrwar::ဝြွှော
::hhrwar::ဟြွှော
::hsrwar::သြွှော
::hSrwar::ဿြွှော

::hkrwi::ကြွှိ
::hkhrwi::ခြွှိ
::hgrwi::ဂြွှိ
::hghrwi::ဃြွှိ
::hngrwi::ငြွှိ
::hcrwi::စြွှိ
::hchrwi::ဆြွှိ
::hjrwi::ဇြွှိ
::hjhrwi::ဈြွှိ
::hnyrwi::ဉြွှိ
::hNyrwi::ညြွှိ
::hTrwi::ဋြွှိ
::hThrwi::ဌြွှိ
::hDrwi::ဍြွှိ
::hDhrwi::ဎြွှိ
::hNrwi::ဏြွှိ
::htrwi::တြွှိ
::hthrwi::ထြွှိ
::hdrwi::ဒြွှိ
::hdhrwi::ဓြွှိ
::hnrwi::နြွှိ
::hprwi::ပြွှိ
::hphrwi::ဖြွှိ
::hbrwi::ဗြွှိ
::hbhrwi::ဘြွှိ
::hmrwi::မြွှိ
::hyrwi::ယြွှိ
::hrrwi::ရြွှိ
::hlrwi::လြွှိ
::hLrwi::ဠြွှိ
::hwrwi::ဝြွှိ
::hhrwi::ဟြွှိ
::hsrwi::သြွှိ
::hSrwi::ဿြွှိ

::hkrwui::ကြွှို
::hkhrwui::ခြွှို
::hgrwui::ဂြွှို
::hghrwui::ဃြွှို
::hngrwui::ငြွှို
::hcrwui::စြွှို
::hchrwui::ဆြွှို
::hjrwui::ဇြွှို
::hjhrwui::ဈြွှို
::hnyrwui::ဉြွှို
::hNyrwui::ညြွှို
::hTrwui::ဋြွှို
::hThrwui::ဌြွှို
::hDrwui::ဍြွှို
::hDhrwui::ဎြွှို
::hNrwui::ဏြွှို
::htrwui::တြွှို
::hthrwui::ထြွှို
::hdrwui::ဒြွှို
::hdhrwui::ဓြွှို
::hnrwui::နြွှို
::hprwui::ပြွှို
::hphrwui::ဖြွှို
::hbrwui::ဗြွှို
::hbhrwui::ဘြွှို
::hmrwui::မြွှို
::hyrwui::ယြွှို
::hrrwui::ရြွှို
::hlrwui::လြွှို
::hLrwui::ဠြွှို
::hwrwui::ဝြွှို
::hhrwui::ဟြွှို
::hsrwui::သြွှို
::hSrwui::ဿြွှို

::hkrwii::ကြွှီ
::hkhrwii::ခြွှီ
::hgrwii::ဂြွှီ
::hghrwii::ဃြွှီ
::hngrwii::ငြွှီ
::hcrwii::စြွှီ
::hchrwii::ဆြွှီ
::hjrwii::ဇြွှီ
::hjhrwii::ဈြွှီ
::hnyrwii::ဉြွှီ
::hNyrwii::ညြွှီ
::hTrwii::ဋြွှီ
::hThrwii::ဌြွှီ
::hDrwii::ဍြွှီ
::hDhrwii::ဎြွှီ
::hNrwii::ဏြွှီ
::htrwii::တြွှီ
::hthrwii::ထြွှီ
::hdrwii::ဒြွှီ
::hdhrwii::ဓြွှီ
::hnrwii::နြွှီ
::hprwii::ပြွှီ
::hphrwii::ဖြွှီ
::hbrwii::ဗြွှီ
::hbhrwii::ဘြွှီ
::hmrwii::မြွှီ
::hyrwii::ယြွှီ
::hrrwii::ရြွှီ
::hlrwii::လြွှီ
::hLrwii::ဠြွှီ
::hwrwii::ဝြွှီ
::hhrwii::ဟြွှီ
::hsrwii::သြွှီ
::hSrwii::ဿြွှီ

::hkrwu::ကြွှု
::hkhrwu::ခြွှု
::hgrwu::ဂြွှု
::hghrwu::ဃြွှု
::hngrwu::ငြွှု
::hcrwu::စြွှု
::hchrwu::ဆြွှု
::hjrwu::ဇြွှု
::hjhrwu::ဈြွှု
::hnyrwu::ဉြွှု
::hNyrwu::ညြွှု
::hTrwu::ဋြွှု
::hThrwu::ဌြွှု
::hDrwu::ဍြွှု
::hDhrwu::ဎြွှု
::hNrwu::ဏြွှု
::htrwu::တြွှု
::hthrwu::ထြွှု
::hdrwu::ဒြွှု
::hdhrwu::ဓြွှု
::hnrwu::နြွှု
::hprwu::ပြွှု
::hphrwu::ဖြွှု
::hbrwu::ဗြွှု
::hbhrwu::ဘြွှု
::hmrwu::မြွှု
::hyrwu::ယြွှု
::hrrwu::ရြွှု
::hlrwu::လြွှု
::hLrwu::ဠြွှု
::hwrwu::ဝြွှု
::hhrwu::ဟြွှု
::hsrwu::သြွှု
::hSrwu::ဿြွှု

::hkrwuu::ကြွှူ
::hkhrwuu::ခြွှူ
::hgrwuu::ဂြွှူ
::hghrwuu::ဃြွှူ
::hngrwuu::ငြွှူ
::hcrwuu::စြွှူ
::hchrwuu::ဆြွှူ
::hjrwuu::ဇြွှူ
::hjhrwuu::ဈြွှူ
::hnyrwuu::ဉြွှူ
::hNyrwuu::ညြွှူ
::hTrwuu::ဋြွှူ
::hThrwuu::ဌြွှူ
::hDrwuu::ဍြွှူ
::hDhrwuu::ဎြွှူ
::hNrwuu::ဏြွှူ
::htrwuu::တြွှူ
::hthrwuu::ထြွှူ
::hdrwuu::ဒြွှူ
::hdhrwuu::ဓြွှူ
::hnrwuu::နြွှူ
::hprwuu::ပြွှူ
::hphrwuu::ဖြွှူ
::hbrwuu::ဗြွှူ
::hbhrwuu::ဘြွှူ
::hmrwuu::မြွှူ
::hyrwuu::ယြွှူ
::hrrwuu::ရြွှူ
::hlrwuu::လြွှူ
::hLrwuu::ဠြွှူ
::hwrwuu::ဝြွှူ
::hhrwuu::ဟြွှူ
::hsrwuu::သြွှူ
::hSrwuu::ဿြွှူ

::hkrwe::ကြွှေ
::hkhrwe::ခြွှေ
::hgrwe::ဂြွှေ
::hghrwe::ဃြွှေ
::hngrwe::ငြွှေ
::hcrwe::စြွှေ
::hchrwe::ဆြွှေ
::hjrwe::ဇြွှေ
::hjhrwe::ဈြွှေ
::hnyrwe::ဉြွှေ
::hNyrwe::ညြွှေ
::hTrwe::ဋြွှေ
::hThrwe::ဌြွှေ
::hDrwe::ဍြွှေ
::hDhrwe::ဎြွှေ
::hNrwe::ဏြွှေ
::htrwe::တြွှေ
::hthrwe::ထြွှေ
::hdrwe::ဒြွှေ
::hdhrwe::ဓြွှေ
::hnrwe::နြွှေ
::hprwe::ပြွှေ
::hphrwe::ဖြွှေ
::hbrwe::ဗြွှေ
::hbhrwe::ဘြွှေ
::hmrwe::မြွှေ
::hyrwe::ယြွှေ
::hrrwe::ရြွှေ
::hlrwe::လြွှေ
::hLrwe::ဠြွှေ
::hwrwe::ဝြွှေ
::hhrwe::ဟြွှေ
::hsrwe::သြွှေ
::hSrwe::ဿြွှေ

::hkrwau::ကြွှါ်
::hkhrwau::ခြွှါ်
::hgrwau::ဂြွှါ်
::hghrwau::ဃြွှါ်
::hngrwau::ငြွှါ်
::hcrwau::စြွှါ်
::hchrwau::ဆြွှါ်
::hjrwau::ဇြွှါ်
::hjhrwau::ဈြွှါ်
::hnyrwau::ဉြွှါ်
::hNyrwau::ညြွှါ်
::hTrwau::ဋြွှါ်
::hThrwau::ဌြွှါ်
::hDrwau::ဍြွှါ်
::hDhrwau::ဎြွှါ်
::hNrwau::ဏြွှါ်
::htrwau::တြွှါ်
::hthrwau::ထြွှါ်
::hdrwau::ဒြွှါ်
::hdhrwau::ဓြွှါ်
::hnrwau::နြွှါ်
::hprwau::ပြွှါ်
::hphrwau::ဖြွှါ်
::hbrwau::ဗြွှါ်
::hbhrwau::ဘြွှါ်
::hmrwau::မြွှါ်
::hyrwau::ယြွှါ်
::hrrwau::ရြွှါ်
::hlrwau::လြွှါ်
::hLrwau::ဠြွှါ်
::hwrwau::ဝြွှါ်
::hhrwau::ဟြွှါ်
::hsrwau::သြွှါ်
::hSrwau::ဿြွှါ်

::hkrwaw::ကြွှော
::hkhrwaw::ခြွှော
::hgrwaw::ဂြွှော
::hghrwaw::ဃြွှော
::hngrwaw::ငြွှော
::hcrwaw::စြွှော
::hchrwaw::ဆြွှော
::hjrwaw::ဇြွှော
::hjhrwaw::ဈြွှော
::hnyrwaw::ဉြွှော
::hNyrwaw::ညြွှော
::hTrwaw::ဋြွှော
::hThrwaw::ဌြွှော
::hDrwaw::ဍြွှော
::hDhrwaw::ဎြွှော
::hNrwaw::ဏြွှော
::htrwaw::တြွှော
::hthrwaw::ထြွှော
::hdrwaw::ဒြွှော
::hdhrwaw::ဓြွှော
::hnrwaw::နြွှော
::hprwaw::ပြွှော
::hphrwaw::ဖြွှော
::hbrwaw::ဗြွှော
::hbhrwaw::ဘြွှော
::hmrwaw::မြွှော
::hyrwaw::ယြွှော
::hrrwaw::ရြွှော
::hlrwaw::လြွှော
::hLrwaw::ဠြွှော
::hwrwaw::ဝြွှော
::hhrwaw::ဟြွှော
::hsrwaw::သြွှော
::hSrwaw::ဿြွှော

::hkrwaww::ကြွှော်
::hkhrwaww::ခြွှော်
::hgrwaww::ဂြွှော်
::hghrwaww::ဃြွှော်
::hngrwaww::ငြွှော်
::hcrwaww::စြွှော်
::hchrwaww::ဆြွှော်
::hjrwaww::ဇြွှော်
::hjhrwaww::ဈြွှော်
::hnyrwaww::ဉြွှော်
::hNyrwaww::ညြွှော်
::hTrwaww::ဋြွှော်
::hThrwaww::ဌြွှော်
::hDrwaww::ဍြွှော်
::hDhrwaww::ဎြွှော်
::hNrwaww::ဏြွှော်
::htrwaww::တြွှော်
::hthrwaww::ထြွှော်
::hdrwaww::ဒြွှော်
::hdhrwaww::ဓြွှော်
::hnrwaww::နြွှော်
::hprwaww::ပြွှော်
::hphrwaww::ဖြွှော်
::hbrwaww::ဗြွှော်
::hbhrwaww::ဘြွှော်
::hmrwaww::မြွှော်
::hyrwaww::ယြွှော်
::hrrwaww::ရြွှော်
::hlrwaww::လြွှော်
::hLrwaww::ဠြွှော်
::hwrwaww::ဝြွှော်
::hhrwaww::ဟြွှော်
::hsrwaww::သြွှော်
::hSrwaww::ဿြွှော်

::hkrwai::ကြွှဲ
::hkhrwai::ခြွှဲ
::hgrwai::ဂြွှဲ
::hghrwai::ဃြွှဲ
::hngrwai::ငြွှဲ
::hcrwai::စြွှဲ
::hchrwai::ဆြွှဲ
::hjrwai::ဇြွှဲ
::hjhrwai::ဈြွှဲ
::hnyrwai::ဉြွှဲ
::hNyrwai::ညြွှဲ
::hTrwai::ဋြွှဲ
::hThrwai::ဌြွှဲ
::hDrwai::ဍြွှဲ
::hDhrwai::ဎြွှဲ
::hNrwai::ဏြွှဲ
::htrwai::တြွှဲ
::hthrwai::ထြွှဲ
::hdrwai::ဒြွှဲ
::hdhrwai::ဓြွှဲ
::hnrwai::နြွှဲ
::hprwai::ပြွှဲ
::hphrwai::ဖြွှဲ
::hbrwai::ဗြွှဲ
::hbhrwai::ဘြွှဲ
::hmrwai::မြွှဲ
::hyrwai::ယြွှဲ
::hrrwai::ရြွှဲ
::hlrwai::လြွှဲ
::hLrwai::ဠြွှဲ
::hwrwai::ဝြွှဲ
::hhrwai::ဟြွှဲ
::hsrwai::သြွှဲ
::hSrwai::ဿြွှဲ

>!g::Send, {U+1004}{U+103A}{U+1039}
>!n::Send, {U+1036}
>!.::Send, {U+1037}
>!h::Send, {U+1038}
::||::။
::|::၊
::hnai::၌
::rwe::၍
::LK::၎
:*?:E::၏

>!0::Send, {U+1040}
>!1::Send, {U+1041}
>!2::Send, {U+1042}
>!3::Send, {U+1043}
>!4::Send, {U+1044}
>!5::Send, {U+1045}
>!6::Send, {U+1046}
>!7::Send, {U+1047}
>!8::Send, {U+1048}
>!9::Send, {U+1049}