#Hotstring O
#Hotstring EndChars :
<^+-::Suspend -1
<!`::Send, {U+207B}
<!+`::Send, {U+207A}
<!0::Send, {U+2070}
<!+0::Send, {U+2080}
<!1::Send, {U+00B9}
<!+1::Send, {U+2081}
<!2::Send, {U+00B2}
<!+2::Send, {U+2082}
<!3::Send, {U+00B3}
<!+3::Send, {U+2083}
<!4::Send, {U+2074}
<!+4::Send, {U+2084}
<!5::Send, {U+2075}
<!+5::Send, {U+2085}
<!6::Send, {U+2076}
<!+6::Send, {U+2086}
<!7::Send, {U+2077}
<!+7::Send, {U+2087}
<!8::Send, {U+2078}
<!+8::Send, {U+2088}
<!9::Send, {U+2079}
<!+9::Send, {U+2089}
<!-::Send, {U+2013}
<!_::Send, {U+2014}
<!=::Send, {U+00B1}
<!+::Send, {U+2020}
<^<!+::Send, {U+2021}
<!q::Send, {U+00BC}
<!+q::Send, {U+00BE}
<!w::Send, {U+00BD}
<!+w::Send, {U+2016}
<!e::Send, {U+03B5}
<!+e::Send, {U+218B}
<!r::Send, {U+00AE}
<!+r::Send, {U+2117}
<^<!r::Send, {U+03C1}
<!t::Send, {U+2122}
<!+t::Send, {U+03C4}
<!y::Send, {U+2153}
<!+y::Send, {U+2154}
<^<!y::Send, {U+03C5}
<!u::Send, {U+221E}
<!+u::Send, {U+2135}
<^<!u::Send, {U+03B8}
<^<!+u::Send, {U+0398}
<!i::Send, {U+2191}
<!+i::Send, {U+2071}
<^<!i::Send, {U+03B9}
<!o::Send, {U+00B0}
<!+o::Send, {U+00A4}
<^<!o::Send, {U+03BF}
<^<!+o::Send, {U+1D1A9}
<!p::Send, {U+03C0}
<!+p::Send, {U+00B6}
<![::Send, {U+2329}
<!+[::Send, {U+2669}
<!]::Send, {U+232A}
<!+]::Send, {U+266A}
<!|::Send, {U+00A6}
<!\::Send, {U+00AC}
<!a::Send, {U+03B1}
<!+a::Send, {U+00C5}
<!s::Send, {U+03A3}
<!+s::Send, {U+00A7}
<^<!s::Send, {U+03C3}
<^<!+s::Send, {U+03C2}
<!d::Send, {U+03B4}
<!+d::Send, {U+0394}
<!f::Send, {U+03C6}
<!+f::Send, {U+03A6}
<!g::Send, {U+03B3}
<!+g::Send, {U+0393}
<!h::Send, {U+03B7}
<!+h::Send, {U+2606}
<^<!+h::Send, {U+2605}
<!j::Send, {U+2190}
<!+j::Send, {U+2260}
<^<!j::Send, {U+03BE}
<!k::Send, {U+2193}
<!+k::Send, {U+2640}
<^<!k::Send, {U+03BA}
<!l::Send, {U+2192}
<!+l::Send, {U+2642}
<^<!l::Send, {U+03BB}
<^<!+l::Send, {U+039B}
<!;::Send, {U+00B7}
<!'::Send, {U+266F}
<!"::Send, {U+266E}
<^<!"::Send, {U+1D12A}
<!+;::Send, {U+2022}
<!z::Send, {U+2032}
<!+z::Send, {U+2033}
<^<!z::Send, {U+03B6}
<!x::Send, {U+00D7}
<!+x::Send, {U+218A}
<^<!x::Send, {U+03C7}
<^<!+x::Send, {U+03A7}
<!c::Send, {U+00A9}
<!+c::Send, {U+00A2}
<^<!c::Send, {U+03C8}
<^<!+c::Send, {U+03A8}
<!v::Send, {U+03C9}
<!+v::Send, {U+03A9}
<!b::Send, {U+03B2}
<!+b::Send, {U+2661}
<^<!+b::Send, {U+2665}
<!n::Send, {U+2116}
<!+n::Send, {U+207F}
<^<!n::Send, {U+03BD}
<!m::Send, {U+03BC}
<!+m::Send, {U+2212}
<!,::Send, {U+266D}
<!+,::Send, {U+2264}
<^<!+,::Send, {U+1D12B}
<!.::Send, {U+2026}
<!+.::Send, {U+2265}
<!/::Send, {U+00F7}
<!?::Send, {U+221A}
<!vk20::Send, {U+2009}
<!+vk20::Send, {U+200A}

<!vk60::Send, {U+2070}
<!+vk60::Send, {U+2080}
<!vk61::Send, {U+00B9}
<!+vk61::Send, {U+2081}
<!vk62::Send, {U+00B2}
<!+vk62::Send, {U+2082}
<!vk63::Send, {U+00B3}
<!+vk63::Send, {U+2083}
<!vk64::Send, {U+2074}
<!+vk64::Send, {U+2084}
<!vk65::Send, {U+2075}
<!+vk65::Send, {U+2085}
<!vk66::Send, {U+2076}
<!+vk66::Send, {U+2086}
<!vk67::Send, {U+2077}
<!+vk67::Send, {U+2087}
<!vk68::Send, {U+2078}
<!+vk68::Send, {U+2088}
<!vk69::Send, {U+2079}
<!+vk69::Send, {U+2089}
<!vk6A::Send, {U+00D7}
<!vk6B::Send, {U+00B1}
<!vk6D::Send, {U+2212}
<!vk6F::Send, {U+00F7}
<!+vk6F::Send, {U+221A}

:::grin::😃
:::happy::😄
:::beaming::😁
:::joy::😂
:::wink::😉
:::smile::😊
:::hearteyes::😍
:::blowakiss::😘
:::smiley::☺
:::smiling::☺️
:::kissing::😚
:::winkingtongue::😜
:::tongue::😝
:::smirk::😏
:::unamused::😒
:::relieved::😌
:::pensive::😔
:::sleepy::😪
:::medicalmask::😷
:::astonished::😲
:::flushed::😳
:::fearful::😨
:::anxious::😰
:::console::😥
:::tear::😢
:::crying::😭
:::scream::😱
:::confounded::😖
:::persevering::😣
:::disappointed::😞
:::downcast::😓
:::rage::😡
:::angry::😠
:::imp::👿
:::skull::💀
:::poo::💩
:::ghost::👻
:::alien::👽
:::taito::👾
:::waving::👋
:::hand::✋
:::okay::👌
:::peacesign::✌️
:::peacesignsy::✌
:::pointleft::👈
:::pointright::👉
:::pointup::👆
:::pointdown::👇
:::point::☝️
:::pointto::☝
:::thumbsup::👍
:::thumbsdown::👎
:::raisedfist::✊
:::fist::👊
:::clap::👏
:::hands::🙌
:::openhands::👐
:::foldedhands::🙏
:::nailpolish::💅
:::flex::💪
:::ear::👂
:::nose::👃
:::eyes::👀
:::lips::👄
:::baby::👶
:::boy::👦
:::girl::👧
:::blond::👱
:::man::👨
:::woman::👩
:::oldman::👴
:::oldwoman::👵
:::nogesture::🙅
:::yesgesture::🙆
:::tipgesture::💁
:::bowing::🙇
:::police::👮
:::guard::💂
:::constructionworker::👷
:::princess::👸
:::turban::👳
:::skullcap::👲
:::cherub::👼
:::santa::🎅
:::massage::💆
:::haircut::💇
:::walking::🚶
:::running::🏃
:::dancer::💃
:::bunnysuit::👯
:::surfer::🏄
:::swimmer::🏊
:::bath::🛀
:::couple::👫
:::lovers::💏
:::compatibility::💑
:::footprints::👣
:::saru::🐵
:::monkey::🐒
:::inu::🐶
:::ookami::🐺
:::wolf::🐺
:::neko::🐱
:::tora::🐯
:::uma::🐴
:::horse::🐎
:::ushi::🐮
:::buta::🐷
:::inoshishi::🐗
:::boar::🐗
:::sheep::🐑
:::camel::🐫
:::elephant::🐘
:::nezumi::🐭
:::hamster::🐹
:::usagi::🐰
:::kuma::🐻
:::bear::🐻
:::koala::🐨
:::chicken::🐔
:::chick::🐤
:::bird::🐦
:::penguin::🐧
:::kaeru::🐸
:::frog::🐸
:::snake::🐍
:::spoutingwhale::🐳
:::dolphin::🐬
:::fish::🐟
:::tropicalfish::🐠
:::octopus::🐙
:::shell::🐚
:::bug::🐛
:::bouquet::💐
:::sakura::🌸
:::rose::🌹
:::hibiscus::🌺
:::sunflower::🌻
:::tulip::🌷
:::palmtree::🌴
:::cactus::🌵
:::sheafofrice::🌾
:::clover::🍀
:::maple::🍁
:::fallleaves::🍂
:::leaves::🍃
:::moon::🌙
:::sun::☀️
:::sunsy::☀
:::star::⭐️
:::whitemediumstar::⭐
:::glowingstar::🌟
:::cloudsy::☁
:::cloud::☁️
:::cyclone::🌀
:::rainbow::🌈
:::closedumbrella::🌂
:::umbrellarain::☔
:::bolt::⚡
:::snowman::⛄
:::fire::🔥
:::water::🌊
:::watermelon::🍉
:::orange::🍊
:::apple::🍎
:::strawberry::🍓
:::tomato::🍅
:::eggplant::🍆
:::bread::🍞
:::burger::🍔
:::fries::🍟
:::cooking::🍳
:::pot::🍲
:::bentobox::🍱
:::ricecracker::🍘
:::riceball::🍙
:::rice::🍚
:::curryrice::🍛
:::noodles::🍜
:::spaghetti::🍝
:::oden::🍢
:::sushi::🍣
:::dango::🍡
:::icecream::🍦
:::shavedice::🍧
:::birthday::🎂
:::cake::🍰
:::hotbeverage::☕
:::teacup::🍵
:::sake::🍶
:::cocktail::🍸
:::beer::🍺
:::beers::🍻
:::silverware::🍴
:::jackolantern::🎃
:::christmastree::🎄
:::fireworks::🎆
:::sparkler::🎇
:::sparkles::✨
:::balloon::🎈
:::partypopper::🎉
:::pinedecoration::🎍
:::dolls::🎎
:::carpstreamer::🎏
:::windchime::🎐
:::moonviewing::🎑
:::present::🎁
:::ticket::🎫
:::trophy::🏆
:::soccerball::⚽
:::baseball::⚾
:::basketball::🏀
:::football::🏈
:::tennis::🎾
:::flaginhole::⛳
:::skis::🎿
:::bullseye::🎯
:::pistol::🔫
:::8ball::🎱
:::slots::🎰
:::spadessuit::♠️
:::spades::♠
:::heartssuit::♥️
:::hearts::♥
:::diamondssuit::♦️
:::diamonds::♦
:::clubssuit::♣️
:::clubs::♣
:::mahjong::🀄
:::palette::🎨
:::mountfuji::🗻
:::house::🏠
:::officebuilding::🏢
:::postofficebuilding::🏣
:::hospital::🏥
:::bank::🏦
:::hotel::🏨
:::lovehotel::🏩
:::gasstation::🏪
:::school::🏫
:::hardwarestore::🏬
:::factory::🏭
:::jou::🏯
:::castle::🏰
:::wedding::💒
:::tokyotower::🗼
:::statueofliberty::🗽
:::church::⛪
:::fountain::⛲
:::tent::⛺
:::night::🌃
:::sunrisemountains::🌄
:::sunrisesea::🌅
:::eveningskyline::🌆
:::sunsetskyline::🌇
:::onsen::♨
:::hotspring::♨️
:::ferriswheel::🎡
:::rollercoaster::🎢
:::barberpole::💈
:::railwaycar::🚃
:::highspeedtrain::🚄
:::bullettrain::🚅
:::metro::🚇
:::station::🚉
:::bus::🚌
:::ambulance::🚑
:::firetruck::🚒
:::policecar::🚓
:::taxi::🚕
:::car::🚗
:::suv::🚙
:::deliverytruck::🚚
:::bicycle::🚲
:::busstop::🚏
:::fuelpump::⛽
:::horizontaltrafficlight::🚥
:::construction::🚧
:::boat::⛵
:::speedboat::🚤
:::ship::🚢
:::plane::✈️
:::planesy::✈
:::seat::💺
:::rocket::🚀
:::1200::🕛
:::0100::🕐
:::0200::🕑
:::0300::🕒
:::0400::🕓
:::0500::🕔
:::0600::🕕
:::0700::🕖
:::0800::🕗
:::0900::🕘
:::1000::🕙
:::1100::🕚
:::ribbon::🎀
:::necktie::👔
:::tshirt::👕
:::dress::👗
:::kimono::👘
:::bikini::👙
:::handbag::👜
:::backpack::🎒
:::shoe::👟
:::highheel::👠
:::womanssandal::👡
:::womansboot::👢
:::crown::👑
:::womanshat::👒
:::tophat::🎩
:::graduationcap::🎓
:::lipstick::💄
:::ring::💍
:::gem::💎
:::highvolume::🔊
:::loudspeaker::📢
:::megaphone::📣
:::bell::🔔
:::note::🎵
:::notes::🎶
:::microphone::🎤
:::headphones::🎧
:::radio::📻
:::saxophone::🎷
:::trumpet::🎺
:::guitar::🎸
:::phone::📱
:::arrowphone::📲
:::dial::☎️
:::dialsy::☎
:::fax::📠
:::laptop::💻
:::computerdisc::💽
:::cd::💿
:::dvd::📀
:::moviecamera::🎥
:::clapper::🎬
:::crt::📺
:::camera::📷
:::vhs::📼
:::magnify::🔍
:::light::💡
:::openbook::📖
:::moneybag::💰
:::yenstocksup::💹
:::envelopedown::📩
:::mail::📫
:::postbox::📮
:::writing::📝
:::briefcase::💼
:::scissors::✂️
:::scissorssy::✂
:::locked::🔒
:::unlocked::🔓
:::key::🔑
:::hammer::🔨
:::bomb::💣
:::satellite::📡
:::syringe::💉
:::pill::💊
:::toilet::🚽
:::cigarette::🚬
:::heartarrow::💘
:::heartribbon::💝
:::growingheart::💗
:::beatingheart::💓
:::heartbutton::💟
:::brokenheart::💔
:::redheart::❤️
:::heart::❤
:::yellowheart::💛
:::greenheart::💚
:::blueheart::💙
:::purpleheart::💜
:::kiss::💋
:::anger::💢
:::sweat::💦
:::dashing::💨
:::zzz::💤
:::atm::🏧
:::handicap::♿
:::mens::🚹
:::womens::🚺
:::unisex::🚻
:::babysy::🚼
:::wc::🚾
:::warning::⚠️
:::warningsign::⚠
:::nosmoking::🚭
:::18::🔞
:::up::⬆️
:::uparrow::⬆
:::upright::↗️
:::uprightarrow::↗
:::right::➡️
:::rightarrow::➡
:::downright::↘️
:::downrightarrow::↘️
:::down::⬇️
:::downarrow::⬇
:::downleft::↙️
:::left::⬅️
:::leftarrow::⬅
:::upleft::↖️
:::upleftarrow::↖
:::top::🔝
:::daviddot::🔯
:::aries::♈
:::taurus::♉
:::gemini::♊
:::cancer::♋
:::leo::♌
:::virgo::♍
:::libra::♎
:::scorpio::♏
:::sagittarius::♐
:::capricorn::♑
:::aquarius::♒
:::pisces::♓
:::ophiuchus::⛎
:::play::▶️
:::righttriangle::▶
:::fastforward::⏩
:::rewind::◀️
:::lefttriangle::◀
:::fastreverse::⏪
:::cinema::🎦
:::connection::📶
:::vibrationmode::📳
:::phoneoff::📴
:::int::❓
:::?::❔
:::!::❕
:::bang::❗
:::usdyen::💱
:::trident::🔱
:::shoshinsha::🔰
:::wakaba::🔰
:::beginner::🔰
:::correct::⭕
:::incorrect::❌
:::doubleloop::➿
:::partalteration::〽️
:::asterisk::✳️
:::eightspokedasterisk::✳
:::eightpointedstar::✴️
:::octagram::✴
:::copyright::©️
:::registered::®️
:::trademark::™️
:::#::#️⃣
:::0::0️⃣
:::1::1️⃣
:::2::2️⃣
:::3::3️⃣
:::4::4️⃣
:::5::5️⃣
:::6::6️⃣
:::7::7️⃣
:::8::8️⃣
:::9::9️⃣
:::abutton::🅰
:::a::🅰️
:::ab::🆎
:::bbutton::🅱
:::b::🅱️
:::cool::🆒
:::id::🆔
:::new::🆕
:::obutton::🅾
:::o::🅾️
:::ok::🆗
:::pbutton::🅿
:::p::🅿️
:::up!::🆙
:::vs::🆚
:C::KOKO::🈁
:C::SE::🈂️
:C::GATSU::🈷️
:C::YUU::🈶
:C::SHI::🈯
:C::SHIbutton::🈯️
:C::TOKUbutton::🉐️
:C::TOKU::🉐
:::waributton::🈹️
:::wari::🈹
:C::MUbutton::🈚️
:C::MU::🈚
:::SHINbutton::🈸️
:C::SHIN::🈸
:::kara::🈳
:C::FUKUbutton::㊗️
:C::FUKU::㊗
:C::HIbutton::㊙️
:C::HI::㊙
:C::EIbutton::🈺️
:C::EI::🈺
:C::MIbutton::🈵️
:C::MI::🈵
:::redcircle::🔴
:::blackborderedsquare::🔳
:::whiteborderedsquare::🔲
:::chequeredflag::🏁
:::crossedflags::🎌
:::cn::🇨🇳
:::de::🇩🇪
:::es::🇪🇸
:::fr::🇫🇷
:::gb::🇬🇧
:::it::🇮🇹
:::jp::🇯🇵
:::kr::🇰🇷
:::ru::🇷🇺
:::us::🇺🇸
:::shibuya::

:::shootingstar::🌠
:::train::🚆
:::tram::🚋
:::speaker::🔈
:::*::*️⃣
:::blacksquare::⬛
:::whitesquare::⬜

:::haha::😆
:::nervous::😅
:::angel::😇
:::yum::😋
:::blank::😐
:::nomouth::😶
:::xx::😵
:::coolface::😎
:::groan::😩
:::pain::😫
:::proud::😤
:::devil::😈
:::oni::👹
:::tengu::👺
:::nekosmile::😺
:::nekohappy::😸
:::nekojoy::😹
:::nekolove::😻
:::nekomischief::😼
:::nekokiss::😽
:::nekoscream::🙀
:::nekotear::😿
:::nekoangry::😾
:::seenoevil::🙈
:::hearnoevil::🙉
:::speaknoevil::🙊
:::lick::👅
:::frowning::🙍
:::pouting::🙎
:::asking::🙋
:::bride::👰
:::racinghorse::🏇
:::snowboarding::🏂
:::rowing::🚣
:::biking::🚴
:::mountainbiking::🚵
:::ffcouple::👭
:::mmcouple::👬
:::silhouette::👤
:::silhouettes::👥
:::family::👪
:::dog::🐕
:::poodle::🐩
:::cat::🐈
:::tiger::🐅
:::leopard::🐆
:::ox::🐂
:::waterbuffalo::🐃
:::cow::🐄
:::pig::🐖
:::piggy::🐽
:::ram::🐏
:::goat::🐐
:::camel::🐪
:::mouse::🐁
:::rat::🐀
:::rabbit::🐇
:::panda::🐼
:::pawprints::🐾
:::rooster::🐓
:::hatching::🐣
:::babychick::🐥
:::crocodile::🐊
:::turtle::🐢
:::ryuu::🐲
:::dragon::🐉
:::whale::🐋
:::blowfish::🐡
:::snail::🐌
:::ant::🐜
:::bee::🐝
:::ladybug::🐞
:::hanamaru::💮
:::flower::🌼
:::sprout::🌱
:::pinetree::🌲
:::tree::🌳
:::herb::🌿
:::mushroom::🍄
:::newmoon::🌑
:::waxingcrescent::🌒
:::firstquarter::🌓
:::waxinggibbous::🌔
:::fullmoon::🌕
:::waninggibbous::🌖
:::lastquarter::🌗
:::waningcrescent::🌘
:::newmoonface::🌚
:::leftmoonface::🌛
:::rightmoonface::🌜
:::manonthemoon::🌝
:::sunface::🌞
:::milkyway::🌌
:::partlycloudy::⛅
:::snowflake::❄️
:::snowflakesy::❄
:::drop::💧
:::grapes::🍇
:::melon::🍈
:::lemon::🍋
:::banana::🍌
:::pineapple::🍍
:::grannysmith::🍏
:::pear::🍐
:::peach::🍑
:::cherry::🍒
:::corn::🌽
:::chestnut::🌰
:::meat::🍖
:::drumstick::🍗
:::pizza::🍕
:::sweetpotato::🍠
:::friedshrimp::🍤
:::fishcake::🍥
:::icecreambowl::🍨
:::donut::🍩
:::doughnut::🍩
:::cookie::🍪
:::biscuit::🍪
:::chocolate::🍫
:::candy::🍬
:::lollipop::🍭
:::custard::🍮
:::honey::🍯
:::formula::🍼
:::wine::🍷
:::fruitdrink::🍹
:::knife::🔪
:::confetti::🎊
:::tanabata::🎋
:::rugby::🏉
:::bowling::🎳
:::fishingpole::🎣
:::runningshirt::🎽
:::crystalball::🔮
:::gaming::🎮
:::dice::🎲
:::joker::🃏
:::hanafuda::🎴
:::drama::🎭
:::globe::🌍
:::90w::🌎
:::150e::🌏
:::world::🌐
:::japan::🗾
:::volcano::🌋
:::housewithgarden::🏡
:::postoffice::🏤
:::foggy::🌁
:::bridgeatnight::🌉
:::carousel::🎠
:::circus::🎪
:::steamtrain::🚂
:::railwaycar::🚃
:::lightrail::🚈
:::tram::🚊
:::monorail::🚝
:::mountainrailway::🚞
:::oncomingbus::🚍
:::trolleybus::🚎
:::minibus::🚐
:::oncomingpolicecar::🚔
:::oncomingtaxi::🚖
:::oncomingcar::🚘
:::semitruck::🚛
:::tractor::🚜
:::siren::🚨
:::trafficlight::🚦
:::anchor::⚓
:::helicopter::🚁
:::suspendedrailway::🚟
:::mountaincableway::🚠
:::tramway::🚡
:::moai::🗿
:::hourglass::⌛
:::waiting::⏳
:::watch::⌚
:::alarm::⏰
:::1230::🕧
:::0130::🕜
:::0230::🕝
:::0330::🕞
:::0430::🕟
:::0530::🕠
:::0630::🕡
:::0730::🕢
:::0830::🕣
:::0930::🕤
:::1030::🕥
:::1130::🕦
:::glasses::👓
:::jeans::👖
:::pinkshirt::👚
:::purse::👛
:::clutchbag::👝
:::brownshoe::👞
:::mute::🔇
:::sound::🔉
:::loud::🔊
:::postalhorn::📯
:::donotdisturb::🔕
:::staff::🎼
:::keys::🎹
:::violin::🎻
:::telephone::📞
:::pager::📟
:::battery::🔋
:::plug::🔌
:::disk::💾
:::video::📹
:::search::🔎
:::flashlight::🔦
:::lantern::🏮
:::notebooklabel::📔
:::redbook::📕
:::greenbook::📗
:::bluebook::📘
:::orangebook::📙
:::books::📚
:::notebook::📓
:::ledger::📒
:::page::📃
:::scroll::📜
:::document::📄
:::newspaper::📰
:::bookmarktabs::📑
:::bookmark::🔖
:::yen::💴
:::dollar::💵
:::euro::💶
:::pound::💷
:::money::💸
:::creditcard::💳
:::mail::✉️
:::mailsy::✉
:::email::📧
:::incomingmail::📨
:::outbox::📤
:::inbox::📥
:::package::📦
:::closedmailbox::📪
:::openmailbox::📬
:::emptymailbox::📭
:::pencil::✏️
:::pencilsy::✏
:::nib::✒️
:::nibsy::✒
:::folder::📁
:::openfolder::📂
:::calendar::📅
:::tearoffcalendar::📆
:::cardindex::📇
:::stocksup::📈
:::stocksdown::📉
:::chart::📊
:::clipboard::📋
:::pin::📌
:::roundpin::📍
:::paperclip::📎
:::ruler::📏
:::triangularruler::📐
:::penwithlock::🔏
:::keylock::🔐
:::wrench::🔧
:::nutandbolt::🔩
:::link::🔗
:::microscope::🔬
:::telescope::🔭
:::door::🚪
:::shower::🚿
:::bathtub::🛁
:::loveletter::💌
:::sparklyheart::💖
:::hearttwirl::💞
:::twohearts::💕
:::100::💯
:::collision::💥
:::dizzy::💫
:::speechbubble::💬
:::thoughtballoon::💭
:::garbage::🚮
:::potable::🚰 
:::border::🛂
:::customs::🛃
:::baggage::🛄
:::leftluggage::🛅
:::childrencrossing::🚸
:::deny::⛔
:::prohibited::🚫
:::nobicycles::🚳
:::nolittering::🚯
:::nonpotable::🚱
:::nopedestrians::🚷
:::nophones::📵
:::updown::↕️
:::updownarrow::↕
:::leftright::↔️
:::leftrightarrow::↔
:::curveleft::↩️
:::curveleftarrow::↩
:::curveright::↪️
:::curverightarrow::↪
:::curveup::⤴️
:::curveuparrow::⤴
:::curvedown::⤵️
:::curvedownarrow::⤵
:::clockwise::🔃
:::counterclockwise::🔄
:::back::🔙
:::end::🔚
:::on::🔛
:::soon::🔜
:::shuffle::🔀
:::repeat::🔁
:::repeatsingle::🔂
:::upbutton::🔼
:::fastupbutton::⏫
:::donwbutton::🔽
:::fastdownbutton::⏬
:::fastdownbutton::⏫
:::dim::🔅
:::bright::🔆
:::multiply::✖️
:::multiplysign::✖
:::plus::➕
:::minus::➖
:::divide::➗
:::bangbang::‼️
:::bangbangsy::‼
:::bangint::⁉️
:::bangintsy::⁉
:::waveydash::〰️
:::waveydashsy::〰
:::dollarsign::💲
:::recycle::♻️
:::recyclesy::♻
:::nametag::📛
:::checkmark::✅
:::checkbox::☑️
:::checkboxsy::☑
:::check::✔️
:::checksy::✔
:::mark::❎
:::cross::❎
:::loop::➰
:::sparkle::❇️
:::sparklesy::❇
:::10::🔟
:C::ABCD::🔠
:C::abcd::🔡
:::1234::🔢
:::symbols::🔣
:::abc::🔤
:::clbutton::🆑
:::free::🆓
:::i::ℹ
:::info::ℹ️
:::m::Ⓜ️
:::circlem::Ⓜ
:C::NG::🆖
:::sos::🆘
:::kin::🈲
:::kabutton::🉑
:::ka::🉑️
:::gou::🈴︎
:::goubutton::🈴
:::bluecircle::🔵
:::blackcircle::⚫
:::whitecircle::⚪
:::whitecircle::⚪
:::mediumblacksquare::◼️
:::mediumblacksquaresy::◼
:::mediumwhitesquare::◻️
:::mediumwhitesquaresy::◻
:::mediumsmallblacksquare::◾
:::mediumsmallwhitesquare::◽
:::smallblacksquare::▪️
:::smallblacksquaresy::▪
:::smallwhitesquare::▫️
:::smallwhitesquaresy::▫
:::largeorangediamond::🔶
:::largebluediamond::🔷
:::smallorangediamond::🔸
:::smallbluediamond::🔹
:::reduptriangle::🔺
:::reddowntriangle::🔻
:::diamond::💠
:::radiobutton::🔘
:::redflag::🚩

:::biggrin::😀
:::puckering::😗
:::eyesclosedpuckering::😙
:::tongueface::😛
:::expressionless::😑
:::grimace::😬
:::sleeping::😴
:::confused::😕
:::worried::😟
:::surprise::😮
:::gasp::😯
:::scared::😦
:::shocked::😧

:*?::=\::‍
:::white::🏻
:::tan::🏼
:::medium::🏽
:::dark::🏾
:::black::🏿
:::mflovers::👩‍❤️‍💋‍👨
:::mmlovers::👨‍❤️‍💋‍👨
:::fflovers::👩‍❤️‍💋‍👩
:::mfcompatibility::👩‍❤️‍👨
:::mmcompatibility::👨‍❤️‍👨
:::ffcompatibility::👩‍❤️‍👩
:::mom::👩‍
:::dad::👨‍
:::parents::👨‍👩‍
:::dads::👨‍👨‍
:::moms::👩‍👩‍
:::daughter::👧‍
:::daughters::👧‍👧
:::son::👦
:::sons::👦‍👦
:::ad::🇦🇩
:::ae::🇦🇪
:::af::🇦🇫
:::ag::🇦🇬
:::ai::🇦🇮
:::al::🇦🇱
:::am::🇦🇲
:::ao::🇦🇴
:::ar::🇦🇷
:::as::🇦🇸
:::at::🇦🇹
:::au::🇦🇺
:::az::🇦🇿
:::ba::🇧🇦
:::bb::🇧🇧
:::bd::🇧🇩
:::be::🇧🇪
:::bf::🇧🇫
:::bg::🇧🇬
:::bh::🇧🇭
:::bi::🇧🇮
:::bj::🇧🇯
:::bm::🇧🇲
:::bn::🇧🇳
:::bo::🇧🇴
:::br::🇧🇷
:::bs::🇧🇸
:::bt::🇧🇹
:::bw::🇧🇼
:::by::🇧🇾
:::bz::🇧🇿
:::ca::🇨🇦
:::cd::🇨🇩
:::cf::🇨🇫
:::cg::🇨🇬
:::ch::🇨🇭
:::ci::🇨🇮
:::ck::🇨🇰
:::cl::🇨🇱
:::cm::🇨🇲
:::co::🇨🇴
:::cr::🇨🇷
:::cu::🇨🇺
:::cv::🇨🇻
:::cw::🇨🇼
:::cy::🇨🇾
:::cz::🇨🇿
:::dj::🇩🇯
:::dk::🇩🇰
:::dm::🇩🇲
:::do::🇩🇴
:::dz::🇩🇿
:::ec::🇪🇨
:::ee::🇪🇪
:::eg::🇪🇬
:::er::🇪🇷
:::et::🇪🇹
:::fi::🇫🇮
:::fj::🇫🇯
:::fo::🇫🇴
:::ga::🇬🇦
:::gd::🇬🇩
:::ge::🇬🇪
:::gf::🇬🇫
:::gh::🇬🇭
:::gi::🇬🇮
:::gm::🇬🇲
:::gn::🇬🇳
:::gq::🇬🇶
:::gr::🇬🇷
:::gt::🇬🇹
:::gu::🇬🇺
:::gw::🇬🇼
:::gy::🇬🇾
:::hk::🇭🇰
:::hn::🇭🇳
:::hr::🇭🇷
:::ht::🇭🇹
:::hu::🇭🇺
:::id::🇮🇩
:::ie::🇮🇪
:::il::🇮🇱
:::in::🇮🇳
:::iq::🇮🇶
:::ir::🇮🇷
:::is::🇮🇸
:::jm::🇯🇲
:::jo::🇯🇴
:::ke::🇰🇪
:::kg::🇰🇬
:::kh::🇰🇭
:::ki::🇰🇮
:::km::🇰🇲
:::kn::🇰🇳
:::kp::🇰🇵
:::kw::🇰🇼
:::ky::🇰🇾
:::kz::🇰🇿
:::la::🇱🇦
:::lb::🇱🇧
:::lc::🇱🇨
:::li::🇱🇮
:::lk::🇱🇰
:::lr::🇱🇷
:::ls::🇱🇸
:::lt::🇱🇹
:::lu::🇱🇺
:::lt::🇱🇻
:::ly::🇱🇾
:::ma::🇲🇦
:::md::🇲🇩
:::me::🇲🇪
:::mf::🇲🇫
:::mg::🇲🇬
:::mk::🇲🇰
:::ml::🇲🇱
:::mm::🇲🇲
:::mn::🇲🇳
:::mo::🇲🇴
:::mp::🇲🇵
:::mr::🇲🇷
:::ms::🇲🇸
:::mt::🇲🇹
:::mv::🇲🇻
:::mw::🇲🇼
:::mx::🇲🇽
:::my::🇲🇾
:::mz::🇲🇿
:::na::🇳🇦
:::nc::🇳🇨
:::ne::🇳🇪
:C::ng::🇳🇬
:::ni::🇳🇮
:::nl::🇳🇱
:::no::🇳🇴
:::np::🇳🇵
:::nu::🇳🇺
:::nz::🇳🇿
:C::om::🇴🇲
:::pa::🇵🇦
:::pe::🇵🇪
:::pg::🇵🇬
:::pk::🇵🇰
:::pl::🇵🇱
:::pr::🇵🇷
:::ps::🇵🇸
:::pt::🇵🇹
:::pu::🇵🇺
:::py::🇵🇾
:::qa::🇶🇦
:::ro::🇷🇴
:::rs::🇷🇸
:::rw::🇷🇼
:::sa::🇸🇦
:::sb::🇸🇧
:::sc::🇸🇨
:::sd::🇸🇩
:::se::🇸🇪
:::sg::🇸🇬
:::si::🇸🇮
:::sk::🇸🇰
:::sl::🇸🇱
:::sm::🇸🇲
:::sn::🇸🇳
:::so::🇸🇴
:::sr::🇸🇷
:::ss::🇸🇸
:::st::🇸🇹
:::sv::🇸🇻
:::sx::🇸🇽
:::sy::🇸🇾
:::sz::🇸🇿
:::tc::🇹🇨
:::tf::🇹🇫
:::tg::🇹🇬
:::th::🇹🇭
:::tj::🇹🇯
:::tl::🇹🇱
:::tm::🇹🇲
:::🇹🇳::tn
:::to::🇹🇴
:::tr::🇹🇷
:::tt::🇹🇹
:::tv::🇹🇻
:::tz::🇹🇿
:::ua::🇺🇦
:::ug::🇺🇬
:::uy::🇺🇾
:::uz::🇺🇿
:::vc::🇻🇨
:::ve::🇻🇪
:::vg::🇻🇬
:::vi::🇻🇮
:::vn::🇻🇳
:::vu::🇻🇺
:::ws::🇼🇸
:::xk::🇽🇰
:::ye::🇾🇪
:::za::🇿🇦
:::zm::🇿🇲
:::zw::🇿🇼

:::ac::🇦🇨
:::aq::🇦🇶
:::ax::🇦🇽
:::bl::🇧🇱
:::bq::🇧🇶
:::bv::🇧🇻
:::cc::🇨🇨
:::cp::🇨🇵
:::cx::🇨🇽
:::dg::🇩🇬
:::ea::🇪🇦
:::eh::🇪🇭
:::eu::🇪🇺
:::fk::🇫🇰
:::fm::🇫🇲
:::gg::🇬🇬
:::gl::🇬🇱
:::gp::🇬🇵
:::gs::🇬🇸
:::hm::🇭🇲
:::ic::🇮🇨
:::im::🇮🇲
:::io::🇮🇴
:::je::🇯🇪
:::mc::🇲🇨
:::mh::🇲🇭
:::mq::🇲🇶
:::mu::🇲🇺
:::nf::🇳🇫
:::nr::🇳🇷
:::pf::🇵🇫
:::pm::🇵🇲
:::re::🇷🇪
:::sh::🇸🇭
:::sj::🇸🇯
:::ta::🇹🇦
:::td::🇹🇩
:::tk::🇹🇰
:::tw::🇹🇼
:::um::🇺🇲
:::va::🇻🇦
:::wf::🇼🇫
:::yt::🇾🇹

:::slightsmile::🙂
:::upsidedown::🙃
:::moneymouth::🤑
:::hug::🤗
:::thinking::🤔
:::zipit::🤐
:::rollingeyes::🙄
:::sick::🤒
:::bandaged::🤕
:::nerd::🤓
:::slightfrown::🙁
:::frown::☹️
:::frowny::☹
:::skullnbones::☠️
:::skullnbonessy::☠
:::robot::🤖
:::palm::🖐️
:::palmsy::🖐
:::hornsign::🤘
:::middlefinger::🖕
:::handwriting::✍️
:::handwritingsy::✍
:::eye::👁️
:::eyesy::👁
:::detective::🕵️
:::detectivesy::🕵
:::exclaman::🕴️
:::exclamanpoint::🕴
:::skier::⛷️
:::skiersy::⛷
:::golfing::🏌️
:::golfingsy::🏌
:::dribble::⛹️
:::dribblesy::⛹
:::weightlifting::🏋️
:::weightliftingsy::🏋
:::asleep::🛌
:::speech::🗣️
:::speechsy::🗣
:::lion::🦁
:::unicorn::🦄
:::chipmunk::🐿️
:::chipmunksy::🐿
:::turkey::🦃
:::dove::🕊️
:::dovesy::🕊
:::crab::🦀
:::spider::🕷️
:::spidersy::🕷
:::web::🕸️
:::websy::🕸
:::scorpion::🦂
:::rosette::🏵️
:::rosettesy::🏵
:::shamrock::☘️
:::shamrocksy::☘
:::storm::⛈️
:::stormsy::⛈
:::sunny::🌤️
:::sunnysy::🌤
:::cloudy::🌥️
:::cloudysy::🌥
:::rainy::🌦️
:::rainysy::🌦
:::rain::🌧️
:::rainsy::🌧
:::snow::🌨️
:::snowsy::🌨
:::lightning::🌩️
:::lightningsy::🌩
:::tornado::🌪️
:::tornadosy::🌪
:::fog::🌫️
:::fogsy::🌫
:::wind::🌬️
:::windsy::🌬
:::umbrella::☂️
:::umbrellasy::☂
:::shade::⛱️
:::shadesy::⛱
:::snowyman::☃️
:::snowmansy::☃
:::comet::☄️
:::cometsy::☄
:::hotpepper::🌶️
:::hotpeppersy::🌶
:::cheese::🧀
:::hotdog::🌭
:::taco::🌮
:::burrito::🌯
:::popcorn::🍿
:::pop::🍾
:::dinnerplate::🍽️
:::dinnerplatesy::🍽
:::amphora::🏺
:::admission::🎟️
:::admissionsy::🎟
:::medallion::🎖️
:::medallionsy::🎖
:::medal::🏅
:::volleyball::🏐
:::cricket::🏏
:::fieldhockey::🏑
:::hockey::🏒
:::pingpong::🏓
:::badmitton::🏸
:::iceskate::⛸️
:::iceskatesy::⛸
:::joystick::🕹️
:::joysticksy::🕹
:::picture::🖼️
:::picturesy::🖼
:::worldmap::🗺️
:::worldmapsy::🗺
:::snowcappedmountain::🏔️
:::snowcappedmountainsy::🏔
:::mountain::⛰️
:::mountainsy::⛰
:::camp::🏕️
:::campsy::🏕
:::beach::🏖️
:::beachsy::🏖
:::desert::🏜️
:::desertsy::🏜
:::island::🏝️
:::islandsy::🏝
:::nationalpark::🏞️
:::nationalparksy::🏞
:::stadium::🏟️
:::stadiumsy::🏟
:::classical::🏛️
:::classicalsy::🏛
:::buildingconstruction::🏗️
:::buildingconstructionsy::🏗
:::neighborhood::🏘️
:::neighborhoodsy::🏘
:::abandoned::🏚️
:::abandonedsy::🏚
:::mosque::🕌
:::synanogue::🕍
:::shrine::⛩️
:::shrinesy::⛩
:::kaaba::🕋
:::skyline::🏙️
:::skylinesy::🏙
:::racecar::🏎️
:::racecarsy::🏎
:::motorcycle::🏍️
:::motorcyclesy::🏍
:::motorway::🛣️
:::motorwaysy::🛣
:::tracks::🛤️
:::trackssy::🛤
:::oildrum::🛢️
:::oildrumsy::🛢
:::cruise::🛳️
:::cruisesy::🛳
:::ferry::⛴️
:::ferrysy::⛴
:::motorboat::🛥️
:::motorboatsy::🛥
:::smallplane::🛩️
:::smallplanesy::🛩
:::takeoff::🛫
:::landing::🛬
:::shuttle::🛰️
:::shuttlesy::🛰
:::ding::🛎️
:::dingsy::🛎
:::stopwatch::⏱️
:::stopwatchsy::⏱
:::timer::⏲️
:::timersy::⏲
:::mantelpiece::🕰️
:::mantelpiecesy::🕰
:::thermometer::🌡️
:::thermometersy::🌡
:::coloredribbon::🎗️
:::coloredribbonsy::🎗
:::sunglasses::🕶️
:::sunglassessy::🕶
:::shoppingbags::🛍️
:::shoppingbagssy::🛍
:::rescuehelment::⛑️
:::rescuehelmentsy::⛑
:::beads::📿
:::mic::🎙️
:::micsy::🎙
:::volume::🎚️
:::volumesy::🎚
:::knobs::🎛️
:::knobssy::🎛
:::computer::🖥️
:::computersy::🖥
:::printer::🖨️
:::printersy::🖨
:::keyboard::⌨️
:::keyboardsy::⌨
:::computermouse::🖱️
:::computermousesy::🖱
:::trackball::🖲️
:::trackballsy::🖲
:::film::🎞️
:::filmsy::🎞
:::filmprojector::📽️
:::filmprojectorsy::📽
:::cameraflash::📸
:::candle::🕯️
:::candlesy::🕯
:::rolledupnewspaper::🗞️
:::rolledupnewspapersy::🗞
:::label::🏷️
:::labelsy::🏷
:::ballot::🗳️
:::ballotsy::🗳
:::fountainpen::🖋️
:::fountainpensy::🖋
:::pen::🖊️
:::pensy::🖊
:::paintbrush::🖌️
:::paintbrushsy::🖌
:::crayon::🖍️
:::crayonsy::🖍
:::cardindex::🗂️
:::cardindexsy::🗂
:::notepad::🗒️
:::notepadsy::🗒
:::spiralcalendar::🗓️
:::spiralcalendarsy::🗓
:::paperclips::🖇️
:::paperclipssy::🖇
:::openfilecabinet::🗃️
:::openfilecabinetsy::🗃
:::filecabinet::🗄️
:::filecabinetsy::🗄
:::wastebasket::🗑️
:::wastebasketsy::🗑
:::oldkey::🗝️
:::oldkeysy::🗝
:::pick::⛏️
:::pick::⛏
:::hammerpick::⚒️
:::hammerpicksy::⚒
:::hammerwrench::🛠️
:::hammerwrench::🛠
:::dagger::🗡️
:::daggersy::🗡
:::swords::⚔️
:::swordssy::⚔
:::bowandarrow::🏹
:::shield::🛡️
:::shieldsy::🛡
:::gear::⚙️
:::gearsy::⚙
:::clamp::🗜️
:::clampsy::🗜
:::balancescale::⚖️
:::balancescalesy::⚖
:::chains::⛓️
:::chainssy::⛓
:::alembic::⚗️
:::alembicsy::⚗
:::bed::🛏️
:::bedsy::🛏
:::couchandlamp::🛋️
:::couchandlampsy::🛋
:::coffin::⚰️
:::coffinsy::⚰
:::urn::⚱️
:::urnsy::⚱
:::heartbang::❣️
:::heartpoint::❣
:::hole::🕳️
:::holesy::🕳
:::eyebubble::👁️‍🗨️
:::leftspeechbubble::🗨️
:::angerbubble::🗯️
:::angerbubblesy::🗯
:::radioactive::☢️
:::radioactivesy::☢
:::biohazard::☣️
:::biohazardsy::☣
:::placeofworship::🛐
:::atom::⚛️
:::atomsy::⚛
:C::OM::🕉️
:C::OMsy::🕉
:::starofdavid::✡️
:::starofdavidsy::✡
:::wheelofdharma::☸️
:::wheelofdharmasy::☸
:::yinyang::☯️
:::yinyangsy::☯
:::cross::✝️
:::crosssy::✝
:::orthodox::☦️
:::orthodoxsy::☦
:::turk::☪️
:::turksy::☪
:::peace::☮️
:::peacesy::☮
:::menorah::🕎
:::nexttrack::⏭️
:::nexttracksy::⏭
:::playpause::⏯️
:::playpausesy::⏯
:::lasttrack::⏮️
:::lasttracksy::⏮
:::pause::⏸️
:::pausesy::⏸
:::stop::⏹️
:::stopsy::⏹
:::record::⏺️
:::recordsy::⏺
:::fleurdelis::⚜️
:::fleurdelissy::⚜
:::blackflag::🏴
:::whiteflag::🏳️

:::fem::‍♀️
:::masc::‍♂️
:::lgbt::🏳️‍🌈

:::rofl::🤣
:::liar::🤥
:::drooling::🤤
:::nausea::🤢
:::sneeze::🤧
:::cowboy::🤠
:::clown::🤡
:::backofhand::🤚
:::fingerscrossed::🤞
:::callsign::🤙
:::leftfist::🤛
:::rightfist::🤜
:::holdingphone::🤳
:::facepalm::🤦
:::shrug::🤷
:::doctor::‍⚕️
:::student::‍🎓
:::teacher::‍🏫
:::judge::‍⚖️
:::farmer::‍🌾
:::chef::‍🍳
:::mechanic::‍🔧
:::arcwelder::‍🏭
:::officeworker::‍💼
:::scientist::‍🔬
:::technologist::‍💻
:::singer::‍🎤
:::artist::‍🎨
:::pilot::‍✈️
:::astronaut::‍🚀
:::firefighter::‍🚒
:::prince::🤴
:::groom::🤵
:::pregnant::🤰
:::mrsclaus::🤶
:::dancing::🕺
:::fencing::🤺
:::cartwheeling::🤸
:::wrestling::🤼
:::waterpolo::🤽
:::handball::🤾
:::juggling::🤹
:::gorilla::🦍
:::fox::🦊
:::deer::🦌
:::rhinocerous::🦏
:::rhino::🦏
:::bat::🦇
:::eagle::🦅
:::duck::🦆
:::owl::🦉
:::lizard::🦎
:::shark::🦈
:::shrimp::🦐
:::squid::🦑
:::butterfly::🦋
:::wiltedrose::🥀
:::kiwi::🥝
:::avocado::🥑
:::potato::🥔
:::carrot::🥕
:::cucumber::🥒
:::peanuts::🥜
:::croissant::🥐
:::baguette::🥖
:::pancakes::🥞
:::bacon::🥓
:::stuffedflatbread::🥙
:::egg::🥚
:::pan::🥘
:::salad::🥗
:::milk::🥛
:::cheers::🥂
:::tumblerglass::🥃
:::spoon::🥄
:::1stplace::🥇
:::2ndplace::🥈
:::3rdplace::🥉
:::boxingglove::🥊
:::keikogi::🥋
:::goalnet::🥅
:::motorscooter::🛵
:::scooter::🛴
:::stopsign::🛑
:::canoe::🛶
:::drum::🥁
:::cart::🛒
:::blackheart::🖤
:::medical::⚕️
:::medicalsy::⚕

:::starstruck::🤩
:::zany::🤪
:::blushing::🤭
:::shh::🤫
:::raisedbrow::🤨
:::vomit::🤮
:::mindblown::🤯
:::monocole::🧐
:::swearing::🤬
:::loveyou::🤟
:::palms::🤲
:::brain::🧠
:::child::🧒‍
:::children::🧒‍🧒
:::person::🧑
:::parent::🧑‍
:::xparents::🧑‍🧑‍
:::beard::🧔
:::elder::🧓
:::headscarf::🧕
:::breastfeeding::🤱
:::mage::🧙
:::fairy::🧚
:::vampire::🧛
:::merperson::🧜
:::elf::🧝
:::genie::🧞
:::zombie::🧟
:::showering::🧖
:::climbing::🧗
:::yoga::🧘
:::zebra::🦓
:::giraffe::🦒
:::hedgehog::🦔
:::sauropod::🦕
:::trex::🦖
:::crickets::🦗
:::coconut::🥥
:::broccoli::🥦
:::coconut::🥨
:::meat::🥩
:::sandwich::🥪
:::bowl::🥣
:::cannedfood::🥫
:::dumpling::🥟
:::fortunecookie::🥠
:::takeout::🥡
:::pie::🥧
:::drink::🥤
:::chopsticks::🥢
:::sled::🛷
:::curlingstone::🥌
:::ufo::🛸
:::scarf::🧣
:::gloves::🧤
:::coat::🧥
:::socks::🧦
:::cap::🧢
:::orangeheart::🧡
:::eject::⏏️
:::ejectsy::⏏
:::eng::🏴󠁧󠁢󠁥󠁮󠁧󠁿
:::sct::🏴󠁧󠁢󠁳󠁣󠁴󠁿
:::wls::🏴󠁧󠁢󠁷󠁬󠁳󠁿

:::love::🥰
:::hot::🥵
:::cold::🥶
:::woozy::🥴
:::party::🥳
:::pleading::🥺
:::leg::🦵
:::foot::🦶
:::tooth::🦷
:::bone::🦴
:::redhair::‍🦰
:::curlyhair::‍🦱
:::whitehair::‍🦳
:::bald::‍🦲
:::superhero::🦸
:::supervillain::🦹
:::DNA::🧬
:::raccoon::🦝
:::llama::🦙
:::hippopotamus::🦛
:::hippo::🦛
:::kangaroo::🦘
:::badger::🦡
:::swan::🦢
:::peacock::🦚
:::parrot::🦜
:::lobster::🦞
:::mosquito::🦟
:::microbe::🦠
:::mango::🥭
:::veggy::🥬
:::bagel::🥯
:::salt::🧂
:::mooncake::🥮
:::cupcake::🧁
:::firecracker::🧨
:::redenvelope::🧧
:::softball::🥎
:::flyingdisc::🥏
:::lacrosse::🥍
:::jigsaw::🧩
:::pawn::♟️
:::pawnsy::♟
:::compass::🧭
:::brick::🧱
:::skateboard::🛹
:::luggage::🧳
:::teddybear::🧸
:::thread::🧵
:::yarn::🧶
:::goggles::🥽
:::labcoat::🥼
:::hikingboot::🥾
:::flatshoe::🥿
:::abacus::🧮
:::receipt::🧾
:::toolbox::🧰
:::magnet::🧲
:::vial::🧪
:::petridish::🧫
:::lotion::🧴
:::safetypin::🧷
:::broom::🧹
:::basket::🧺
:::paperroll::🧻
:::soap::🧼
:::sponge::🧽
:::fireextinguisher::🧯
:::nazaramulet::🧿
:::infinity::♾️
:::infinitysy::♾
:::pirate::🏴‍☠️
:::un::🇺🇳

:::yawn::🥱
:::pinch::🤏
:::mechanicalarm::🦾
:::mechanicalleg::🦿
:::hearingaid::🦻
:::deaf::🧏
:::standing::🧍
:::kneeling::🧎
:::holdingcane::‍🦯
:::inmotorizedwheelchair::‍🦼
:::inwheelchair::‍🦽
:::handholding::‍🤝‍
:::blood::🩸
:::orangutan::🦧
:::guidedog::🦮
:::servicedog::🐕‍🦺
:::sloth::🦥
:::otter::🦦
:::skunk::🦨
:::flamingo::🦩
:::oyster::🦪
:::saturn::🪐
:::garlic::🧄
:::onion::🧅
:::waffle::🧇
:::falafel::🧆
:::butter::🧈
:::juice::🧃
:::mate::🧉
:::ice::🧊
:::scuba::🤿
:::yoyo::🪀
:::kite::🪁
:::temple::🛕
:::wheelchair::🦽
:::motorizedwheelchair::🦼
:::rickshaw::🛺
:::parachute::🪂
:::vest::🦺
:::sari::🥻
:::swimsuit::🩱
:::briefs::🩲
:::shorts::🩳
:::balletshoes::🩰
:::banjo::🪕
:::diyalamp::🪔
:::axe::🪓
:::ax::🪓
:::cane::🦯
:::bandage::🩹
:::stethoscope::🩺
:::chair::🪑
:::razor::🪒
:::brownheart::🤎
:::whiteheart::🤍
:::orangecircle::🟠
:::yellowcircle::🟡
:::greencircle::🟢
:::purplecircle::🟣
:::browncircle::🟤
:::redsquare::🟥
:::orangesquare::🟧
:::yellowsquare::🟨
:::greensquare::🟩
:::bluesquare::🟦
:::purplesquare::🟪
:::brownsquare::🟫

:::happytear::🥲
:::disguise::🥸
:::che::🤌
:::anatomicalheart::🫀
:::lungs::🫁
:::ninja::🥷
:::feedingbaby::‍🍼
:::claus::‍🎄
:::hugging::🫂
:::blackcat::🐈‍⬛
:::bison::🦬
:::mammoth::🦣
:::beaver::🦫
:::polarbear::🐻‍❄️
:::dodo::🦤
:::feather::🪶
:::seal::🦭
:::beetle::🪲
:::roach::🪳
:::fly::🪰
:::worm::🪱
:::plant::🪴
:::rock::🪨
:::wood::🪵
:::blueberries::🫐
:::olive::🫒
:::bellpepper::🫑
:::flatbread::🫓
:::tamale::🫔
:::fondue::🫕
:::teapot::🫖
:::bobatea::🧋
:::wand::🪄
:::pinhata::🪅
:::pinata::🪅
:::nestingdoll::🪆
:::matryoshka::🪆
:::hut::🛖
:::truck::🛻
:::rollerskate::🛼
:::sewingneedle::🪡
:::knot::🪢
:::sandal::🩴
:::helmet::🪖
:::accordion::🪗
:::longdrum::🪘
:::coin::🪙
:::boomerang::🪃
:::carpentry::🪚
:::screwdriver::🪛
:::hook::🪝
:::ladder::🪜
:::mirror::🪞
:::window::🪟
:::plunger::🪠
:::mousetrap::🪤
:::bucket::🪣
:::toothbrush::🪥
:::grave::🪦
:::sign::🪧
:::elevatorsign::🛗
:::transgender::⚧️
:::transsy::⚧
:::trans::🏳️‍⚧️

:::faceinclouds::😶‍🌫️
:::exhale::😮‍💨
:::dizzyface::😵‍💫
:::loves::‍❤️‍💋‍
:::compatible::‍❤️‍
:::fireheart::❤️‍🔥
:::mendingheart::❤️‍🩹

:::melting::🫠
:::shock::🫢
:::peeking::🫣
:::salute::🫡
:::invisible::🫥
:::meh::🫤
:::aww::🥹
:::handright::🫱
:::handleft::🫲
:::handdown::🫳
:::handup::🫴
:::fingerheart::🫰
:::you::🫵
:::handheart::🫶
:::shaker::‍🫲
:::bitinglip::🫦
:::royal::🫅
:::mpregnant::🫃
:::xpregnant::🫄
:::troll::🧌
:::coral::🪸
:::lotus::🪷
:::nest::🪹
:::nestwitheggs::🪺
:::beans::🫘
:::pouring::🫗
:::jar::🫙
:::disco::🪩
:::slide::🛝
:::wheel::🛞
:::floater::🛟
:::lowbattery::🪫
:::crutch::🩼
:::xray::🩻
:::bubbles::🫧
:::hamsa::🪬
:::idcard::🪪
:::equals::🟰

:::shaking::🫨
:::pushleft::🫷
:::pushright::🫸
:::moose::🫎
:::donkey::🫏
:::wing::🪽
:::blackbird::🐦‍⬛
:::goose::🪿
:::jellyfish::🪼
:::hyacinth::🪻
:::ginger::🫚
:::peas::🫛
:::fan::🪭
:::comb::🪮
:::maracas::🪇
:::flute::🪈
:::pinkheart::🩷
:::lightblueheart::🩵
:::greyheart::🩶
:::grayheart::🩶
:::khanda::🪯
:::wifi::🛜

:::shake::🙂‍↔️
:::nod::🙂‍↕️
:::rightward::‍➡️
:::phoenix::🐦‍🔥
:::lime::🍋‍🟩
:::brownmushroom::🍄‍🟫
:::brokenchain::⛓️‍💥

:::tired::🫩
:::fingerprint::🫆
:::deadtree::🪾
:::wintertree::🪾
:::beet::🫜
:::harp::🪉
:::shovel::🪏
:::splat::🫟
:::cq::🇨🇶

:::distorted::🫪
:::bigfoot::🫈
:::ballet::🧑‍🩰
:::bunnydance::‍🐰‍
:::wrestle::‍🫯‍
:::orca::🫍
:::landslide::🛘
:::trombone::🪊
:::treasure::🪎
:::fighting::🫯